apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: admin-portal
  namespace: admin-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admin-portal
