apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: admin-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: admin-portal
  ports:
    - {name: http, protocol: TCP, port: 8081, targetPort: http}
