(function(){
  'use strict';
  if(window.EclipseDomainAPI.isMock('llm'))return;
  const U=window.EclipsePortalUI;let response='',submissionKey=null,monitoringResponse='',monitoringKey=null;
  const ui=U.controller(async()=>{
    const scopes=window.EclipseAuth.user()?.scopes||[];
    return {models:scopes.includes('llm:invoke')?await window.EclipseAPI.get('/llm/models'):null,
      monitoring:scopes.includes('monitoring:assist')?await window.EclipseAPI.get('/llm/monitoring-assistant'):null,
      usage:scopes.includes('llm:usage:read')?await window.EclipseAPI.get('/llm/usage'):null};
  },(path,data)=>{
    if(path.endsWith('/monitoring-assistant'))return U.card('Monitoring assistant',`<p>${U.esc(data.monitoring?.status||'NOT_CONNECTED')} · SANITIZED_NUMERIC_SIGNALS_ONLY · advisory only</p><form id="monitoring-assistant"><div class="config-grid"><label class="config-field"><span>Signal ID</span><input name="signalId" value="synthetic-cpu-001" pattern="[A-Za-z0-9_.:-]{1,64}" required></label><label class="config-field"><span>Metric</span><input name="metricName" value="service_cpu_utilization" pattern="[A-Za-z_:][A-Za-z0-9_:]{0,127}" required></label><label class="config-field"><span>Current value</span><input name="currentValue" type="number" step="any" value="82" required></label><label class="config-field"><span>Baseline value</span><input name="baselineValue" type="number" step="any" value="45" required></label><label class="config-field"><span>Anomaly score</span><input name="anomalyScore" type="number" min="0" max="1" step="0.01" value="0.86" required></label><label class="config-field"><span>State</span><select name="state"><option>WARNING</option><option>REVIEW_REQUIRED</option><option>ANOMALY_DETECTED</option><option>NORMAL</option></select></label><label class="config-field"><span>Goal</span><select name="goal"><option>TRIAGE_SUMMARY</option><option>TREND_EXPLANATION</option><option>OPERATOR_CHECKLIST</option></select></label></div><button class="button primary" type="submit" ${data.monitoring?.status==='NOT_CONNECTED'?'disabled':''}>Analyze sanitized signal</button><p id="monitoring-error" role="alert"></p><p>${U.esc(monitoringResponse)}</p></form>`,'No raw logs, IPs, identities or free-form prompts · human review required · no action authority');
    if(path.endsWith('/service'))return U.card('LLM service',`<form id="llm-chat"><label class="config-field"><span>Model</span><select name="model">${(data.models?.items||[]).map(m=>`<option value="${U.esc(m.id)}">${U.esc(m.name)} · ${U.esc(m.status)}</option>`).join('')}</select></label><label class="config-field"><span>Prompt · local simulator only</span><textarea name="prompt" maxlength="2000" required></textarea></label><button class="button primary" type="submit" ${data.models?.items[0]?.status!=='SIMULATED'?'disabled':''}>Send</button><p id="chat-error" role="alert"></p><p>${U.esc(response)}</p></form>`,'No external model connected · prompts are not persisted');
    if(path.endsWith('/usage'))return U.card('Usage',U.table(['Time','Model','Input units','Output units'],(data.usage?.items||[]).map(r=>[U.esc(r.created_at),U.esc(r.model),U.esc(r.input_units),U.esc(r.output_units)])),'Character-based simulation units; provider tokens have not been measured');
    if(path.endsWith('/cost'))return U.card('Token cost',U.metrics([['Actual charges',U.money(data.usage?.amount_krw)],['Billing','NOT_CONNECTED']]),'No invented billing or forecast');
    return U.metrics([['Provider','NOT_CONNECTED'],['Local calls',data.usage?.requests??'No usage scope'],['Simulation units',data.usage?.simulation_units??'No usage scope'],['Actual tokens','Not measured']])+U.card('Models',U.table(['Model','Readiness'],(data.models?.items||[]).map(m=>[U.esc(m.name),U.badge(m.status)])),'Development simulator requires explicit enablement')+U.card('Small workspace','<button class="button" type="button" data-workspace>Request Small workspace</button><p id="workspace-error" role="alert"></p>','DEVELOPER_WORKSPACE · adapter not implemented');
  },root=>{const monitor=root.querySelector('#monitoring-assistant');if(monitor)monitor.onsubmit=async e=>{e.preventDefault();if(!monitor.reportValidity())return;const button=monitor.querySelector('[type="submit"]');button.disabled=true;monitoringKey=monitoringKey||U.key();try{const result=await U.post('/llm/monitoring-assistant/analyze',{analysis_goal:monitor.goal.value,signals:[{signal_id:monitor.signalId.value,observed_at:new Date().toISOString(),source:'SYNTHETIC_TEST',metric_name:monitor.metricName.value,current_value:Number(monitor.currentValue.value),baseline_value:Number(monitor.baselineValue.value),anomaly_score:Number(monitor.anomalyScore.value),state:monitor.state.value}]},monitoringKey);monitoringResponse=result.advisory;monitoringKey=null;await ui.reload();}catch(error){monitor.querySelector('#monitoring-error').textContent=error.message;button.disabled=false;}};const workspace=root.querySelector('[data-workspace]');if(workspace)workspace.onclick=async()=>{workspace.disabled=true;try{await U.post('/llm/workspace-requests',{size:'SMALL'});}catch(error){root.querySelector('#workspace-error').textContent=error.message;}finally{workspace.disabled=false;}};const form=root.querySelector('#llm-chat');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type="submit"]');button.disabled=true;submissionKey=submissionKey||U.key();try{const result=await U.post('/llm/chat',{model:form.model.value,prompt:form.prompt.value},submissionKey);response=result.message;submissionKey=null;await ui.reload();}catch(error){form.querySelector('#chat-error').textContent=error.message;button.disabled=false;}};});
  window.EclipseLLM={render:path=>{if(ui.state.identity!==JSON.stringify(window.EclipseAuth.user())){response='';submissionKey=null;monitoringResponse='';monitoringKey=null;}return ui.render(path);},bind:(root,path)=>{if(path.startsWith('/llm/'))ui.bind(root,path);},reset:()=>{response="";submissionKey=null;monitoringResponse='';monitoringKey=null;ui.resetCache();},reload:()=>ui.reload()};
}());
