(function () {
  'use strict';
  const store = {
    requests: [
      {id:'MFG-REQ-00291', project:'ecommerce-api', sku:'MFG-CP-STD', environment:'DEV', status:'ACTIVE', created:'2026-09-09', cost:397000},
      {id:'MFG-REQ-00290', project:'commerce-staging', sku:'MFG-CP-STD', environment:'STG', status:'UNDER_REVIEW', created:'2026-09-08', cost:397000},
      {id:'MFG-REQ-00287', project:'legacy-api-test', sku:'MFG-CP-DEV', environment:'DEV', status:'DESTROYED', created:'2026-08-29', cost:168000},
      {id:'MFG-REQ-00284', project:'quality-prod', sku:'MFG-CP-PRD', environment:'PROD', status:'REJECTED', created:'2026-08-27', cost:869000,rejection_reason:'운영 환경에는 Daily + Weekly 백업과 Private 노출 정책이 필요합니다. 설정을 보완해 다시 신청해 주세요.',feedback_source:'POLICY_ASSISTANT'},
    ],
    resources: [
      {name:'Production', project:'commerce-prod', type:'Kubernetes', status:'ACTIVE',spec:'8 vCPU / 16 GB',database:'PostgreSQL 100 GB',created:'2026-08-11',expires:'2026-11-11'},
      {name:'Development', project:'ecommerce-api', type:'Kubernetes', status:'ACTIVE',spec:'4 vCPU / 8 GB',database:'PostgreSQL 50 GB',created:'2026-09-09',expires:'2026-10-09'},
      {name:'Test', project:'erp-adapter', type:'VM', status:'PROVISIONING',spec:'2 vCPU / 4 GB',database:'None',created:'2026-09-11',expires:'2026-09-18'},
    ],
  };
  const state = {step:1, sku:'MFG-CP-STD', project:'ecommerce-api', environment:'DEV', computeType:'Kubernetes Node', size:'Medium', vcpu:4, memory:8, count:2, networkType:'Managed VPC', subnet:'Application', exposure:'Private', security:'Manufacturing Standard', loadBalancer:true, storageType:'SSD', storageCapacity:100, ttl:'30', customTtl:'', runtime:'Kubernetes', database:'PostgreSQL', databaseStorage:50, redis:true, objectStorage:true, messageQueue:true, monitoring:true, cicd:true, nightShutdown:true, deployment:'AUTO', backup:'Daily'};
  const skus = {
    'MFG-CP-DEV': {name:'Factory Dev',tier:'DEVELOPMENT',copy:'개발·PoC용 단일 노드 통합 환경',cost:168000,specs:['Kubernetes · Small × 1','PostgreSQL 20 GB','Object Storage · CI/CD'],configuration:{environment:'DEV',computeType:'Kubernetes Node',size:'Small',count:1,networkType:'Managed VPC',subnet:'Application',exposure:'Private',security:'Manufacturing Standard',loadBalancer:false,storageType:'SSD',storageCapacity:50,ttl:'30',customTtl:'',runtime:'Kubernetes',database:'PostgreSQL',databaseStorage:20,redis:false,objectStorage:true,messageQueue:false,cicd:true,nightShutdown:true,backup:'Daily'}},
    'MFG-CP-STD': {name:'Factory Standard',tier:'STANDARD',copy:'MES·품질 서비스용 표준 Kubernetes 환경',cost:397000,specs:['Kubernetes · Medium × 2','PostgreSQL 50 GB','Redis · MQ · CI/CD'],configuration:{environment:'STG',computeType:'Kubernetes Node',size:'Medium',count:2,networkType:'Managed VPC',subnet:'Application',exposure:'Private',security:'Manufacturing Standard',loadBalancer:true,storageType:'SSD',storageCapacity:100,ttl:'30',customTtl:'',runtime:'Kubernetes',database:'PostgreSQL',databaseStorage:50,redis:true,objectStorage:true,messageQueue:true,cicd:true,nightShutdown:true,backup:'Daily'}},
    'MFG-CP-PRD': {name:'Factory Production',tier:'PRODUCTION',copy:'생산 핵심 시스템용 고가용성 운영 환경',cost:869000,specs:['Kubernetes · Large × 3','PostgreSQL 200 GB','Dedicated VPC · High IOPS'],configuration:{environment:'PROD',computeType:'Kubernetes Node',size:'Large',count:3,networkType:'Dedicated VPC',subnet:'Application',exposure:'Private',security:'Restricted',loadBalancer:true,storageType:'High IOPS',storageCapacity:500,ttl:'Custom',customTtl:'90',runtime:'Kubernetes',database:'PostgreSQL',databaseStorage:200,redis:true,objectStorage:true,messageQueue:true,cicd:true,nightShutdown:false,backup:'Daily + Weekly'}},
  };
  const partnerHub = {
    name:'PartnerHub Cloud',
    category:'SMT LOT QUALITY SAAS',
    status:'PILOT',
    target:'SMT 공정을 보유한 전자제품 제조기업 및 협력사',
    copy:'PCB Lot의 품질 리스크를 이미지·센서·공정조건 AI 분석과 연결해 조기에 발견하고, 조치와 협력사 이력을 한곳에서 관리합니다.',
    platform:'MFG-CP-PRD',
    commercial:'SaaS 구독 + AI 판정량 + 온보딩·재학습',
    workflow:[
      ['01','Lot 납품','협력사 PCB Lot 입고'],
      ['02','데이터 유입','이미지·센서·공정조건'],
      ['03','AI Risk 제안','HIGH · MEDIUM · LOW'],
      ['04','공급망 연결','Lot과 협력사 연결'],
      ['05','Alert','품질 Dashboard 알림'],
      ['06','담당자 조치','Hold · 재검사 지정'],
      ['07','이력 누적','협력사 품질 이력 반영'],
    ],
    capabilities:[
      ['조기 위험 감지','완제품 조립 전에 Lot 품질 위험을 확인합니다.'],
      ['복합 신호 분석','이미지와 센서·공정조건을 함께 분석합니다.'],
      ['담당자 승인','AI가 제안하고 Hold·재검사는 담당자가 결정합니다.'],
      ['협력사 이력','조치 결과를 공급망 품질 이력으로 연결합니다.'],
    ],
    layers:[
      ['1','사용자 / 클라이언트','웹 대시보드 · REST API · HTTPS · 역할 기반 접근'],
      ['2','애플리케이션','Partner Core · Lot Quality · Inference API · Kubernetes'],
      ['3','클라우드 인프라','Managed Kubernetes · PostgreSQL · Object Storage · VPC / IAM'],
    ],
  };
  const lifecycle = ['REQUESTED','UNDER_REVIEW','APPROVED','PROVISIONING','ACTIVE','SETTLEMENT','EXPIRED','DESTROYING','DESTROYED'];
  const failureStates = ['REJECTED','PROVISION_FAILED','DESTROY_FAILED'];
  const resourceTabs = ['Overview','Resources','Network','Access','Monitoring','Cost','Lifecycle'];
  let selectedResource = null;
  let selectedResourceTab = 'Overview';
  let restoreResourceTabFocus = false;
  const esc = value => String(value == null ? '' : value).replace(/[&<>\"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const money = value => `₩${Number(value).toLocaleString('ko-KR')}`;
  function applySku(code) { const sku=skus[code]; if(!sku)return; state.sku=code; Object.assign(state,sku.configuration); state.step=1; }
  function estimate() { const compute={Small:70000,Medium:120000,Large:220000,Custom:Math.max(70000,state.vcpu*22000+state.memory*5000)}[state.size]; const platform=state.computeType==='Kubernetes Node'?35000:12000; const db=state.database==='None'?0:35000+Number(state.databaseStorage)*350; const services=(state.redis?18000:0)+(state.objectStorage?9000:0)+(state.messageQueue?16000:0)+(state.loadBalancer?14000:0)+(state.cicd?12000:0); return Math.round((compute*state.count+platform+db+services)/1000)*1000; }
  function dashboard() { return `<div class="metric-grid"><article><span>Active environments</span><strong>${store.resources.filter(item=>item.status==='ACTIVE').length}</strong><small>Manufacturing tenant</small></article><article><span>Pending requests</span><strong>${store.requests.filter(item=>['REQUESTED','UNDER_REVIEW'].includes(item.status)).length}</strong><small>Awaiting MSP review</small></article><article><span>Current cost</span><strong>₩482,300</strong><small class="demo-tag">DEMO DATA</small></article><article><span>Alerts</span><strong>0</strong><small>All systems healthy</small></article></div><div class="domain-grid"><article class="data-card"><div class="card-head"><div><h3>Recent requests</h3><p>Cloud Platform lifecycle</p></div><a href="#/manufacturing/requests">View all →</a></div>${requestRows(store.requests.slice(0,3))}</article><article class="data-card"><div class="card-head"><div><h3>Manufacturing Service</h3><p>Service readiness</p></div><a href="#/manufacturing/services">View service →</a></div><div class="service-health"><span>▥</span><div><strong>${esc(partnerHub.name)}</strong><small>SMT Lot quality · Pilot scope defined</small></div><b>${esc(partnerHub.status)}</b></div></article></div>`; }
  function catalog() { return `<div class="product-grid manufacturing-catalog"><article class="product featured package-product"><span class="product-art">☁</span><div><small>MANUFACTURING · CORE PLATFORM</small><h3>Cloud Platform Package</h3><p>IaaS와 PaaS를 하나의 승인·프로비저닝 수명주기로 제공하는 제조 워크로드 패키지입니다.</p><div class="package-columns"><div><b>IaaS Configuration</b><span>Compute · Network · Load Balancer · Storage · TTL</span></div><div><b>PaaS Configuration</b><span>Runtime · Database · Redis · MQ · CI/CD · Monitoring</span></div></div><div class="sku-grid">${Object.entries(skus).map(([code,sku])=>`<article class="sku-card ${code===state.sku?'selected':''}"><small>${esc(sku.tier)}</small><code>${esc(code)}</code><h4>${esc(sku.name)}</h4><p>${esc(sku.copy)}</p><ul>${sku.specs.map(spec=>`<li>${esc(spec)}</li>`).join('')}</ul><div><span>월 예상</span><strong>${money(sku.cost)}</strong></div><a class="button ${code===state.sku?'primary':''}" href="#/manufacturing/configurator" data-mfg-sku="${esc(code)}">${code===state.sku?'Continue':'Select'} ${esc(sku.name)}</a></article>`).join('')}</div></div></article><article class="product partnerhub-product"><span class="product-art pale">▥</span><div><small>MANUFACTURING SAAS · ${esc(partnerHub.status)}</small><h3>${esc(partnerHub.name)}</h3><p>AI 기반 실시간 SMT Lot 품질관리 서비스입니다.</p><ul><li>이미지·센서·공정조건 통합</li><li>Lot Risk Score와 Dashboard Alert</li><li>Hold·재검사 및 협력사 이력</li></ul><a class="button" href="#/manufacturing/services">Explore service <span>→</span></a></div></article></div>`; }
  function field(label, control, help) { return `<label class="config-field"><span>${label}</span>${control}${help?`<small>${help}</small>`:''}</label>`; }
  function select(name, options, value) { return `<select name="${name}">${options.map(option=>`<option ${option===value?'selected':''}>${esc(option)}</option>`).join('')}</select>`; }
  function toggle(name,label,help,checked,locked) { return `<label class="switch-row"><div><strong>${label}</strong><small>${help}</small></div>${locked?'<b>Included</b>':''}<input type="checkbox" name="${name}" ${checked?'checked':''} ${locked?'disabled':''}><i></i></label>`; }
  function choice(name, options, value) { return `<div class="config-choices">${options.map(option=>`<label><input type="radio" name="${name}" value="${esc(option)}" ${option===value?'checked':''}><span>${esc(option)}</span></label>`).join('')}</div>`; }
  function stepProject() { return `<div class="wizard-step"><div class="step-title"><span>01</span><div><h3>Project / Environment</h3><p>프로젝트와 환경 등급을 설정합니다.</p></div></div><div class="config-grid">${field('Project name','<input name="project" value="'+esc(state.project)+'" pattern="[a-z][a-z0-9-]{2,39}" required>','영문 소문자, 숫자, 하이픈을 사용하세요.')}${field('Environment',choice('environment',['DEV','STG','PROD'],state.environment))}</div></div>`; }
  function stepIaas() { const custom=state.size==='Custom'?`<div class="config-grid custom-spec">${field('vCPU','<input type="number" name="vcpu" min="1" max="64" value="'+state.vcpu+'">')}${field('Memory GB','<input type="number" name="memory" min="2" max="512" value="'+state.memory+'">')}${field('Instance count','<input type="number" name="count" min="1" max="20" value="'+state.count+'">')}</div>`:''; return `<div class="wizard-step"><div class="step-title"><span>02</span><div><h3>IaaS Configuration</h3><p>컴퓨트·네트워크·스토리지 기반을 설정합니다.</p></div></div><h4>Compute</h4>${field('Compute type',choice('computeType',['VM','Kubernetes Node'],state.computeType))}${field('Compute size',choice('size',['Small','Medium','Large','Custom'],state.size))}${custom}<h4>Network & Security</h4><div class="config-grid">${field('Network type',select('networkType',['Managed VPC','Dedicated VPC'],state.networkType))}${field('Subnet',select('subnet',['Application','Data','DMZ'],state.subnet))}${field('Exposure',choice('exposure',['Private','Public'],state.exposure))}${field('Security policy',select('security',['Manufacturing Standard','Restricted','Custom Policy'],state.security))}</div><h4>Load Balancer & Storage</h4><div class="config-grid">${toggle('loadBalancer','Load Balancer','Automatic traffic distribution',state.loadBalancer)}${field('Storage type',select('storageType',['SSD','HDD','High IOPS'],state.storageType))}${field('Capacity GB','<input type="number" name="storageCapacity" min="20" max="4096" value="'+state.storageCapacity+'">')}${field('TTL',select('ttl',['1','7','30','Custom'],state.ttl)+(state.ttl==='Custom'?'<input class="inline-custom" type="number" name="customTtl" min="1" max="90" value="'+esc(state.customTtl)+'" placeholder="Days">':''),'만료 시 회수 프로세스가 자동 시작됩니다.')}</div></div>`; }
  function stepPaas() { return `<div class="wizard-step"><div class="step-title"><span>03</span><div><h3>PaaS Configuration</h3><p>애플리케이션 런타임과 관리형 서비스를 선택합니다.</p></div></div><div class="config-grid">${field('Runtime',choice('runtime',['Kubernetes','VM Application Runtime'],state.runtime))}${field('Database',select('database',['PostgreSQL','MySQL','None'],state.database))}${state.database!=='None'?field('Database storage GB','<input type="number" name="databaseStorage" min="20" max="2048" value="'+state.databaseStorage+'">'):''}</div><div class="switch-list">${toggle('redis','Redis','Managed in-memory cache',state.redis)}${toggle('objectStorage','Object Storage','Secure object storage',state.objectStorage)}${toggle('messageQueue','Message Queue','Asynchronous event delivery',state.messageQueue)}${toggle('monitoring','Monitoring','Metrics, logs and alerts',true,true)}${toggle('cicd','CI/CD Integration','Deployment pipeline connection',state.cicd)}</div></div>`; }
  function stepPolicy() { return `<div class="wizard-step"><div class="step-title"><span>04</span><div><h3>Operation Policy</h3><p>운영 자동화 정책을 설정합니다.</p></div></div><div class="policy-callout"><span>◆</span><div><small>Deployment Policy</small><strong>AUTO</strong><p>내부 정책이 승인 후 Terraform Provider를 결정합니다.</p></div></div><div class="switch-list">${toggle('nightShutdown','Night Shutdown','22:00–08:00 자동 중지',state.nightShutdown)}</div><div class="config-grid">${field('Backup policy',select('backup',['None','Daily','Daily + Weekly'],state.backup))}${field('Deployment',select('deployment',['AUTO'],state.deployment),'고객에게 Cloud Provider 선택을 강제하지 않습니다.')}</div></div>`; }
  function summaryRows() { return `<dl class="review-list"><div><dt>Product SKU</dt><dd>${esc(state.sku)} · ${esc(skus[state.sku]?.name||'Custom')}</dd></div><div><dt>Project / Environment</dt><dd>${esc(state.project)} · ${esc(state.environment)}</dd></div><div><dt>Compute</dt><dd>${esc(state.computeType)} · ${esc(state.size)}${state.size==='Custom'?` (${state.vcpu} vCPU / ${state.memory} GB × ${state.count})`:''}</dd></div><div><dt>Network</dt><dd>${esc(state.networkType)} · ${esc(state.subnet)} · ${esc(state.exposure)}</dd></div><div><dt>Storage</dt><dd>${esc(state.storageType)} · ${state.storageCapacity} GB</dd></div><div><dt>Runtime / Database</dt><dd>${esc(state.runtime)} · ${esc(state.database)}${state.database!=='None'?` ${state.databaseStorage} GB`:''}</dd></div><div><dt>Managed services</dt><dd>${[state.redis&&'Redis',state.objectStorage&&'Object Storage',state.messageQueue&&'Message Queue',state.cicd&&'CI/CD','Monitoring'].filter(Boolean).join(' · ')}</dd></div><div><dt>Policy</dt><dd>AUTO · ${state.backup} backup · TTL ${state.ttl==='Custom'?state.customTtl:state.ttl} days</dd></div></dl>`; }
  function stepCost() { return `<div class="wizard-step"><div class="step-title"><span>05</span><div><h3>Cost Estimate</h3><p>구성 기준 월 예상 비용입니다.</p></div></div><div class="cost-panel"><small>ESTIMATED MONTHLY COST · DEMO DATA</small><strong>${money(estimate())}</strong><p>실제 Cloud Provider와 사용량에 따라 달라질 수 있습니다.</p></div>${summaryRows()}</div>`; }
  function stepReview() { return `<div class="wizard-step"><div class="step-title"><span>06</span><div><h3>Review & Submit</h3><p>한 번의 요청으로 전체 패키지를 제출합니다.</p></div></div><div class="review-head"><div><small>MANUFACTURING · ${esc(state.sku)}</small><h3>Cloud Platform Package</h3></div><span>Deployment · AUTO</span></div>${summaryRows()}<label class="config-field note-field"><span>Request note</span><textarea name="note" minlength="5" maxlength="1000" required>제조 서비스 개발 및 운영 환경 구성</textarea></label></div>`; }
  const steps=[stepProject,stepIaas,stepPaas,stepPolicy,stepCost,stepReview];
  function configurator() { return `<div class="wizard-layout"><form id="mfg-wizard" class="wizard-card"><ol class="wizard-progress">${['Project','IaaS','PaaS','Policy','Cost','Review'].map((label,index)=>`<li class="${index+1===state.step?'active':index+1<state.step?'done':''}"><span>${index+1<state.step?'✓':index+1}</span><b>${label}</b></li>`).join('')}</ol>${steps[state.step-1]()}<div class="wizard-actions">${state.step>1?'<button type="button" class="button" data-back>← Back</button>':'<span></span>'}<button type="${state.step===6?'submit':'button'}" class="button primary" ${state.step<6?'data-next':''}>${state.step===6?'Submit Request':'Continue'} →</button></div><p id="wizard-message" class="wizard-message"></p></form><aside class="live-summary"><small>LIVE SUMMARY · ${esc(state.sku)}</small><h3>${esc(skus[state.sku]?.name||'Cloud Platform')}</h3><p>${esc(state.project)}</p><dl><div><dt>Environment</dt><dd>${esc(state.environment)}</dd></div><div><dt>Compute</dt><dd>${esc(state.computeType)}</dd></div><div><dt>Size</dt><dd>${esc(state.size)}</dd></div><div><dt>Runtime</dt><dd>${esc(state.runtime)}</dd></div><div><dt>Database</dt><dd>${esc(state.database)}</dd></div><div><dt>Deployment</dt><dd class="auto">● AUTO</dd></div></dl><div><span>Estimated Cost <b>DEMO</b></span><strong>${money(estimate())}<small>/ month</small></strong></div></aside></div>`; }
  function requestRows(items) { return `<div class="domain-rows">${items.map(item=>`<div><strong>${esc(item.id)}</strong><span><b>${esc(item.project)}</b><small>${esc(item.sku||'MFG-CP-STD')} · ${esc(item.environment)}</small>${item.rejection_reason?`<small class="request-feedback"><b>${esc(item.feedback_source||'MSP_OPERATOR')}</b> ${esc(item.rejection_reason)}</small>`:''}</span><time>${esc(item.created)}</time><em class="domain-status ${item.status.toLowerCase()}">${esc(item.status)}</em></div>`).join('')}</div>`; }
  function requests() { return `<div class="request-stats"><article><span>All requests</span><strong>${store.requests.length}</strong></article><article><span>Under review</span><strong>${store.requests.filter(item=>['REQUESTED','UNDER_REVIEW'].includes(item.status)).length}</strong></article><article><span>Active</span><strong>${store.requests.filter(item=>item.status==='ACTIVE').length}</strong></article></div><article class="data-card"><div class="card-head"><div><h3>Manufacturing requests</h3><p>Tenant-isolated request context</p></div></div>${requestRows(store.requests)}<div class="lifecycle-strip">${lifecycle.map(status=>`<span>${status}</span>`).join('<i>→</i>')}</div><div class="failure-strip"><small>Exception states</small>${failureStates.map(status=>`<span>${status}</span>`).join('')}</div></article>`; }
  function detailGrid(items) { return `<div class="detail-overview">${items.map(([label,value,className])=>`<div><small>${esc(label)}</small><strong class="${className||''}">${value}</strong></div>`).join('')}</div>`; }
  function resourceTabContent(item) {
    const panels = {
      Overview: `${detailGrid([['STATUS',`● ${esc(item.status)}`,'auto'],['PLATFORM',esc(item.type)],['COMPUTE',esc(item.spec)],['DATABASE',esc(item.database)],['REDIS','Enabled'],['OBJECT STORAGE','Enabled'],['CREATED',esc(item.created)],['EXPIRES',esc(item.expires)]])}<div class="detail-health"><span>CPU <b>43%</b></span><span>Memory <b>61%</b></span><span>Pods <b>8 / 8</b></span><span>Network <b class="auto">Normal</b></span></div>`,
      Resources: `${detailGrid([['COMPUTE POOL',esc(item.spec)],['RUNTIME',esc(item.type)],['DATABASE',esc(item.database)],['BLOCK STORAGE','100 GB SSD'],['OBJECT STORAGE','Enabled'],['BACKUP','Daily · 14 days'],['AUTO SCALING',item.type==='Kubernetes'?'2–6 nodes':'Disabled'],['REGION','Policy selected']])}<p class="detail-note">All resources are managed as one Cloud Platform package.</p>`,
      Network: `${detailGrid([['NETWORK','Managed VPC'],['SUBNET','Application'],['EXPOSURE','Private'],['LOAD BALANCER','Enabled'],['PRIVATE DNS',`${esc(item.project)}.internal`],['EGRESS','Policy controlled'],['TLS','Managed certificate'],['HEALTH','● Normal','auto']])}<p class="detail-note">Provider and CIDR details remain hidden from customer roles.</p>`,
      Access: `${detailGrid([['ACCESS MODEL','Just-in-time grant'],['ACTIVE GRANTS','0'],['DEFAULT TTL','4 hours'],['MFA','Required'],['AUDIT','Enabled'],['SECRET STORAGE','External vault'],['SSH PUBLIC','Disabled'],['POLICY','Least privilege']])}<p class="detail-note">Privileged access requires a separate approved grant and is automatically revoked.</p>`,
      Monitoring: `${detailGrid([['SERVICE','● Healthy','auto'],['CPU','43%'],['MEMORY','61%'],['PODS','8 / 8'],['API P95','184 ms'],['ERROR RATE','0.08%'],['LOG RETENTION','30 days'],['ALERTS','0 open']])}<p class="detail-note demo-tag">DEMO DATA · Production metrics will be supplied by Prometheus and Grafana.</p>`,
      Cost: `${detailGrid([['CURRENT MONTH','₩218,000'],['PROJECTED','₩312,000'],['COMPUTE','₩126,000'],['DATABASE','₩58,000'],['STORAGE','₩14,000'],['MSP FEE','₩20,000'],['BUDGET USED','62%'],['NIGHT SAVING','₩31,200']])}<p class="detail-note demo-tag">DEMO DATA · Estimates exclude tax and may change with actual usage.</p>`,
      Lifecycle: `<ol class="resource-lifecycle">${['REQUESTED','APPROVED','PROVISIONING','ACTIVE'].map((status,index)=>`<li class="${item.status===status||index<3?'done':''}"><span>${index<3?'✓':index+1}</span><div><strong>${status}</strong><small>${index===0?item.created:index===1?item.created:index===2?item.created:item.status==='ACTIVE'?'Current state':'Pending'}</small></div></li>`).join('')}<li><span>5</span><div><strong>EXPIRES</strong><small>${esc(item.expires)}</small></div></li><li><span>6</span><div><strong>DESTROYED</strong><small>Automatic after expiry</small></div></li></ol>`,
    };
    return panels[selectedResourceTab] || panels.Overview;
  }
  function resourceDetail(item) { return `<article class="resource-detail"><div class="review-head"><div><small>MY INFRASTRUCTURE</small><h3>${esc(item.name)} · ${esc(item.project)}</h3></div><button class="button" data-close-resource>Close</button></div><nav class="detail-tabs" role="tablist" aria-label="Infrastructure detail">${resourceTabs.map(tab=>`<button type="button" role="tab" aria-selected="${tab===selectedResourceTab}" class="${tab===selectedResourceTab?'active':''}" data-resource-tab="${tab}">${tab}</button>`).join('')}</nav><section class="detail-panel" role="tabpanel" aria-label="${esc(selectedResourceTab)}">${resourceTabContent(item)}</section></article>`; }
  function infrastructure() { const selected=store.resources.find(item=>item.project===selectedResource); return `${selected?resourceDetail(selected):''}<div class="resource-grid">${store.resources.map(item=>`<article><div><span>${esc(item.name.slice(0,1))}</span><h3>${esc(item.name)}</h3></div><p>${esc(item.project)}</p><dl><div><dt>Platform</dt><dd>${esc(item.type)}</dd></div><div><dt>Compute</dt><dd>${esc(item.spec)}</dd></div><div><dt>Database</dt><dd>${esc(item.database)}</dd></div><div><dt>Expires</dt><dd>${esc(item.expires)}</dd></div><div><dt>Status</dt><dd class="auto">● ${esc(item.status)}</dd></div></dl><button class="button" data-resource="${esc(item.project)}">View detail</button></article>`).join('')}</div>`; }
  function monitoring() { return `<div class="monitor-grid customer-monitor"><article class="service-gauge"><small>SERVICE STATUS</small><strong>● Healthy</strong><p>All Cloud Platform checks passing</p></article><article class="service-gauge"><small>PODS</small><strong>8 / 8</strong><p>Desired replicas available</p></article><article class="service-gauge"><small>NETWORK</small><strong>● Normal</strong><p>Private endpoint reachable</p></article></div><article class="data-card monitoring-preview"><div><small>CPU</small><strong>43%</strong></div><div><small>Memory</small><strong>61%</strong></div><div><small>API p95</small><strong>184ms</strong></div><div><small>Error rate</small><strong>0.08%</strong></div><button class="button" type="button">Open Grafana ↗</button><small class="demo-tag">DEMO DATA</small></article>`; }
  function finops() { const days=[42,48,44,61,58,72,66,75,69,82,76,88]; return `<div class="metric-grid"><article><span>Current month</span><strong>₩482,300</strong><small class="demo-tag">DEMO DATA</small></article><article><span>Projected</span><strong>₩691,000</strong><small>September forecast</small></article><article><span>MSP service fee</span><strong>₩100,000</strong><small>Platform operations</small></article><article><span>Night saving</span><strong>₩68,400</strong><small>Estimated</small></article></div><div class="domain-grid finops-grid"><article class="data-card cost-breakdown"><div class="card-head"><div><h3>Cost allocation</h3><p>KT Cloud resource + MSP fee</p></div></div>${[['Compute','₩231,000'],['Database','₩127,000'],['Storage','₩24,000'],['MSP Fee','₩100,000']].map(([name,cost])=>`<div><span>${name}</span><strong>${cost}</strong></div>`).join('')}</article><article class="data-card daily-cost"><div class="card-head"><div><h3>Cost by day</h3><p>September · DEMO DATA</p></div></div><div class="mini-chart" aria-label="Daily cost trend">${days.map((value,index)=>`<i style="height:${value}%"><span>${index+1}</span></i>`).join('')}</div></article></div>`; }
  function services() { return `<section class="partnerhub-overview"><div><div class="partnerhub-labels"><small>${esc(partnerHub.category)}</small><em>${esc(partnerHub.status)}</em></div><h3>AI 기반 실시간 Lot 품질관리</h3><p>${esc(partnerHub.copy)}</p><div class="partnerhub-actions"><a class="button primary" href="#partnerhub-flow">운영 흐름 보기 <span>↓</span></a><a class="button" href="#/manufacturing/catalog">플랫폼 구성 <span>→</span></a></div></div><dl class="partnerhub-facts"><div><dt>대상</dt><dd>${esc(partnerHub.target)}</dd></div><div><dt>권장 기반</dt><dd>${esc(partnerHub.platform)}</dd></div><div><dt>상품화</dt><dd>Commercial SKU · TBD</dd></div></dl></section><section class="partnerhub-capabilities" aria-label="PartnerHub 핵심 가치">${partnerHub.capabilities.map(([name,copy],index)=>`<article><span>0${index+1}</span><div><h4>${esc(name)}</h4><p>${esc(copy)}</p></div></article>`).join('')}</section><section id="partnerhub-flow" class="partnerhub-flow-section"><div class="partnerhub-section-head"><small>운영 흐름</small><h3>Lot 입고부터 품질 이력까지</h3><p>AI는 위험을 제안하고 최종 조치는 담당자가 결정합니다.</p></div><ol class="partnerhub-flow">${partnerHub.workflow.map(([step,name,copy])=>`<li><span>${esc(step)}</span><div><strong>${esc(name)}</strong><small>${esc(copy)}</small></div></li>`).join('')}</ol></section><section class="partnerhub-detail-grid"><article><div class="partnerhub-section-head"><small>서비스 구성</small><h3>3-Layer 아키텍처</h3></div><div class="partnerhub-layers">${partnerHub.layers.map(([number,name,copy])=>`<div><span>L${esc(number)}</span><p><strong>${esc(name)}</strong><small>${esc(copy)}</small></p></div>`).join('')}</div></article><article class="partnerhub-policy"><div><small>비즈니스 모델</small><h3>사용량과 도입 범위 기준</h3><p>${esc(partnerHub.commercial)}</p></div><div><small>책임 있는 AI</small><strong>AI는 제안하고, 담당자가 결정합니다.</strong><p>승인·결재 체인으로 품질 판단의 책임과 이력을 남깁니다.</p></div></article></section>`; }
  function render(path) { if(path==='/manufacturing/dashboard')return dashboard(); if(path==='/manufacturing/catalog')return catalog(); if(path==='/manufacturing/configurator')return configurator(); if(path==='/manufacturing/requests')return requests(); if(path==='/manufacturing/infrastructure')return infrastructure(); if(path==='/manufacturing/services')return services(); if(path==='/manufacturing/monitoring')return monitoring(); if(path==='/manufacturing/finops')return finops(); return '' ; }
  function readForm(form) { new FormData(form).forEach((value,key)=>{ if(key in state){ const current=state[key]; state[key]=typeof current==='number'?Number(value):value; }}); ['loadBalancer','redis','objectStorage','messageQueue','cicd','nightShutdown'].forEach(key=>{const input=form.elements[key]; if(input)state[key]=input.checked;}); }
  function requestPayload(note) { return {sku:state.sku,project:state.project,environment:state.environment,profile:'cloud-platform',configuration:{iaas:{compute_type:state.computeType,size:state.size,vcpu:state.vcpu,memory_gb:state.memory,instance_count:state.count,network_type:state.networkType,subnet:state.subnet,exposure:state.exposure,security_policy:state.security,load_balancer:state.loadBalancer,storage_type:state.storageType,storage_capacity_gb:state.storageCapacity},paas:{runtime:state.runtime,database:state.database,database_storage_gb:state.databaseStorage,redis:state.redis,object_storage:state.objectStorage,message_queue:state.messageQueue,monitoring:true,cicd:state.cicd},operation_policy:{night_shutdown:state.nightShutdown,backup:state.backup,ttl_days:state.ttl==='Custom'?Number(state.customTtl):Number(state.ttl),deployment:'AUTO'},request_note:note,cost_estimate_krw:estimate()}}; }
  async function submit(form) {
    const button=form.querySelector('[type="submit"]'); const message=form.querySelector('#wizard-message');
    button.disabled=true; button.textContent='Submitting…';
    try {
      const payload=requestPayload(new FormData(form).get('note'));
      const item=await window.EclipseDomainAPI.post('manufacturing','/manufacturing/requests',payload,()=>({id:`MFG-REQ-${String(300+store.requests.length).padStart(5,'0')}`,sku:state.sku,project:state.project,environment:state.environment,status:'REQUESTED',created:new Date().toISOString(),cost:estimate()}));
      store.requests.unshift({id:item.id,sku:item.sku||state.sku,project:item.project,environment:item.environment,status:item.status,created:String(item.created_at||item.created).slice(0,10),cost:item.configuration?.cost_estimate_krw||item.cost||estimate()});
      state.step=1; window.EclipseRouter.navigate('/manufacturing/requests');
    } catch (error) { message.textContent=error.message; button.disabled=false; button.textContent='Submit Request →'; }
  }
  function bind(root,path) { if(path==='/manufacturing/catalog'){root.querySelectorAll('[data-mfg-sku]').forEach(link=>link.addEventListener('click',()=>applySku(link.dataset.mfgSku)));return;} if(path==='/manufacturing/infrastructure'){root.querySelectorAll('[data-resource]').forEach(button=>button.addEventListener('click',()=>{selectedResource=button.dataset.resource;selectedResourceTab='Overview';window.EclipseApp.refresh();}));root.querySelectorAll('[data-resource-tab]').forEach(button=>button.addEventListener('click',()=>{selectedResourceTab=button.dataset.resourceTab;restoreResourceTabFocus=true;window.EclipseApp.refresh();}));const activeTab=root.querySelector('[data-resource-tab][aria-selected="true"]');if(activeTab){activeTab.scrollIntoView({block:'nearest',inline:'nearest'});if(restoreResourceTabFocus){activeTab.focus({preventScroll:true});restoreResourceTabFocus=false;}}const close=root.querySelector('[data-close-resource]');if(close)close.addEventListener('click',()=>{selectedResource=null;selectedResourceTab='Overview';restoreResourceTabFocus=false;window.EclipseApp.refresh();});return;} if(path!=='/manufacturing/configurator')return; const form=root.querySelector('#mfg-wizard'); if(!form)return; form.addEventListener('change',()=>{readForm(form); window.EclipseApp.refresh();}); form.addEventListener('input',event=>{if(['INPUT','SELECT'].includes(event.target.tagName)){readForm(form); if(event.target.name!=='project')window.EclipseApp.refresh();}}); const next=form.querySelector('[data-next]'); if(next)next.addEventListener('click',()=>{readForm(form); if(!form.checkValidity()){form.reportValidity();return;} state.step=Math.min(6,state.step+1); window.EclipseApp.refresh();}); const back=form.querySelector('[data-back]'); if(back)back.addEventListener('click',()=>{readForm(form);state.step=Math.max(1,state.step-1);window.EclipseApp.refresh();}); form.addEventListener('submit',event=>{event.preventDefault();readForm(form);if(form.checkValidity())submit(form);else form.reportValidity();}); }
  window.EclipseManufacturing={render,bind,store,state,skus,partnerHub,applySku,lifecycle,failureStates,resourceTabs};
}());
