apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - network-policy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: iaas-service-portal
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true
