$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L5-governance-intelligent-ops\S041-terraform-drift-detection-validation'
$p=@{Runbook=Join-Path $root 'runbooks\terraform-drift-detection-validation.md';Commands=Join-Path $root 'runbooks\terraform-drift-detection-commands.example.md';Criteria=Join-Path $root 'terraform\terraform-drift-detection-criteria.example.md';Decision=Join-Path $root 'terraform\terraform-drift-decision-matrix.example.md';Policy=Join-Path $root 'policy\terraform-drift-detection-policy.example.md';PlanNoDrift=Join-Path $root 'terraform\drift-detection-plan-no-drift.example.json';PlanDrift=Join-Path $root 'terraform\drift-detection-plan-drift.example.json';PlanCritical=Join-Path $root 'terraform\drift-detection-plan-critical-drift.example.json';NoDrift=Join-Path $e 'logs\terraform-plan-no-drift.sample.txt';Drift=Join-Path $e 'logs\terraform-plan-drift-detected.sample.txt';Critical=Join-Path $e 'logs\terraform-plan-critical-drift.sample.txt';Classification=Join-Path $e 'logs\terraform-drift-classification.sample.txt';Final=Join-Path $e 'logs\terraform-drift-final-summary.sample.txt';Manifest=Join-Path $e 'configs\terraform-drift-detection-manifest.sample.yml'}
$log=Join-Path $e 'logs\terraform-drift-detection-validation.log';$summary=Join-Path $e 'configs\terraform-drift-detection-validation-summary.md';New-Item -ItemType Directory -Force -Path (Split-Path $log),(Split-Path $summary)|Out-Null
$rs=[System.Collections.Generic.List[object]]::new();$ls=[System.Collections.Generic.List[string]]::new();$fail=0;$warn=0
function Add-R([string]$Id,[string]$Name,[string]$Result,[string]$Detail){if($Result-eq'FAIL'){$script:fail++};if($Result-eq'WARN'){$script:warn++};$x="[$Result] $Id ${Name}: $Detail";Write-Host $x;$script:ls.Add($x)|Out-Null;$script:rs.Add([pscustomobject]@{Id=$Id;Name=$Name;Result=$Result;Detail=$Detail})|Out-Null};function T([string]$x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 'Required artifacts' $(if($missing.Count-eq 0){'PASS'}else{'FAIL'}) 'Five baselines, three JSON examples, five log samples, and one manifest are required.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$commandTerms=@('terraform apply','terraform destroy','terraform import','terraform state rm','terraform state mv','terraform force-unlock');$commandSafe=$c.Commands-match'MANUAL LAB EXECUTION ONLY'-and$c.Commands-match'OUT OF SCOPE'-and@($commandTerms|Where-Object{$c.Commands-notmatch[regex]::Escape($_)}).Count-eq 0;Add-R V002 'Command safety boundary' $(if($commandSafe){'PASS'}else{'FAIL'}) 'Plan is manual-lab-only and mutation/state commands are out of scope.'
$noDrift=$c.NoDrift-match'Exit_Code:\s*0'-and$c.NoDrift-match'No changes\. Infrastructure matches the configuration\.'-and$c.NoDrift-match'NO_DRIFT';Add-R V003 'No-drift evidence' $(if($noDrift){'PASS'}else{'FAIL'}) 'Exit code 0 and NO_DRIFT are required.'
$drift=$c.Drift-match'Exit_Code:\s*2'-and$c.Drift-match'0 to add, 1 to change, 0 to destroy'-and$c.Drift-match'<terraform-resource-address-placeholder>'-and$c.Drift-match'DRIFT_DETECTED';Add-R V004 'Drift-detected evidence' $(if($drift){'PASS'}else{'FAIL'}) 'Exit code 2, a changed resource, and DRIFT_DETECTED are required.'
$critical=$c.Critical-match'Exit_Code:\s*2'-and$c.Critical-match'unsafe security rule drift placeholder'-and$c.Critical-match'<unrestricted-source-placeholder>'-and$c.Critical-match'Severity:\s*Critical'-and$c.Critical-match'CRITICAL_DRIFT';Add-R V005 'Critical drift evidence' $(if($critical){'PASS'}else{'FAIL'}) 'Security exposure, Critical severity, and CRITICAL_DRIFT are required.'
$class=$c.Classification-match'Drift_Type'-and$c.Classification-match'Affected_Resource'-and$c.Classification-match'Expected_Value'-and$c.Classification-match'Observed_Value'-and$c.Classification-match'Severity'-and$c.Classification-match'remediation_scenario:\s*S042';Add-R V006 'Drift classification and S042 mapping' $(if($class){'PASS'}else{'FAIL'}) 'Classification fields and S042 mapping are required.'
$final=$c.Final-match'Drift_Detection_Completed:\s*true'-and$c.Final-match'Drift_Evidence_Present:\s*true'-and$c.Final-match'Remediation_Executed:\s*false'-and$c.Final-match'S042'-and$c.Final-match'S043'-and$c.Final-match'Real_Cloud_Operation_Performed:\s*false';Add-R V007 'Final non-remediation summary' $(if($final){'PASS'}else{'FAIL'}) 'Detection completion, S042/S043 mapping, and no execution are required.'
$mf=@('drift_detection_id','terraform_environment','cloud_provider','drift_status','drift_severity','affected_resource','expected_value','observed_value','plan_exit_code','plan_artifact_reference','remediation_scenario: S042','policy_validation_scenario: S043','evidence_reference','final_judgment');$manifest=@($mf|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq 0;Add-R V008 'Drift manifest' $(if($manifest){'PASS'}else{'FAIL'}) 'All manifest fields and S042/S043 links are required.'
$jsonOk=$true;try{$j1=$c.PlanNoDrift|ConvertFrom-Json;$j2=$c.PlanDrift|ConvertFrom-Json;$j3=$c.PlanCritical|ConvertFrom-Json;$jsonOk=$j1.drift_judgment-eq'NO_DRIFT'-and$j2.drift_judgment-eq'DRIFT_DETECTED'-and$j3.drift_judgment-eq'CRITICAL_DRIFT'}catch{$jsonOk=$false};Add-R V009 'Sanitized plan JSON examples' $(if($jsonOk){'PASS'}else{'FAIL'}) 'Three parseable JSON examples with matching judgments are required.'
$riskyFiles=@(Get-ChildItem $root -Recurse -Force -ErrorAction SilentlyContinue|Where-Object{($_.FullName-notlike"$root\.git*")-and(($_.PSIsContainer-and$_.Name-eq'.terraform')-or(-not$_.PSIsContainer-and($_.Name-match'^(?:terraform\.tfstate(?:\.backup)?|terraform\.tfvars|.+\.auto\.tfvars)$'-or$_.Extension-match'^\.(?:tfplan|plan)$')))});Add-R V010 'Terraform state and artifact safety' $(if($riskyFiles.Count-eq 0){'PASS'}else{'FAIL'}) 'No tfstate, tfvars, plan binary, or .terraform directory may exist.'
$ip=$all-match'(?<![\w<])(?:\d{1,3}\.){3}\d{1,3}(?:/\d{1,2})?(?![\w>])';$id=$all-match'(?i)\b(?:vpc|sg|subnet|vnet)-[0-9a-f]{6,}\b'-or$all-match'\b\d{12}\b'-or$all-match'\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b';$secret=$all-match'(?im)^\s*(?:password|token|secret|access_key|secret_key|client_secret|authorization)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$safe=-not$ip-and-not$id-and-not$secret;Add-R V011 'Identifier network and secret safety' $(if($safe){'PASS'}else{'FAIL'}) 'No real IDs, IP/CIDR, credential, token, key, backend value, or secret may exist.'
$policy=@('evidence-based','must not contain credentials','state files','plan binaries','S042','S043','Public exposure drift');$policyOk=@($policy|Where-Object{$c.Policy-notmatch[regex]::Escape($_)}).Count-eq 0;Add-R V012 'Drift policy requirements' $(if($policyOk){'PASS'}else{'FAIL'}) 'Evidence, artifact, escalation, and scenario boundaries are required.'
$remediationSafe=$c.Final-match'Remediation_Executed:\s*false'-and$c.Final-notmatch'(?im)^Remediation_Executed:\s*true';Add-R V013 'No remediation execution' $(if($remediationSafe){'PASS'}else{'FAIL'}) 'S041 evidence must not claim remediation execution.'
$script=Get-Content $PSCommandPath -Raw;$exec=$script-match'(?im)^\s*(?:terraform|aws|az|openstack)\s+';Add-R V014 'Validator execution safety' $(if(-not$exec){'PASS'}else{'FAIL'}) 'Validator must not execute Terraform or cloud CLIs.'
$placeholder=$c.Classification-match'<drift-severity-placeholder>'-or$c.Manifest-match'<plan-exit-code-placeholder>';Add-R V015 'Evidence maturity' $(if($placeholder){'WARN'}else{'PASS'}) 'Placeholder-only severity/exit values are acceptable for static evidence but require future lab proof.'
$ts=(Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK');$overall=if($fail-eq 0){'PASS'}else{'FAIL'};$finalLine="[$overall] Terraform drift detection (StaticEvidence): $fail critical failure(s), $warn warning(s).";Write-Host $finalLine;@('SNSD Multi-Cloud Ops - S041 Terraform Drift Detection Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+@($ls)+@('',$finalLine,'No Terraform, cloud API, remote state, provider credential, or remediation operation occurred.')|Set-Content $log -Encoding UTF8
$out=@('# Terraform Drift Detection Validation Summary','', '- Scenario: S041-terraform-drift-detection-validation',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required file check result: **$(if($missing.Count-eq 0){'PASS'}else{'FAIL'})**","- Command safety result: **$(if($commandSafe){'PASS'}else{'FAIL'})**","- No-drift evidence result: **$(if($noDrift){'PASS'}else{'FAIL'})**","- Drift-detected evidence result: **$(if($drift){'PASS'}else{'FAIL'})**","- Critical-drift evidence result: **$(if($critical){'PASS'}else{'FAIL'})**","- Drift classification result: **$(if($class){'PASS'}else{'FAIL'})**","- Manifest result: **$(if($manifest){'PASS'}else{'FAIL'})**","- S042 remediation mapping result: **$(if($class-and$final){'PASS'}else{'FAIL'})**","- S043 policy mapping result: **$(if($final-and$manifest){'PASS'}else{'FAIL'})**","- Terraform state safety result: **$(if($riskyFiles.Count-eq 0){'PASS'}else{'FAIL'})**","- Secret-safety check result: **$(if($safe){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result | Detail |','|---|---|---|---|');foreach($r in $rs){$out+="| $($r.Id) | $($r.Name) | $($r.Result) | $($r.Detail) |"};$out|Set-Content $summary -Encoding UTF8;if($fail-gt 0){exit 1};exit 0
