$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot; $e=Join-Path $root 'evidence/L5-governance-intelligent-ops/S048-ml-anomaly-detection-validation'
$p=@{Runbook="$root/runbooks/ml-anomaly-detection-validation.md";Commands="$root/runbooks/ml-anomaly-detection-commands.example.md";Profile="$root/ml-security/models/ml-anomaly-threshold-profile.example.yml";Criteria="$root/ml-security/models/ml-anomaly-detection-criteria.example.md";Decision="$root/ml-security/models/ml-anomaly-detection-decision-matrix.example.md";Policy="$root/policy/ml-anomaly-detection-policy.example.md";Input="$root/ml-security/datasets/ml-anomaly-detection-input.sample.csv";Output="$root/ml-security/datasets/ml-anomaly-detection-output.sample.csv";Invalid="$root/ml-security/datasets/ml-anomaly-detection-invalid-output.sample.csv";Metadata="$root/ml-security/datasets/ml-anomaly-detection-run-metadata.sample.yml";Script="$root/ml-security/scripts/metric-anomaly-detection.example.py";ProfileLog="$e/logs/ml-anomaly-threshold-profile-load.sample.txt";InputLog="$e/logs/ml-anomaly-input-validation.sample.txt";RunLog="$e/logs/ml-anomaly-detection-run.sample.txt";PassLog="$e/logs/ml-anomaly-output-validation-pass.sample.txt";FailLog="$e/logs/ml-anomaly-output-validation-fail.sample.txt";ClassLog="$e/logs/ml-anomaly-classification.sample.txt";Privacy="$e/logs/ml-anomaly-privacy-safety.sample.txt";Final="$e/logs/ml-anomaly-detection-final-summary.sample.txt";Manifest="$e/configs/ml-anomaly-detection-validation-manifest.sample.yml"}
$log="$e/logs/ml-anomaly-detection-validation.log";$summary="$e/configs/ml-anomaly-detection-validation-summary.md";$res=@();$fails=0;$warns=0
function Add-R($id,$name,$ok,$detail,$warning=$false){$s=if($ok){'PASS'}elseif($warning){'WARN'}else{'FAIL'};if($s-eq'FAIL'){$script:fails++};if($s-eq'WARN'){$script:warns++};Write-Host "[$s] $id ${name}: $detail";$script:res+=[pscustomobject]@{Id=$id;Name=$name;Status=$s}}
function T($x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 Artifacts ($missing.Count-eq0) 'Required S048 artifacts exist.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$cmd=$c.Commands-match'OPTIONAL MANUAL LOCAL SAMPLE ONLY'-and$c.Commands-match'does not query Prometheus'-and$c.Commands-match'does not query.*Grafana'-and$c.Commands-match'does not train or deploy'-and$c.Commands-match'no automated blocking';Add-R V002 Commands $cmd 'No-query, no-training/deployment, and no-blocking boundaries exist.'
$profileVals=@('static_threshold_profile','S047','S048','S049','S050','z_score_placeholder','static_threshold_placeholder','rolling_baseline_placeholder','NORMAL','WARNING','ANOMALY_DETECTED','REVIEW_REQUIRED','EVIDENCE_INCOMPLETE','not a trained model binary');$profile=@($profileVals|Where-Object{$c.Profile-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V003 Profile $profile 'Static threshold profile and decision values are complete.'
$inCols=@('dataset_id','metric_timestamp','metric_source','metric_name','metric_value','metric_unit','scrape_job','instance_placeholder','service_placeholder','feature_group','feature_name','normalized_value','anomaly_label_placeholder','evidence_reference');$outCols=@('detection_run_id','dataset_id','metric_timestamp','feature_group','feature_name','metric_name','metric_value','normalized_value','baseline_value_placeholder','anomaly_score','threshold_reference','anomaly_decision','review_required','related_scenario','evidence_reference');$in=@(Import-Csv $p.Input);$out=@(Import-Csv $p.Output);$inHead=@($in[0].PSObject.Properties.Name);$outHead=@($out[0].PSObject.Properties.Name);$n=0.0;$inOk=@($inCols|Where-Object{$_-notin$inHead}).Count-eq0-and$in.Count-ge20-and@($in|Where-Object{-not[double]::TryParse([string]$_.metric_value,[ref]$n)-or-not[double]::TryParse([string]$_.normalized_value,[ref]$n)}).Count-eq0;Add-R V004 Input $inOk 'Input has required columns, 20 rows, and numeric values.'
$allowed=@('NORMAL','WARNING','ANOMALY_DETECTED','REVIEW_REQUIRED','EVIDENCE_INCOMPLETE');$outOk=@($outCols|Where-Object{$_-notin$outHead}).Count-eq0-and$out.Count-ge20-and@($out|Where-Object{-not[double]::TryParse([string]$_.anomaly_score,[ref]$n)-or$_.anomaly_decision-notin$allowed}).Count-eq0-and@($out|Where-Object{$_.anomaly_decision-eq'ANOMALY_DETECTED'}).Count-gt0-and@($out|Where-Object{$_.anomaly_decision-eq'NORMAL'}).Count-gt0-and@($out|Where-Object{$_.anomaly_decision-in@('WARNING','REVIEW_REQUIRED')}).Count-gt0;Add-R V005 Output $outOk 'Output has required columns, numeric scores, valid decisions, and representative outcomes.'
$invalid=$c.Invalid-match'INTENTIONALLY INVALID'-and$c.Invalid-match'not_numeric'-and$c.Invalid-match'INVALID_DECISION';Add-R V006 Invalid $invalid 'Invalid output is clearly marked and malformed.'
$map=@('dataset_source_scenario: S047','report_generation_scenario: S049','final_evidence_report_scenario: S050');$metadata=@($map|Where-Object{$c.Metadata-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V007 Metadata $metadata 'Run metadata maps S047/S049/S050.'
$evidence=$c.ProfileLog-match'static_threshold_profile'-and$c.InputLog-match'S047'-and$c.RunLog-match'Live_Prometheus_Query_Performed:\s*false'-and$c.RunLog-match'ML_Model_Training_Performed:\s*false'-and$c.PassLog-match'ANOMALY_DETECTED'-and$c.FailLog-match'ANOMALY_VALIDATION_FAILED'-and$c.ClassLog-match'S049';Add-R V008 Evidence $evidence 'Profile, input, run, pass/fail, and classification evidence is consistent.'
$privacy=@('No_Raw_Logs: true','No_Packet_Payload: true','No_SIEM_Logs: true','No_Wazuh_Logs: true','No_EDR_Telemetry: true','No_Credentials: true','No_Real_IPs: true','No_Real_Hostnames: true','No_Production_Identifiers: true');$privacyOk=@($privacy|Where-Object{$c.Privacy-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V009 Privacy $privacyOk 'Privacy and telemetry exclusions are confirmed.'
$final=$c.Final-match'ANOMALY_DETECTED'-and$c.Final-match'Live_Prometheus_Query_Performed:\s*false'-and$c.Final-match'ML_Model_Trained:\s*false'-and$c.Final-match'Model_Deployed:\s*false'-and$c.Final-match'Automated_Blocking_Performed:\s*false'-and$c.Final-match'S049';Add-R V010 Final $final 'Final summary confirms anomaly sample and no live/training/deployment/blocking action.'
$mf=@('ml_anomaly_detection_validation_id','detection_run_id','dataset_source_scenario: S047','dataset_id','input_dataset_reference','output_dataset_reference','invalid_output_reference','threshold_profile_reference','detection_method','scoring_method','detected_anomaly_count','warning_count','review_required_count','privacy_safety_result','report_generation_scenario: S049','final_evidence_report_scenario: S050','evidence_reference','final_judgment');$manifest=@($mf|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V011 Manifest $manifest 'Manifest fields and S047/S049/S050 mappings exist.'
$policyTerms=@('metric-only S047','SIEM','Wazuh','EDR','raw logs','packet','malware detection','threat hunting','LLM-based analysis','automated blocking','human review','S049','S050');$policy=@($policyTerms|Where-Object{$c.Policy-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V012 Policy $policy 'Policy scope and human review boundaries exist.'
$bins=@(Get-ChildItem $root -Recurse -File -Force -ErrorAction SilentlyContinue|Where-Object{$_.FullName-notlike"$root/.git*"-and$_.Extension-match'(?i)^\.(pkl|pickle|joblib|onnx|pt|pth|h5|pb|pcap|pcapng)$'});Add-R V013 BinarySafety ($bins.Count-eq0) 'No trained model or packet-capture binary exists.'
$ip=$all-match'(?<![\w<])(?:\d{1,3}\.){3}\d{1,3}(?![\w>])';$url=$all-match'(?i)https?://(?!<)[a-z0-9]';$secret=$all-match'(?im)^\s*(?:password|token|secret|access_key|api_key|authorization)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$src=Get-Content $PSCommandPath -Raw;$exec=$src-match'(?im)^\s*(?:curl|python|promtool|kubectl|aws|az|openstack)\s+';Add-R V014 Safety (-not$ip-and-not$url-and-not$secret-and-not$exec) 'No real endpoint, secret, or external execution detected.'
$scriptOk=$c.Script-match'SAMPLE / NON-PRODUCTION'-and$c.Script-notmatch'(?i)sklearn|tensorflow|torch|requests|urllib|socket'-and$c.Script-match'ANOMALY_DETECTED';Add-R V015 SampleScript $scriptOk 'Optional script is deterministic standard-library logic.'
Add-R V016 Maturity $false 'Thresholds and anomaly decisions are synthetic sample evidence.' $true
$ts=(Get-Date).ToString('s');$overall=if($fails){'FAIL'}else{'PASS'};$end="[$overall] ML anomaly detection (StaticEvidence): $fails critical failure(s), $warns warning(s).";Write-Host $end;@('S048 ML Anomaly Detection Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+($res|ForEach-Object{"[$($_.Status)] $($_.Id) $($_.Name)"})+@('',$end,'No live query, training, deployment, or blocking occurred.')|Set-Content $log -Encoding UTF8
@('# ML Anomaly Detection Validation Summary','',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required files: **$(if($missing.Count-eq0){'PASS'}else{'FAIL'})**","- Command safety: **$(if($cmd){'PASS'}else{'FAIL'})**","- Threshold profile: **$(if($profile){'PASS'}else{'FAIL'})**","- Input dataset: **$(if($inOk){'PASS'}else{'FAIL'})**","- Detection output: **$(if($outOk){'PASS'}else{'FAIL'})**","- Invalid output: **$(if($invalid){'PASS'}else{'FAIL'})**","- Run metadata: **$(if($metadata){'PASS'}else{'FAIL'})**","- Classification/privacy: **$(if($evidence-and$privacyOk){'PASS'}else{'FAIL'})**","- S047/S049/S050 mappings: **$(if($metadata-and$manifest){'PASS'}else{'FAIL'})**","- Model binary/secret safety: **$(if($bins.Count-eq0-and-not$ip-and-not$url-and-not$secret){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**")|Set-Content $summary -Encoding UTF8;if($fails){exit 1}
