$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L4-failure-recovery\S039-restore-execution-validation'
$p=@{Runbook=Join-Path $root 'runbooks\restore-execution-validation.md';Commands=Join-Path $root 'runbooks\restore-execution-commands.example.md';Criteria=Join-Path $root 'runbooks\restore-execution-criteria.example.md';Policy=Join-Path $root 'policy\restore-validation-policy.example.md';Ansible=Join-Path $root 'ansible\playbooks\restore-execution-check.example.yml';Precheck=Join-Path $e 'logs\restore-precheck.sample.txt';Checksum=Join-Path $e 'logs\restore-checksum-verification.sample.txt';Command=Join-Path $e 'logs\restore-command-output.sample.txt';Metadata=Join-Path $e 'logs\restore-artifact-metadata.sample.txt';Consistency=Join-Path $e 'logs\restore-consistency-check.sample.txt';Completion=Join-Path $e 'logs\restore-completion-summary.sample.txt';Manifest=Join-Path $e 'configs\restore-execution-manifest.sample.yml'}
$log=Join-Path $e 'logs\restore-execution-validation.log';$summary=Join-Path $e 'configs\restore-execution-validation-summary.md';New-Item -ItemType Directory -Force -Path (Split-Path $log),(Split-Path $summary)|Out-Null
$rs=[System.Collections.Generic.List[object]]::new();$ls=[System.Collections.Generic.List[string]]::new();$fail=0;$warn=0
function Add-R([string]$Id,[string]$Name,[string]$Result,[string]$Detail){if($Result-eq'FAIL'){$script:fail++};if($Result-eq'WARN'){$script:warn++};$x="[$Result] $Id ${Name}: $Detail";Write-Host $x;$script:ls.Add($x)|Out-Null;$script:rs.Add([pscustomobject]@{Id=$Id;Name=$Name;Result=$Result;Detail=$Detail})|Out-Null};function T([string]$x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 'Required artifacts' $(if($missing.Count-eq 0){'PASS'}else{'FAIL'}) 'Five baselines and seven samples are required.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$terms=@('<backup-manifest-placeholder>','<backup-id-placeholder>','<backup-file-placeholder>','<restore-target-placeholder>','<restore-source-placeholder>','<restore-method-placeholder>','<restore-job-id-placeholder>','<evidence-path>','S038','S040');Add-R V002 'Runbook workflow and placeholders' $(if(@($terms|Where-Object{$c.Runbook-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'Backup linkage, target, restore, rollback, and health mapping are required.'
$phases=@('Backup manifest reference','Backup checksum verification','Restore target preparation','Restore command execution evidence placeholder','Restore log review','Restore artifact metadata','Restore consistency check','Restore completion summary','Restore abort / rollback condition','Mapping to service health validation');Add-R V003 'Criteria matrix' $(if(@($phases|Where-Object{$c.Criteria-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'All ten phases are required.'
$policyFields=@('backup manifest','checksum','disposable','job ID','backup ID','source','target','duration','consistency','rollback','S040');Add-R V004 'Restore policy requirements' $(if(@($policyFields|Where-Object{$c.Policy-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'Manifest, integrity, disposable target, metadata, rollback, and health linkage are required.'
$debug=$c.Ansible-match'hosts:\s*restore_target_placeholder'-and$c.Ansible-match'ansible\.builtin\.debug'-and$c.Ansible-notmatch'(?im)^\s*(?:shell|command|unarchive|synchronize|copy|fetch):';Add-R V005 'Ansible placeholder safety' $(if($debug){'PASS'}else{'FAIL'}) 'Debug-only non-production example is required.'
$precheck=$c.Precheck-match'<backup-manifest-placeholder>'-and$c.Precheck-match'<restore-target-placeholder>'-and$c.Precheck-match'Disposable_Lab_Target:\s*true'-and$c.Precheck-match'Production_Target:\s*false';Add-R V006 'Restore precheck evidence' $(if($precheck){'PASS'}else{'FAIL'}) 'Manifest, prepared disposable target, and no-production-target evidence are required.'
$checksum=$c.Checksum-match'Checksum_Algorithm:\s*SHA256'-and$c.Checksum-match'<backup-file-placeholder>'-and$c.Checksum-match'Checksum_Verified:\s*true-placeholder'-and$c.Checksum-match'Checksum_Match:\s*true-placeholder'-and$c.Checksum-match'Production_Hash_Stored:\s*false';Add-R V007 'Checksum verification evidence' $(if($checksum){'PASS'}else{'FAIL'}) 'SHA256 verified/match placeholders and no-production-hash marker are required.'
$command=$c.Command-match'MANUAL LAB RESTORE SAMPLE'-and$c.Command-match'completed-placeholder'-and$c.Command-match'<restore-job-id-placeholder>'-and$c.Command-match'Execution_By_Validator:\s*false';Add-R V008 'Manual restore command evidence' $(if($command){'PASS'}else{'FAIL'}) 'Manual lab completion must be explicit and not validator-executed.'
$size=[regex]::Match($c.Metadata,'(?im)^Restored_Size_Bytes:\s*(\d+)\s*$');$metadata=$c.Metadata-match'<restored-artifact-placeholder>'-and$c.Metadata-match'<restored-at-placeholder>'-and$c.Metadata-match'<restore-target-placeholder>'-and$size.Success-and[int64]$size.Groups[1].Value-gt 0;Add-R V009 'Restore artifact metadata' $(if($metadata){'PASS'}else{'FAIL'}) 'Artifact, time, positive size, and target are required.'
$consistency=$c.Consistency-match'Consistency_Check:\s*passed-placeholder'-and$c.Consistency-match'<count-placeholder>'-and$c.Consistency-match'Real_Rows_Or_Data_Stored:\s*false';Add-R V010 'Restore consistency evidence' $(if($consistency){'PASS'}else{'FAIL'}) 'Passed consistency, symbolic count, and no-real-data marker are required.'
$manifestFields=@('restore_job_id','backup_id','backup_manifest','backup_file','restore_source','restore_target','restore_method','checksum_algorithm','checksum_verified','restore_started_at','restore_completed_at','restore_duration_seconds','consistency_check','rollback_required','rollback_condition','service_health_validation_scenario: S040','evidence_reference');$manifest=@($manifestFields|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq 0;Add-R V011 'Restore manifest fields' $(if($manifest){'PASS'}else{'FAIL'}) 'All required restore manifest fields are required.'
$completion=$c.Completion-match'Restore_Completed:\s*true'-and$c.Completion-match'Checksum_Verified:\s*true'-and$c.Completion-match'Consistency_Check_Passed:\s*true'-and$c.Completion-match'Restore_Target_Validated:\s*true'-and$c.Completion-match'Final_Health_Validation:\s*S040'-and$c.Completion-match'Real_Restore_Artifact_Committed:\s*false';Add-R V012 'Restore completion summary' $(if($completion){'PASS'}else{'FAIL'}) 'Completion, integrity, consistency, target, S040, and no-real-artifact judgments are required.'
$risky=@(Get-ChildItem $e -Recurse -File -Force|Where-Object{$_.Name-notmatch'\.sample\.'-and$_.Name-match'(?i)\.(?:bak|backup|dump|sql|gz|tgz|tar|zip|7z|db|sqlite)$'});$pathHit=$all-match'(?im)(?:[A-Z]:\\|/(?:home|var|opt|srv|mnt|data)/|s3://|az://|swift://|gs://)';$secret=$all-match'(?im)^\s*(?:password|token|secret|access_key|connection_string)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$safe=$risky.Count-eq 0-and-not$pathHit-and-not$secret;Add-R V013 'Restore artifact path and secret safety' $(if($safe){'PASS'}else{'FAIL'}) 'No artifact, dump/archive, path/storage URI, credential, connection string, key, or secret may exist.'
$script=Get-Content $PSCommandPath -Raw;$unsafe=$script-match'(?im)^\s*(?:mysql|mariadb|psql|tar|unzip|Expand-Archive|restic|borg|aws|az|openstack|rclone|ansible-playbook)\b';Add-R V014 'Execution safety boundary' $(if(-not$unsafe){'PASS'}else{'FAIL'}) 'Validator must not restore/import/extract/download/query storage or execute Ansible.'
$commandsOut=$c.Commands-match'OUT OF SCOPE'-and$c.Commands-match'never executed';Add-R V015 'Command reference boundary' $(if($commandsOut){'PASS'}else{'FAIL'}) 'Operational restore commands must be sample-only and out of scope.'
$ts=(Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK');$overall=if($fail-eq 0){'PASS'}else{'FAIL'};$final="[$overall] Restore execution (StaticEvidence): $fail critical failure(s), $warn warning(s).";Write-Host $final;@('SNSD Multi-Cloud Ops - S039 Restore Execution Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+@($ls)+@('', $final,'No restore, SQL import, archive extraction, backup download, storage query, Ansible run, credential read, or production-data access occurred.')|Set-Content $log -Encoding UTF8
$out=@('# Restore Execution Validation Summary','', '- Scenario: S039-restore-execution-validation',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required file check result: **$(if($missing.Count-eq 0){'PASS'}else{'FAIL'})**","- Precheck result: **$(if($precheck){'PASS'}else{'FAIL'})**","- Checksum verification result: **$(if($checksum){'PASS'}else{'FAIL'})**","- Manual restore evidence result: **$(if($command){'PASS'}else{'FAIL'})**","- Metadata result: **$(if($metadata){'PASS'}else{'FAIL'})**","- Consistency result: **$(if($consistency){'PASS'}else{'FAIL'})**","- Manifest result: **$(if($manifest){'PASS'}else{'FAIL'})**","- Completion result: **$(if($completion){'PASS'}else{'FAIL'})**","- Artifact / secret safety result: **$(if($safe){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result | Detail |','|---|---|---|---|');foreach($r in $rs){$out+="| $($r.Id) | $($r.Name) | $($r.Result) | $($r.Detail) |"};$out|Set-Content $summary -Encoding UTF8;if($fail-gt 0){exit 1};exit 0
