param([switch]$LiveHttp,[switch]$LiveKubectl,[switch]$LivePrometheus,[string]$WebHealthUrl,[string]$ApiHealthUrl,[string]$LoadBalancerHealthUrl,[string]$Namespace,[string]$DeploymentName,[string]$ServiceName,[string]$PrometheusUrl,[string]$ExpectedJob,[string]$ExpectedInstance)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L4-failure-recovery\S040-service-health-after-recovery-validation'
$p=@{Runbook=Join-Path $root 'runbooks\service-health-after-recovery-validation.md';Commands=Join-Path $root 'runbooks\service-health-after-recovery-commands.example.md';Criteria=Join-Path $root 'runbooks\service-health-after-recovery-criteria.example.md';Decision=Join-Path $root 'runbooks\service-health-after-recovery-decision-matrix.example.md';Metrics=Join-Path $root 'observability\prometheus\service-health-after-recovery-metrics.example.md';Web=Join-Path $e 'logs\post-recovery-web-health.sample.txt';Api=Join-Path $e 'logs\post-recovery-api-health.sample.txt';Lb=Join-Path $e 'logs\post-recovery-lb-health.sample.txt';Workloads=Join-Path $e 'logs\post-recovery-kubernetes-workloads.sample.txt';Endpoints=Join-Path $e 'logs\post-recovery-kubernetes-endpoints.sample.txt';Db=Join-Path $e 'logs\post-recovery-db-health.sample.txt';Replication=Join-Path $e 'logs\post-recovery-replication-health.sample.txt';Prometheus=Join-Path $e 'logs\post-recovery-prometheus-targets.sample.json';Blackbox=Join-Path $e 'logs\post-recovery-blackbox-probe.sample.json';Alerts=Join-Path $e 'logs\post-recovery-alerts-cleared.sample.json';BackupRestore=Join-Path $e 'logs\backup-restore-reference.sample.txt';Final=Join-Path $e 'logs\final-service-health-summary.sample.txt';Manifest=Join-Path $e 'configs\service-health-after-recovery-manifest.sample.yml'}
$log=Join-Path $e 'logs\service-health-after-recovery-validation.log';$summary=Join-Path $e 'configs\service-health-after-recovery-validation-summary.md';New-Item -ItemType Directory -Force -Path (Split-Path $log),(Split-Path $summary)|Out-Null
$rs=[System.Collections.Generic.List[object]]::new();$ls=[System.Collections.Generic.List[string]]::new();$fail=0;$warn=0
function Add-R([string]$Id,[string]$Name,[string]$Result,[string]$Detail){if($Result-eq'FAIL'){$script:fail++};if($Result-eq'WARN'){$script:warn++};$x="[$Result] $Id ${Name}: $Detail";Write-Host $x;$script:ls.Add($x)|Out-Null;$script:rs.Add([pscustomobject]@{Id=$Id;Name=$Name;Result=$Result;Detail=$Detail})|Out-Null};function T([string]$x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 'Required artifacts' $(if($missing.Count-eq 0){'PASS'}else{'FAIL'}) 'Five baselines and thirteen samples are required.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$domains=@('Web service health','API service health','Load balancer health','Kubernetes deployment rollout','Kubernetes pod readiness','Kubernetes service endpoints','DB primary availability','DB replica availability','Replication lag','Prometheus target health','Blackbox endpoint probe','Alert cleared state','Backup creation reference','Restore execution reference','Final recovery summary');Add-R V002 'Final health criteria matrix' $(if(@($domains|Where-Object{$c.Criteria-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'All fifteen health domains are required.'
$judgments=@('RECOVERED','DEGRADED','FAILED','INCOMPLETE','REVIEW_REQUIRED');Add-R V003 'Final recovery decision model' $(if(@($judgments|Where-Object{$c.Decision-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'All five final judgment states are required.'
$metricTerms=@('up{job="<scrape-job-name-placeholder>"}','probe_success{instance="<blackbox-target-placeholder>"}','probe_http_status_code{instance="<blackbox-target-placeholder>"}','kube_deployment_status_replicas_available','kube_pod_status_ready','nginx_up','nginx_http_response_5xx_total');Add-R V004 'Post-recovery metric placeholders' $(if(@($metricTerms|Where-Object{$c.Metrics-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'Required symbolic metric families are required.'
$http=$c.Web-match'HTTP/1\.1 200 OK'-and$c.Api-match'HTTP/1\.1 200 OK'-and$c.Lb-match'HTTP/1\.1 200 OK';Add-R V005 'Web API and LB health' $(if($http){'PASS'}else{'FAIL'}) 'All three user-facing health samples must be 200.'
$workload=$c.Workloads-match'successfully rolled out'-and$c.Workloads-match'\s1/1\s'-and$c.Workloads-match'\sRunning\s';Add-R V006 'Kubernetes workload health' $(if($workload){'PASS'}else{'FAIL'}) 'Successful rollout and Running/Ready Pod are required.';$endpoint=$c.Endpoints-match'<pod-ip-placeholder>:<service-port-placeholder>'-and$c.Endpoints-notmatch'(?i)<none>';Add-R V007 'Kubernetes endpoint health' $(if($endpoint){'PASS'}else{'FAIL'}) 'A symbolic non-empty endpoint is required.'
$db=$c.Db-match'Primary:\s*available-placeholder'-and$c.Db-match'Replica:\s*available-placeholder'-and$c.Db-match'Real_DB_Connection_Output_Stored:\s*false';Add-R V008 'Database availability evidence' $(if($db){'PASS'}else{'FAIL'}) 'Primary/Replica availability and no-real-output marker are required.';$repl=$c.Replication-match'Replica_IO_Running:\s*Yes'-and$c.Replication-match'Replica_SQL_Running:\s*Yes'-and$c.Replication-match'Seconds_Behind_Master:\s*0';Add-R V009 'Replication health evidence' $(if($repl){'PASS'}else{'FAIL'}) 'Both threads and zero lag are required.'
$prom=$c.Prometheus-match'"health":"up"'-and$c.Prometheus-match'"up":"1"';Add-R V010 'Prometheus health evidence' $(if($prom){'PASS'}else{'FAIL'}) 'Target up and up=1 are required.';$probe=$c.Blackbox-match'"probe_success":"1"'-and$c.Blackbox-match'"probe_http_status_code":"(?:200|204)"'-and$c.Blackbox-match'probe_duration_seconds';Add-R V011 'Blackbox health evidence' $(if($probe){'PASS'}else{'FAIL'}) 'probe_success=1, healthy status, and duration are required.';$alerts=$c.Alerts-match'(?i)"state":"(?:inactive|resolved[^" ]*|cleared[^" ]*)"'-and$c.Alerts-match'"firing":false';Add-R V012 'Alerts-cleared evidence' $(if($alerts){'PASS'}else{'FAIL'}) 'Resolved/inactive/cleared and not-firing evidence is required.'
$reference=$c.BackupRestore-match'Backup_Creation_Scenario:\s*S038'-and$c.BackupRestore-match'Restore_Execution_Scenario:\s*S039'-and$c.BackupRestore-match'<backup-id-placeholder>'-and$c.BackupRestore-match'<restore-job-id-placeholder>'-and$c.BackupRestore-match'Checksum_Verified:\s*true-placeholder'-and$c.BackupRestore-match'Consistency_Check:\s*passed-placeholder';Add-R V013 'Backup restore reference evidence' $(if($reference){'PASS'}else{'FAIL'}) 'S038/S039 IDs, checksum, and consistency are required.'
$summaryFields=@('web: PASS','api: PASS','load_balancer: PASS','kubernetes: PASS','database: PASS','replication: PASS','prometheus: PASS','blackbox: PASS','backup_restore_reference: PASS','final_judgment: RECOVERED');$final=@($summaryFields|Where-Object{$c.Final-notmatch[regex]::Escape($_)}).Count-eq 0;Add-R V014 'Final RECOVERED summary' $(if($final){'PASS'}else{'FAIL'}) 'All domains PASS and final_judgment RECOVERED are required.'
$manifestFields=@('recovery_validation_id','related_failure_scenarios','backup_creation_scenario: S038','restore_execution_scenario: S039','backup_id','restore_job_id','web_health','api_health','load_balancer_health','kubernetes_health','database_health','replication_health','prometheus_health','blackbox_health','alert_state','final_judgment','evidence_reference');$manifest=@($manifestFields|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq 0;Add-R V015 'Recovery manifest fields' $(if($manifest){'PASS'}else{'FAIL'}) 'All required manifest fields are required.'
$bad='(?i)CrashLoopBackOff|ImagePullBackOff|ErrImagePull|\bFailed\b|\bPending\b|\bUnknown\b|\b0/1\b|HTTP/1\.1 5\d\d|timeout|connection refused|unavailable-placeholder|<none>|Running:\s*No|Seconds_Behind_Master:\s*NULL|"health":"down"|"up":"0"|"probe_success":"0"|"firing":true';$criticalSafe=(@($c.Web,$c.Api,$c.Lb,$c.Workloads,$c.Endpoints,$c.Db,$c.Replication,$c.Prometheus,$c.Blackbox,$c.Alerts)-join"`n")-notmatch$bad;Add-R V016 'Critical recovered-state failure indicators' $(if($criticalSafe){'PASS'}else{'FAIL'}) 'No critical unhealthy signal may remain.'
$duration=[regex]::Match($c.Final,'(?im)^recovery_duration_seconds:\s*(\d+(?:\.\d+)?)\s*$');Add-R V017 'Recovery evidence maturity' $(if($duration.Success){'PASS'}else{'WARN'}) 'Evidence is placeholder-only and recovery duration is unmeasured; real operational proof remains future work.'
$ip=[regex]::Matches($all,'(?<![A-Za-z0-9<])(?:\d{1,3}\.){3}\d{1,3}(?![A-Za-z0-9>])').Count;$url=[regex]::Matches($all,'(?i)https?://(?!<)[^\s"`]+').Count;$domain=[regex]::Matches($all,'(?i)(?<![A-Za-z0-9<.-])(?:[a-z0-9-]+\.)+[a-z]{2,}(?![A-Za-z0-9>.-])').Count;$secret=$all-match'(?im)^\s*(?:password|token|secret|authorization|cookie|api[_-]?key|connection_string)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$forbiddenFiles=@(Get-ChildItem $root -Recurse -File -Force -ErrorAction SilentlyContinue|Where-Object{$_.FullName-notmatch'[\\/]\.git[\\/]'-and$_.Name-match'(?i)(^|\.)kubeconfig($|\.)|\.pem$|\.key$'});$safe=$ip-eq 0-and$url-eq 0-and$domain-eq 0-and-not$secret-and$forbiddenFiles.Count-eq 0;Add-R V018 'Endpoint credential and secret safety' $(if($safe){'PASS'}else{'FAIL'}) 'No real URL/domain/IP, DB credential, kubeconfig, token, cookie, key, connection string, or secret may exist.'
$script=Get-Content $PSCommandPath -Raw;$destructive=$script-match'(?im)^\s*(?:kubectl\s+(?:apply|delete|patch|edit|scale|rollout restart|cordon|drain|taint)|mysql|mariadb|psql|systemctl|service|terraform|ansible-playbook)\b';Add-R V019 'Execution safety boundary' $(if(-not$destructive){'PASS'}else{'FAIL'}) 'No recovery, database, backup, restore, resource, or configuration mutation is allowed.'
$mode=@();if($LiveHttp){$mode+='LiveHttp'};if($LiveKubectl){$mode+='LiveKubectl'};if($LivePrometheus){$mode+='LivePrometheus'};if($mode.Count-eq 0){$mode+='Static'};$modeName=$mode-join'+'
if($LiveHttp){$r='PASS';$detail='Status-only requests completed.';$urls=@($WebHealthUrl,$ApiHealthUrl,$LoadBalancerHealthUrl)|Where-Object{-not[string]::IsNullOrWhiteSpace($_)};if($urls.Count-eq 0){$r='FAIL';$detail='At least one health URL is required.'}else{foreach($u in $urls){try{$res=Invoke-WebRequest -Uri $u -Method Head -UseBasicParsing -TimeoutSec 10;$status=[int]$res.StatusCode;if($status-in 401,403){if($r-ne'FAIL'){$r='WARN'}}elseif($status-notin 200,204,301,302){$r='FAIL'}}catch{$r='FAIL'}}};Add-R V020 'LiveHttp read-only health' $r $detail}
if($LiveKubectl){$r='PASS';$detail='Read-only Kubernetes state summarized.';if([string]::IsNullOrWhiteSpace($Namespace)){$r='FAIL';$detail='Namespace is required.'}else{$k=Get-Command kubectl -CommandType Application -ErrorAction SilentlyContinue;if($null-eq$k){$r='FAIL'}else{$argsList=@(@('get','deployment','-n',$Namespace),@('get','pods','-n',$Namespace),@('get','service','-n',$Namespace),@('get','endpoints','-n',$Namespace));if($DeploymentName){$argsList+=,@('rollout','status',"deployment/$DeploymentName",'-n',$Namespace)};$outs=@();foreach($a in $argsList){$o=@(&$k.Source @a 2>&1);if($LASTEXITCODE-ne 0){$r='FAIL'};$outs+=,$o};if(($outs[1]-join"`n")-match'(?i)CrashLoopBackOff|ImagePullBackOff|ErrImagePull|\s0/\d+\s|\s(?:Failed|Pending|Unknown)\s'){$r='FAIL'};if(($outs[3]-join"`n")-match'(?i)<none>'){$r='FAIL'}}};Add-R V021 'LiveKubectl read-only health' $r $detail}
if($LivePrometheus){$r='PASS';$detail='Read-only Prometheus state summarized.';if([string]::IsNullOrWhiteSpace($PrometheusUrl)){$r='FAIL';$detail='PrometheusUrl is required.'}else{try{$up=Invoke-RestMethod -Uri "$PrometheusUrl/api/v1/query?query=up" -Method Get -TimeoutSec 10;$probeLive=Invoke-RestMethod -Uri "$PrometheusUrl/api/v1/query?query=probe_success" -Method Get -TimeoutSec 10;$targets=Invoke-RestMethod -Uri "$PrometheusUrl/api/v1/targets" -Method Get -TimeoutSec 10;$alertsLive=Invoke-RestMethod -Uri "$PrometheusUrl/api/v1/alerts" -Method Get -TimeoutSec 10;$selected=@($targets.data.activeTargets);if($ExpectedJob){$selected=@($selected|Where-Object{$_.labels.job-eq$ExpectedJob})};if($ExpectedInstance){$selected=@($selected|Where-Object{$_.labels.instance-eq$ExpectedInstance})};if(@($selected|Where-Object{$_.health-eq'down'}).Count-gt 0){$r='FAIL'}}catch{$r='FAIL';$detail='Read-only API query failed; raw response was not stored.'}};Add-R V022 'LivePrometheus read-only health' $r $detail}
$ts=(Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK');$overall=if($fail-eq 0){'PASS'}else{'FAIL'};$finalLine="[$overall] Service health after recovery ($modeName): $fail critical failure(s), $warn warning(s).";Write-Host $finalLine;@('SNSD Multi-Cloud Ops - S040 Service Health After Recovery Validation',"Generated: $ts","Validation mode: $modeName",'')+@($ls)+@('', $finalLine,'No recovery, backup, restore, SQL, database connection, infrastructure/configuration mutation, credential, raw live response, or response body was stored or executed.')|Set-Content $log -Encoding UTF8
$out=@('# Service Health After Recovery Validation Summary','', '- Scenario: S040-service-health-after-recovery-validation',"- Generated: $ts","- Validation mode: **$modeName**","- Required file check result: **$(if($missing.Count-eq 0){'PASS'}else{'FAIL'})**","- Web/API/LB result: **$(if($http){'PASS'}else{'FAIL'})**","- Kubernetes result: **$(if($workload-and$endpoint){'PASS'}else{'FAIL'})**","- Database / replication result: **$(if($db-and$repl){'PASS'}else{'FAIL'})**","- Prometheus / Blackbox / alert result: **$(if($prom-and$probe-and$alerts){'PASS'}else{'FAIL'})**","- Backup/restore reference result: **$(if($reference){'PASS'}else{'FAIL'})**","- Final RECOVERED result: **$(if($final-and$manifest){'PASS'}else{'FAIL'})**","- Endpoint / secret safety result: **$(if($safe){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result | Detail |','|---|---|---|---|');foreach($rr in $rs){$out+="| $($rr.Id) | $($rr.Name) | $($rr.Result) | $($rr.Detail) |"};$out|Set-Content $summary -Encoding UTF8;if($fail-gt 0){exit 1};exit 0
