$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L4-failure-recovery\S033-db-replica-failure-validation'
$paths=@{Runbook=Join-Path $root 'runbooks\db-replica-failure-validation.md';Commands=Join-Path $root 'runbooks\db-replica-failure-commands.example.md';Criteria=Join-Path $root 'runbooks\db-replica-failure-criteria.example.md';Ansible=Join-Path $root 'ansible\playbooks\db-replica-status-check.example.yml';Metrics=Join-Path $root 'observability\prometheus\db-replica-failure-metrics.example.md';Pre=Join-Path $e 'logs\pre-failure-replica-status.sample.txt';Injection=Join-Path $e 'logs\replica-failure-injection-event.sample.txt';Detection=Join-Path $e 'logs\replica-failure-detection.sample.txt';Primary=Join-Path $e 'logs\primary-availability-during-replica-failure.sample.txt';Post=Join-Path $e 'logs\post-recovery-replica-status.sample.txt';Catchup=Join-Path $e 'logs\replication-catchup-validation.sample.txt'}
$log=Join-Path $e 'logs\db-replica-failure-validation.log';$summary=Join-Path $e 'configs\db-replica-failure-summary.md';New-Item -ItemType Directory -Force -Path (Split-Path $log),(Split-Path $summary)|Out-Null
$results=[System.Collections.Generic.List[object]]::new();$lines=[System.Collections.Generic.List[string]]::new();$fail=0;$warn=0
function Add-R([string]$Id,[string]$Name,[string]$Result,[string]$Detail){if($Result-eq'FAIL'){$script:fail++};if($Result-eq'WARN'){$script:warn++};$x="[$Result] $Id ${Name}: $Detail";Write-Host $x;$script:lines.Add($x)|Out-Null;$script:results.Add([pscustomobject]@{Id=$Id;Name=$Name;Result=$Result;Detail=$Detail})|Out-Null}
function Read-T([string]$p){if(Test-Path $p -PathType Leaf){Get-Content $p -Raw}else{''}}
$missing=@($paths.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 'Required artifacts' $(if($missing.Count-eq 0){'PASS'}else{'FAIL'}) 'Five baselines and six samples are required.'
$c=@{};foreach($k in $paths.Keys){$c[$k]=Read-T $paths[$k]};$all=($c.Values)-join"`n"
$terms=@('<db-replica-host-placeholder>','<db-primary-host-placeholder>','<replica-service-name-placeholder>','<replication-lag-threshold-seconds>','<evidence-path>','MANUAL FAULT INJECTION ONLY','MANUAL RECOVERY ACTION ONLY');Add-R V002 'Runbook placeholders and boundary' $(if(@($terms|Where-Object{$c.Runbook-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'Required placeholders and manual boundaries must exist.'
$phases=@('Pre-failure replica service state','Pre-failure replication thread health','Pre-failure replication lag','Manual replica failure injection','Replica service failure detection','Replica replication failure detection','Primary availability during replica failure','Recovery action placeholder','Post-recovery replica service state','Post-recovery replication thread health','Post-recovery replication lag','Replication catch-up validation');Add-R V003 'Criteria matrix' $(if(@($phases|Where-Object{$c.Criteria-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'All twelve phases are required.'
$debugOnly=$c.Ansible-match'hosts:\s*db_replica_placeholder'-and$c.Ansible-match'ansible\.builtin\.debug'-and$c.Ansible-notmatch'(?im)^\s*(?:shell|command|service|systemd):';Add-R V004 'Ansible placeholder safety' $(if($debugOnly){'PASS'}else{'FAIL'}) 'Debug-only placeholder is required.'
$metricReady=$c.Metrics-match'<db-replica-instance-placeholder>'-and$c.Metrics-match'seconds_behind_master';Add-R V005 'Metric placeholder documentation' $(if($metricReady){'PASS'}else{'FAIL'}) 'Symbolic replica metrics are required.'
$pre=$c.Pre-match'Replica_(?:IO|SQL)_Running:\s*Yes'-and$c.Pre-match'Replica_IO_Running:\s*Yes'-and$c.Pre-match'Replica_SQL_Running:\s*Yes'-and$c.Pre-match'Seconds_Behind_Master:\s*0';Add-R V006 'Pre-failure replica health' $(if($pre){'PASS'}else{'FAIL'}) 'Both threads must be Yes and lag 0.'
$manual=$c.Injection-match'MANUAL FAULT INJECTION SAMPLE'-and$c.Injection-match'Execution_By_Validator:\s*false';Add-R V007 'Manual failure injection evidence' $(if($manual){'PASS'}else{'FAIL'}) 'Failure event must be manual-only.'
$detected=$c.Detection-match'Replica_IO_Running:\s*No'-and$c.Detection-match'Replica_SQL_Running:\s*No'-and$c.Detection-match'Seconds_Behind_Master:\s*NULL'-and$c.Detection-match'Last_(?:IO|SQL)_Error:';Add-R V008 'Replica failure detection' $(if($detected){'PASS'}else{'FAIL'}) 'Thread failure, NULL lag, and error placeholder are required.'
$primary=$c.Primary-match'reachable-placeholder'-and$c.Primary-match'read-write-available-placeholder'-and$c.Primary-match'<binlog-file-placeholder>'-and$c.Primary-match'<binlog-position-placeholder>';Add-R V009 'Primary availability during replica failure' $(if($primary){'PASS'}else{'FAIL'}) 'Primary reachable/read-write placeholder evidence is required.'
$post=$c.Post-match'Replica_IO_Running:\s*Yes'-and$c.Post-match'Replica_SQL_Running:\s*Yes'-and$c.Post-match'Seconds_Behind_Master:\s*0';Add-R V010 'Post-recovery replica health' $(if($post){'PASS'}else{'FAIL'}) 'Recovered threads and zero lag are required.'
$catchup=$c.Catchup-match'within-threshold-placeholder'-and$c.Catchup-match'IO_Thread:\s*healthy'-and$c.Catchup-match'SQL_Thread:\s*healthy'-and$c.Catchup-match'Replication_Error:\s*none-placeholder';Add-R V011 'Replication catch-up' $(if($catchup){'PASS'}else{'FAIL'}) 'Catch-up and no-error judgment are required.'
$elapsed=[regex]::Match($c.Injection,'(?im)^Recovery_Elapsed_Seconds:\s*(\d+(?:\.\d+)?)\s*$');Add-R V012 'Recovery timing' $(if($elapsed.Success){'PASS'}else{'WARN'}) 'Unmeasured recovery time leaves threshold compliance unproven.'
$badPost=$c.Post-match'(?i)(Running:\s*No|Seconds_Behind_Master:\s*(?:NULL|[1-9]\d*))' -or $c.Catchup-match'(?i)Replication_Error:\s*(?!none-placeholder)\S+';Add-R V013 'Recovered-state failure indicators' $(if(-not$badPost){'PASS'}else{'FAIL'}) 'No unhealthy thread, NULL/excessive lag, or error may remain.'
$forbidden=@(Get-ChildItem $root -Recurse -File -Force -ErrorAction SilentlyContinue|Where-Object{$_.FullName-notmatch'[\\/]\.git[\\/]'-and$_.Name-match'(?i)(?:^|[-_])dump(?:[-_.]|$)|\.dump$|\.sql\.gz$|\.pem$|\.key$|^my\.cnf$|^\.my\.cnf$'});$ip=[regex]::Matches($all,'(?<![A-Za-z0-9<])(?:\d{1,3}\.){3}\d{1,3}(?![A-Za-z0-9>])').Count;$secret=$all-match'(?im)^\s*(?:password|user|token|secret|dsn|connection_string)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$safe=$forbidden.Count-eq 0-and$ip-eq 0-and-not$secret;Add-R V014 'Database evidence safety' $(if($safe){'PASS'}else{'FAIL'}) 'No dump, credential, connection string, address, key, or secret may exist.'
$scriptText=Get-Content $PSCommandPath -Raw;$unsafe=$scriptText-match'(?im)^\s*(?:mysql|mariadb|systemctl|service|ansible-playbook|curl|Invoke-WebRequest|Invoke-RestMethod)\b';Add-R V015 'Execution safety boundary' $(if(-not$unsafe){'PASS'}else{'FAIL'}) 'Validator must not execute DB, service, Ansible, or network commands.'
$timestamp=(Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK');$overall=if($fail-eq 0){'PASS'}else{'FAIL'};$final="[$overall] DB replica failure (StaticEvidence): $fail critical failure(s), $warn warning(s).";Write-Host $final
@('SNSD Multi-Cloud Ops - S033 DB Replica Failure Validation',"Generated: $timestamp",'Validation mode: StaticEvidence','')+@($lines)+@('', $final,'No database, service, SQL, Prometheus, Grafana, or network command was executed.')|Set-Content $log -Encoding UTF8
$out=@('# DB Replica Failure Summary','', '- Scenario: S033-db-replica-failure-validation',"- Generated: $timestamp",'- Validation mode: **StaticEvidence**',"- Required file check result: **$(if($missing.Count-eq 0){'PASS'}else{'FAIL'})**","- Pre-failure replica result: **$(if($pre){'PASS'}else{'FAIL'})**","- Manual fault evidence result: **$(if($manual){'PASS'}else{'FAIL'})**","- Failure detection result: **$(if($detected){'PASS'}else{'FAIL'})**","- Primary availability result: **$(if($primary){'PASS'}else{'FAIL'})**","- Post-recovery replica result: **$(if($post){'PASS'}else{'FAIL'})**","- Catch-up result: **$(if($catchup){'PASS'}else{'FAIL'})**","- Secret-safety result: **$(if($safe){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result | Detail |','|---|---|---|---|');foreach($r in $results){$out+="| $($r.Id) | $($r.Name) | $($r.Result) | $($r.Detail) |"};$out|Set-Content $summary -Encoding UTF8
if($fail-gt 0){exit 1};exit 0
