$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L4-failure-recovery\S038-backup-creation-validation'
$p=@{Runbook=Join-Path $root 'runbooks\backup-creation-validation.md';Commands=Join-Path $root 'runbooks\backup-creation-commands.example.md';Criteria=Join-Path $root 'runbooks\backup-creation-criteria.example.md';Policy=Join-Path $root 'policy\backup-retention-policy.example.md';Ansible=Join-Path $root 'ansible\playbooks\backup-creation-check.example.yml';Command=Join-Path $e 'logs\backup-command-output.sample.txt';Metadata=Join-Path $e 'logs\backup-file-metadata.sample.txt';Checksum=Join-Path $e 'logs\backup-checksum.sample.txt';Listing=Join-Path $e 'logs\backup-repository-listing.sample.txt';Creation=Join-Path $e 'logs\backup-creation-summary.sample.txt';Manifest=Join-Path $e 'configs\backup-manifest.sample.yml'}
$log=Join-Path $e 'logs\backup-creation-validation.log';$summary=Join-Path $e 'configs\backup-creation-validation-summary.md';New-Item -ItemType Directory -Force -Path (Split-Path $log),(Split-Path $summary)|Out-Null
$rs=[System.Collections.Generic.List[object]]::new();$ls=[System.Collections.Generic.List[string]]::new();$fail=0;$warn=0
function Add-R([string]$Id,[string]$Name,[string]$Result,[string]$Detail){if($Result-eq'FAIL'){$script:fail++};if($Result-eq'WARN'){$script:warn++};$x="[$Result] $Id ${Name}: $Detail";Write-Host $x;$script:ls.Add($x)|Out-Null;$script:rs.Add([pscustomobject]@{Id=$Id;Name=$Name;Result=$Result;Detail=$Detail})|Out-Null};function T([string]$x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 'Required artifacts' $(if($missing.Count-eq 0){'PASS'}else{'FAIL'}) 'Five baselines and six samples are required.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$terms=@('<backup-scope-placeholder>','<backup-source-placeholder>','<backup-target-placeholder>','<backup-method-placeholder>','<backup-file-placeholder>','<backup-manifest-placeholder>','<retention-class-placeholder>','<encryption-placeholder>','<access-control-placeholder>','<evidence-path>','S039','S040');Add-R V002 'Runbook workflow and placeholders' $(if(@($terms|Where-Object{$c.Runbook-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'Scope, source, target, integrity, protection, and downstream references are required.'
$phases=@('Backup scope definition','Backup source identification','Backup target identification','Backup command execution evidence placeholder','Backup artifact metadata','Backup manifest creation','Backup checksum generation','Backup size sanity check','Retention classification','Encryption / access control placeholder','Backup creation final summary');Add-R V003 'Criteria matrix' $(if(@($phases|Where-Object{$c.Criteria-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'All eleven phases are required.'
$policyFields=@('owner','retention','created','expiry','Encryption','access-control','S039');Add-R V004 'Retention policy requirements' $(if(@($policyFields|Where-Object{$c.Policy-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'Ownership, retention, expiry, protection, and restore linkage are required.'
$debug=$c.Ansible-match'hosts:\s*backup_target_placeholder'-and$c.Ansible-match'ansible\.builtin\.debug'-and$c.Ansible-notmatch'(?im)^\s*(?:shell|command|archive|synchronize|copy|fetch):';Add-R V005 'Ansible placeholder safety' $(if($debug){'PASS'}else{'FAIL'}) 'Debug-only non-production example is required.'
$command=$c.Command-match'completed-placeholder'-and$c.Command-match'<backup-file-placeholder>'-and$c.Command-match'Production_Command_Output_Stored:\s*false';Add-R V006 'Backup command evidence' $(if($command){'PASS'}else{'FAIL'}) 'Sanitized completion and no-production-output markers are required.'
$size=[regex]::Match($c.Metadata,'(?im)^Size_Bytes:\s*(\d+)\s*$');$metadata=$c.Metadata-match'<backup-file-placeholder>'-and$c.Metadata-match'<created-at-placeholder>'-and$c.Metadata-match'<owner-placeholder>'-and$c.Metadata-match'<retention-class-placeholder>'-and$size.Success-and[int64]$size.Groups[1].Value-gt 0;Add-R V007 'Backup artifact metadata' $(if($metadata){'PASS'}else{'FAIL'}) 'Name, time, positive size, owner, and retention are required.'
$checksum=$c.Checksum-match'Checksum_Algorithm:\s*SHA256'-and$c.Checksum-match'<sha256-placeholder>'-and$c.Checksum-match'<backup-file-placeholder>'-and$c.Checksum-match'Production_Hash_Stored:\s*false';Add-R V008 'Checksum evidence' $(if($checksum){'PASS'}else{'FAIL'}) 'SHA256 placeholder and no-production-hash marker are required.'
$listing=$c.Listing-match'<backup-target-placeholder>'-and$c.Listing-match'<backup-file-placeholder>'-and$c.Listing-match'<backup-manifest-placeholder>'-and$c.Listing-match'Real_Path_Or_Bucket_Stored:\s*false';Add-R V009 'Repository listing evidence' $(if($listing){'PASS'}else{'FAIL'}) 'Symbolic target/file/manifest and no-real-storage marker are required.'
$manifestFields=@('backup_id','backup_source','backup_target','backup_method','backup_file','created_at','size_bytes','checksum_algorithm','checksum','retention_class','encryption_placeholder','access_control_placeholder','restore_validation_scenario: S039','health_validation_scenario: S040','evidence_reference');$manifest=@($manifestFields|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq 0;Add-R V010 'Backup manifest fields' $(if($manifest){'PASS'}else{'FAIL'}) 'All required manifest fields are required.'
$creation=$c.Creation-match'Backup_Created:\s*true-placeholder'-and$c.Creation-match'Manifest_Created:\s*true'-and$c.Creation-match'Checksum_Generated:\s*true'-and$c.Creation-match'Retention_Class_Assigned:\s*true'-and$c.Creation-match'Real_Backup_Artifact_Committed:\s*false';Add-R V011 'Backup creation summary evidence' $(if($creation){'PASS'}else{'FAIL'}) 'Created/manifest/checksum/retention and no-real-artifact judgments are required.'
$risky=@(Get-ChildItem $e -Recurse -File -Force|Where-Object{$_.Name-notmatch'\.sample\.'-and$_.Name-match'(?i)\.(?:bak|backup|dump|sql|gz|tgz|tar|zip|7z|db|sqlite)$'});Add-R V012 'Real backup artifact safety' $(if($risky.Count-eq 0){'PASS'}else{'FAIL'}) 'No archive, dump, database, or backup artifact may exist.'
$pathHit=$all-match'(?im)(?:[A-Z]:\\|/(?:home|var|opt|srv|mnt|data)/|s3://|az://|swift://|gs://)';$secret=$all-match'(?im)^\s*(?:password|token|secret|access_key|connection_string)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$safe=-not$pathHit-and-not$secret;Add-R V013 'Storage path and secret safety' $(if($safe){'PASS'}else{'FAIL'}) 'No real path, bucket/repository URI, credential, connection string, key, or secret may exist.'
$script=Get-Content $PSCommandPath -Raw;$unsafe=$script-match'(?im)^\s*(?:mysqldump|pg_dump|tar|zip|Compress-Archive|restic|borg|aws|az|openstack|rclone|ansible-playbook)\b';Add-R V014 'Execution safety boundary' $(if(-not$unsafe){'PASS'}else{'FAIL'}) 'Validator must not create/dump/archive/upload/query backups or execute Ansible.'
$commandsOut=$c.Commands-match'OUT OF SCOPE'-and$c.Commands-match'never executed';Add-R V015 'Command reference boundary' $(if($commandsOut){'PASS'}else{'FAIL'}) 'Operational backup commands must be sample-only and out of scope.'
$ts=(Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK');$overall=if($fail-eq 0){'PASS'}else{'FAIL'};$final="[$overall] Backup creation (StaticEvidence): $fail critical failure(s), $warn warning(s).";Write-Host $final;@('SNSD Multi-Cloud Ops - S038 Backup Creation Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+@($ls)+@('', $final,'No backup, dump, archive, upload, storage query, Ansible run, credential read, or production-data access occurred.')|Set-Content $log -Encoding UTF8
$out=@('# Backup Creation Validation Summary','', '- Scenario: S038-backup-creation-validation',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required file check result: **$(if($missing.Count-eq 0){'PASS'}else{'FAIL'})**","- Policy requirement check result: **$(if(@($policyFields|Where-Object{$c.Policy-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'})**","- Backup command evidence result: **$(if($command){'PASS'}else{'FAIL'})**","- Metadata result: **$(if($metadata){'PASS'}else{'FAIL'})**","- Manifest result: **$(if($manifest){'PASS'}else{'FAIL'})**","- Checksum result: **$(if($checksum){'PASS'}else{'FAIL'})**","- Retention result: **$(if($creation){'PASS'}else{'FAIL'})**","- Artifact / secret safety result: **$(if($risky.Count-eq 0-and$safe){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result | Detail |','|---|---|---|---|');foreach($r in $rs){$out+="| $($r.Id) | $($r.Name) | $($r.Result) | $($r.Detail) |"};$out|Set-Content $summary -Encoding UTF8;if($fail-gt 0){exit 1};exit 0
