$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e="$root/evidence/L5-governance-intelligent-ops/S049-ml-anomaly-report-generation-validation"
$p=@{Runbook="$root/runbooks/ml-anomaly-report-generation-validation.md";Commands="$root/runbooks/ml-anomaly-report-generation-commands.example.md";Template="$root/ml-security/reports/ml-anomaly-report-template.example.md";Criteria="$root/ml-security/reports/ml-anomaly-report-criteria.example.md";Decision="$root/ml-security/reports/ml-anomaly-report-decision-matrix.example.md";Policy="$root/policy/ml-anomaly-report-generation-policy.example.md";Input="$root/ml-security/reports/ml-anomaly-report-input-summary.sample.yml";Checklist="$root/ml-security/reports/ml-anomaly-report-quality-checklist.example.md";Report="$root/ml-security/reports/ml-anomaly-report.sample.md";Json="$root/ml-security/reports/ml-anomaly-report-summary.sample.json";Invalid="$root/ml-security/reports/ml-anomaly-report-invalid.sample.md";Script="$root/ml-security/scripts/anomaly-report-generation.example.py";TemplateLog="$e/logs/ml-anomaly-report-template-load.sample.txt";InputLog="$e/logs/ml-anomaly-report-input-validation.sample.txt";RunLog="$e/logs/ml-anomaly-report-generation-run.sample.txt";PassLog="$e/logs/ml-anomaly-report-validation-pass.sample.txt";FailLog="$e/logs/ml-anomaly-report-validation-fail.sample.txt";MapLog="$e/logs/ml-anomaly-report-scenario-mapping.sample.txt";Privacy="$e/logs/ml-anomaly-report-privacy-safety.sample.txt";Final="$e/logs/ml-anomaly-report-generation-final-summary.sample.txt";Manifest="$e/configs/ml-anomaly-report-generation-validation-manifest.sample.yml"}
$log="$e/logs/ml-anomaly-report-generation-validation.log";$summary="$e/configs/ml-anomaly-report-generation-validation-summary.md";$res=@();$fails=0;$warns=0
function Add-R($id,$name,$ok,$detail,$warning=$false){$s=if($ok){'PASS'}elseif($warning){'WARN'}else{'FAIL'};if($s-eq'FAIL'){$script:fails++};if($s-eq'WARN'){$script:warns++};Write-Host "[$s] $id ${name}: $detail";$script:res+=[pscustomobject]@{Id=$id;Name=$name;Status=$s}};function T($x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 Artifacts ($missing.Count-eq0) 'Required S049 artifacts exist.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$cmd=$c.Commands-match'OPTIONAL MANUAL LOCAL SAMPLE ONLY'-and$c.Commands-match'does not query Prometheus'-and$c.Commands-match'does not query.*Grafana'-and$c.Commands-match'train/deploy'-and$c.Commands-match'call an LLM'-and$c.Commands-match'automated blocking';Add-R V002 Commands $cmd 'No-query, no-model, no-LLM, and no-blocking boundaries exist.'
$sections=@('Report Metadata','Executive Summary','Dataset Reference','Detection Run Reference','Anomaly Summary','Top Anomaly Candidates','Affected Metric Groups','Operational Interpretation','Confidence / Review Notes','Recommended Operator Actions','Out-of-Scope Actions','Evidence References','S047 / S048 / S050 Scenario Mapping','Final Report Judgment');$template=@($sections|Where-Object{$c.Template-notmatch[regex]::Escape($_)}).Count-eq0-and@('REPORT_READY','REPORT_WARNING','REPORT_EVIDENCE_INCOMPLETE','REPORT_REVIEW_REQUIRED','REPORT_INVALID'|Where-Object{$c.Template-notmatch$_}).Count-eq0;Add-R V003 Template $template 'Required sections and judgment values exist.'
$input=@('S047','S048','S050','anomaly_count','warning_count','review_required_count','evidence_reference');$inputOk=@($input|Where-Object{$c.Input-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V004 Input $inputOk 'Input summary has counts, evidence, and mappings.'
$reportSections=@('Report Metadata','Executive Summary','Dataset Reference','Detection Run Reference','Anomaly Summary','Top Anomaly Candidates','Operational Interpretation','Recommended Operator Actions','Out-of-Scope Actions','Evidence References','Scenario Mapping','Final Report Judgment');$report=@($reportSections|Where-Object{$c.Report-notmatch[regex]::Escape($_)}).Count-eq0-and@('S047','S048','S050','human review is required','No automated blocking','not an LLM-based final decision','final_judgment: REPORT_READY'|Where-Object{$c.Report-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V005 Report $report 'Valid report has sections, mappings, human review, and safety statements.'
$json=$false;try{$j=$c.Json|ConvertFrom-Json;$fields=@('report_id','dataset_source_scenario','anomaly_detection_scenario','final_evidence_report_scenario','dataset_id','detection_run_id','anomaly_count','warning_count','review_required_count','report_status','final_judgment','evidence_reference');$json=@($fields|Where-Object{$_-notin$j.PSObject.Properties.Name}).Count-eq0-and$j.dataset_source_scenario-eq'S047'-and$j.anomaly_detection_scenario-eq'S048'-and$j.final_evidence_report_scenario-eq'S050'-and$j.final_judgment-eq'REPORT_READY'}catch{$json=$false};Add-R V006 SummaryJson $json 'Summary JSON is parseable, complete, and mapped.'
$invalid=$c.Invalid-match'INVALID SAMPLE'-and$c.Invalid-match'omits the S048'-and$c.Invalid-match'INVALID_REPORT_JUDGMENT';Add-R V007 Invalid $invalid 'Invalid fixture is clearly marked and intentionally incomplete.'
$evidence=$c.TemplateLog-match'Required_Report_Sections_Validated:\s*true'-and$c.InputLog-match'S047'-and$c.InputLog-match'S048'-and$c.InputLog-match'S050'-and$c.RunLog-match'LLM_Analysis_Performed:\s*false'-and$c.RunLog-match'Automated_Blocking_Performed:\s*false'-and$c.PassLog-match'REPORT_READY'-and$c.FailLog-match'REPORT_INVALID'-and$c.MapLog-match'S047'-and$c.MapLog-match'S048'-and$c.MapLog-match'S050';Add-R V008 Evidence $evidence 'Template/input/run/pass/fail/mapping evidence is consistent.'
$privacy=@('No_Raw_Logs: true','No_Packet_Payload: true','No_SIEM_Logs: true','No_Wazuh_Logs: true','No_EDR_Telemetry: true','No_Credentials: true','No_Real_IPs: true','No_Real_Hostnames: true','No_Production_Identifiers: true');$privacyOk=@($privacy|Where-Object{$c.Privacy-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V009 Privacy $privacyOk 'Privacy and telemetry exclusions are confirmed.'
$final=$c.Final-match'REPORT_READY'-and$c.Final-match'Live_Prometheus_Query_Performed:\s*false'-and$c.Final-match'ML_Model_Trained:\s*false'-and$c.Final-match'Model_Deployed:\s*false'-and$c.Final-match'LLM_Analysis_Performed:\s*false'-and$c.Final-match'Automated_Blocking_Performed:\s*false'-and$c.Final-match'S050';Add-R V010 Final $final 'Final summary confirms safe report generation.'
$mf=@('ml_anomaly_report_generation_validation_id','report_id','dataset_source_scenario: S047','anomaly_detection_scenario: S048','final_evidence_report_scenario: S050','dataset_id','detection_run_id','report_template_reference','report_input_reference','report_output_reference','report_summary_reference','invalid_report_reference','anomaly_count','warning_count','review_required_count','privacy_safety_result','evidence_reference','final_judgment');$manifest=@($mf|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V011 Manifest $manifest 'Manifest fields and S047/S048/S050 mappings exist.'
$policyTerms=@('metric-only S048','S047','S050','SIEM','Wazuh','EDR','raw logs','packet','malware detection','threat hunting','LLM-based final decisions','automated blocking','SOC auto-incident creation','human review');$policy=@($policyTerms|Where-Object{$c.Policy-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V012 Policy $policy 'Policy scope and human-review requirements exist.'
$bins=@(Get-ChildItem $root -Recurse -File -Force -ErrorAction SilentlyContinue|Where-Object{$_.FullName-notlike"$root/.git*"-and$_.Extension-match'(?i)^\.(pkl|pickle|joblib|onnx|pt|pth|h5|pb|pcap|pcapng)$'});Add-R V013 BinarySafety ($bins.Count-eq0) 'No model or packet binary exists.'
$ip=$all-match'(?<![\w<])(?:\d{1,3}\.){3}\d{1,3}(?![\w>])';$url=$all-match'(?i)https?://(?!<)[a-z0-9]';$secret=$all-match'(?im)^\s*(?:password|token|secret|access_key|api_key|authorization)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$src=Get-Content $PSCommandPath -Raw;$exec=$src-match'(?im)^\s*(?:curl|python|kubectl|aws|az|openstack)\s+';Add-R V014 Safety (-not$ip-and-not$url-and-not$secret-and-not$exec) 'No endpoint, secret, or external execution detected.'
$scriptOk=$c.Script-match'SAMPLE / NON-PRODUCTION'-and$c.Script-notmatch'(?i)sklearn|tensorflow|torch|requests|urllib|socket|openai'-and$c.Script-match'Human review is required';Add-R V015 SampleScript $scriptOk 'Optional script is deterministic standard-library reporting.'
Add-R V016 Maturity $false 'Interpretation and counts are synthetic static-sample evidence.' $true
$ts=(Get-Date).ToString('s');$overall=if($fails){'FAIL'}else{'PASS'};$end="[$overall] ML anomaly report generation (StaticEvidence): $fails critical failure(s), $warns warning(s).";Write-Host $end;@('S049 ML Anomaly Report Generation Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+($res|ForEach-Object{"[$($_.Status)] $($_.Id) $($_.Name)"})+@('',$end,'No live query, model operation, LLM call, incident creation, or blocking occurred.')|Set-Content $log -Encoding UTF8
@('# ML Anomaly Report Generation Validation Summary','',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required files: **$(if($missing.Count-eq0){'PASS'}else{'FAIL'})**","- Command safety: **$(if($cmd){'PASS'}else{'FAIL'})**","- Report template/input/output: **$(if($template-and$inputOk-and$report){'PASS'}else{'FAIL'})**","- Summary JSON/invalid report: **$(if($json-and$invalid){'PASS'}else{'FAIL'})**","- Scenario mappings: **$(if($manifest){'PASS'}else{'FAIL'})**","- Privacy/LLM/model/secret safety: **$(if($privacyOk-and$bins.Count-eq0-and-not$ip-and-not$url-and-not$secret){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**")|Set-Content $summary -Encoding UTF8;if($fails){exit 1}
