$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e="$root\evidence\L5-governance-intelligent-ops\S046-resource-cleanup-validation"
$p=@{Runbook="$root\runbooks\resource-cleanup-validation.md";Commands="$root\runbooks\resource-cleanup-commands.example.md";Rules="$root\cost-governance\resource-cleanup-rules.example.yml";Criteria="$root\cost-governance\resource-cleanup-criteria.example.md";Decision="$root\cost-governance\resource-cleanup-decision-matrix.example.md";ImpactMatrix="$root\cost-governance\resource-cleanup-impact-classification-matrix.example.md";Policy="$root\policy\resource-cleanup-policy.example.md";ReadyInput="$root\cost-governance\resource-cleanup-input-ready.example.json";BlockedInput="$root\cost-governance\resource-cleanup-input-blocked.example.json";ExceptionInput="$root\cost-governance\resource-cleanup-input-exception.example.json";Load="$e\logs\cleanup-rule-load.sample.txt";Inventory="$e\logs\cleanup-candidate-inventory.sample.txt";Ready="$e\logs\cleanup-evaluation-ready.sample.txt";Blocked="$e\logs\cleanup-evaluation-blocked.sample.txt";Exception="$e\logs\cleanup-exception-approval.sample.txt";Impact="$e\logs\cleanup-impact-classification.sample.txt";Plan="$e\logs\cleanup-plan.sample.txt";Final="$e\logs\cleanup-final-summary.sample.txt";Manifest="$e\configs\resource-cleanup-validation-manifest.sample.yml"}
$log="$e\logs\resource-cleanup-validation.log";$summary="$e\configs\resource-cleanup-validation-summary.md";$res=@();$fails=0;$warns=0;function Add-R($id,$name,$ok,$detail,$warning=$false){$s=if($ok){'PASS'}elseif($warning){'WARN'}else{'FAIL'};if($s-eq'FAIL'){$script:fails++};if($s-eq'WARN'){$script:warns++};Write-Host "[$s] $id ${name}: $detail";$script:res+=@([pscustomobject]@{Id=$id;Name=$name;Status=$s})};function T($x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 Artifacts ($missing.Count-eq0) 'Required cleanup artifacts exist.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$deleteTerms=@('terraform destroy','terraform apply','terraform state rm','terminate-instances','az resource delete','openstack server delete','kubectl delete');$cmd=$c.Commands-match'MANUAL LAB INVENTORY EXAMPLES ONLY'-and$c.Commands-match'MANUAL LAB EVIDENCE CONVERSION ONLY'-and$c.Commands-match'OUT OF SCOPE'-and@($deleteTerms|Where-Object{$c.Commands-notmatch[regex]::Escape($_)}).Count-eq0-and$c.Commands-match'does not.*delete resources'-and$c.Commands-match'no external cleanup tool is required';Add-R V002 Commands $cmd 'Inventory is manual and all deletion commands are out of scope.'
$judgments=@('CLEANUP_READY','CLEANUP_NOT_REQUIRED','CLEANUP_BLOCKED','CLEANUP_EXCEPTION_APPROVED','CLEANUP_EVIDENCE_INCOMPLETE','CLEANUP_REVIEW_REQUIRED');$exc=@('exception_id','owner','reason','expiry','approval_id','rollback_condition','evidence_reference');$domains=@('ownership','lifecycle','retention','cost','orphan','dependency','approval','cleanup-plan','final-report');$rules=@($judgments+$exc+$domains|Where-Object{$c.Rules-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V003 Rules $rules 'Judgments, exception fields, and cleanup domains are required.'
$json=$true;try{$a=$c.ReadyInput|ConvertFrom-Json;$b=$c.BlockedInput|ConvertFrom-Json;$d=$c.ExceptionInput|ConvertFrom-Json;$json=$a.final_expected_judgment-eq'CLEANUP_READY'-and$b.final_expected_judgment-eq'CLEANUP_BLOCKED'-and$d.final_expected_judgment-eq'CLEANUP_EXCEPTION_APPROVED'}catch{$json=$false};Add-R V004 Inputs $json 'Ready/blocked/exception JSON inputs are consistent.'
$load=$c.Load-match'Cleanup_Rules_Loaded'-and$c.Load-match'Real_Cloud_Inventory_Queried:\s*false'-and$c.Load-match'External_Cleanup_Tool_Required:\s*false';$inventory=$c.Inventory-match'Cleanup_Candidate_ID'-and$c.Inventory-match'Owner'-and$c.Inventory-match'Retention_Class'-and$c.Inventory-match'Cost_Classification'-and$c.Inventory-match'Dependency_Risk'-and$c.Inventory-match'Real_Resource_ID_Stored:\s*false';Add-R V005 'Load and inventory' ($load-and$inventory) 'Rules and sanitized candidate metadata required.'
$ready=$c.Ready-match'Owner_Present'-and$c.Ready-match'Retention_Class_Present'-and$c.Ready-match'Dependency_Risk:\s*low-placeholder'-and$c.Ready-match'S045_Cost_Mapping_Present:\s*true'-and$c.Ready-match'CLEANUP_READY';Add-R V006 Ready $ready 'Ready evidence requires owner, retention, low risk, and S045.'
$blocked=$c.Blocked-match'Missing_Owner'-and$c.Blocked-match'Missing_Retention_Class'-and$c.Blocked-match'Dependency_Risk:\s*high-placeholder'-and$c.Blocked-match'Missing_Approval'-and$c.Blocked-match'CLEANUP_BLOCKED';Add-R V007 Blocked $blocked 'Blocked evidence requires explicit blockers.'
$exception=@($exc|Where-Object{$c.Exception-notmatch[regex]::Escape($_)}).Count-eq0-and$c.Exception-match'CLEANUP_EXCEPTION_APPROVED';Add-R V008 Exception $exception 'Complete approved exception required.'
$impact=$c.Impact-match'Resource_Category'-and$c.Impact-match'Cleanup_Signal'-and$c.Impact-match'Dependency_Risk'-and$c.Impact-match'Cost_Impact'-and$c.Impact-match'Required_Action';Add-R V009 Impact $impact 'Impact classification fields required.'
$plan=$c.Plan-match'Cleanup_Change_ID'-and$c.Plan-match'Candidate_Resource'-and$c.Plan-match'Cleanup_Action'-and$c.Plan-match'Approval_Requirement'-and$c.Plan-match'Rollback_Note'-and$c.Plan-match'Deletion_Performed_By_Validation_Script:\s*false';Add-R V010 Plan $plan 'Plan and explicit no-deletion marker required.'
$final=$c.Final-match'Cleanup_Rules_Validated:\s*true'-and$c.Final-match'Real_Resource_Deletion_Performed:\s*false'-and$c.Final-match'Real_Cloud_Operation_Performed:\s*false'-and$c.Final-match'CLEANUP_READY';Add-R V011 Summary $final 'Rules validated with no deletion/cloud operation.'
$mf=@('resource_cleanup_validation_id','cleanup_rule_set_reference','cleanup_candidate_inventory_reference','ready_input_reference','blocked_input_reference','exception_input_reference','cleanup_impact_classification_reference','cleanup_plan_reference','cost_guardrail_scenario: S045','drift_detection_scenario: S041','drift_remediation_scenario: S042','policy_as_code_scenario: S043','final_evidence_report_scenario: S050','evidence_reference','final_judgment');$manifest=@($mf|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V012 Manifest $manifest 'All fields and S041/S042/S043/S045/S050 mappings required.'
$policy=@('owner evidence','retention classification','cost classification','dependency risk review','rollback or recovery note','Critical cleanup requires approval','Real resource deletion must not be executed','Terraform destroy','S045','S050');$policyOk=@($policy|Where-Object{$c.Policy-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V013 Policy $policyOk 'Ownership, retention, cost, risk, rollback, approval, and deletion boundaries required.'
$risky=@(Get-ChildItem $root -Recurse -Force -ErrorAction SilentlyContinue|Where-Object{($_.FullName-notlike"$root\.git*")-and(($_.PSIsContainer-and$_.Name-eq'.terraform')-or(-not$_.PSIsContainer-and$_.Name-match'^(?:terraform\.tfstate(?:\.backup)?|terraform\.tfvars|.+\.auto\.tfvars|kubeconfig)$'))});Add-R V014 ArtifactSafety ($risky.Count-eq0) 'No state, tfvars, .terraform, or kubeconfig.'
$ip=$all-match'(?<![\w<])(?:\d{1,3}\.){3}\d{1,3}(?![\w>])';$id=$all-match'\b\d{12}\b'-or$all-match'(?i)\b(?:i|vol|vpc|sg|subnet)-[0-9a-f]{6,}\b';$secret=$all-match'(?im)^\s*(?:password|token|secret|access_key|api_key|authorization)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$src=Get-Content $PSCommandPath -Raw;$exec=$src-match'(?im)^\s*(?:terraform|aws|az|openstack|kubectl)\s+';Add-R V015 Safety (-not$ip-and-not$id-and-not$secret-and-not$exec) 'No identifiers, networks, credentials, keys, delete execution, or external tool.'
Add-R V016 Maturity $false 'Candidate, approval, risk, and cleanup actions are placeholder-only.' $true
$ts=(Get-Date).ToString('s');$overall=if($fails){'FAIL'}else{'PASS'};$end="[$overall] Resource cleanup (StaticEvidence): $fails critical failure(s), $warns warning(s).";Write-Host $end;@('S046 Resource Cleanup Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+($res|ForEach-Object{"[$($_.Status)] $($_.Id) $($_.Name)"})+@('',$end,'No Terraform, cloud CLI/API, kubectl, inventory query, deletion, or cleanup operation occurred.')|Set-Content $log -Encoding UTF8
@('# Resource Cleanup Validation Summary','',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required files: **$(if($missing.Count-eq0){'PASS'}else{'FAIL'})**","- Command safety: **$(if($cmd){'PASS'}else{'FAIL'})**","- Rules/inputs: **$(if($rules-and$json){'PASS'}else{'FAIL'})**","- Ready/blocked/exception: **$(if($ready-and$blocked-and$exception){'PASS'}else{'FAIL'})**","- Impact/plan: **$(if($impact-and$plan){'PASS'}else{'FAIL'})**","- Manifest/mappings: **$(if($manifest){'PASS'}else{'FAIL'})**","- Artifact/secret safety: **$(if($risky.Count-eq0-and-not$ip-and-not$id-and-not$secret){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**")|Set-Content $summary -Encoding UTF8;if($fails){exit 1}
