$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L5-governance-intelligent-ops\S044-kubernetes-manifest-policy-validation'
$p=@{Runbook="$root\runbooks\kubernetes-manifest-policy-validation.md";Commands="$root\runbooks\kubernetes-manifest-policy-commands.example.md";Rules="$root\policy\kubernetes-manifest-policy-rules.example.yml";Criteria="$root\policy\kubernetes-manifest-policy-criteria.example.md";Decision="$root\policy\kubernetes-manifest-policy-decision-matrix.example.md";Compliant="$root\kubernetes\security\manifest-policy-compliant-deployment.example.yml";Violation="$root\kubernetes\security\manifest-policy-violation-deployment.example.yml";ExceptionManifest="$root\kubernetes\security\manifest-policy-exception-deployment.example.yml";Exposure="$root\kubernetes\security\manifest-policy-service-exposure.example.yml";Load="$e\logs\kubernetes-policy-rule-load.sample.txt";Pass="$e\logs\kubernetes-manifest-compliant-evaluation.sample.txt";Fail="$e\logs\kubernetes-manifest-violation-evaluation.sample.txt";Exception="$e\logs\kubernetes-manifest-exception-approval.sample.txt";Class="$e\logs\kubernetes-manifest-violation-classification.sample.txt";Final="$e\logs\kubernetes-manifest-policy-final-summary.sample.txt";Manifest="$e\configs\kubernetes-manifest-policy-validation-manifest.sample.yml"}
$log="$e\logs\kubernetes-manifest-policy-validation.log";$summary="$e\configs\kubernetes-manifest-policy-validation-summary.md";$res=@();$fails=0;$warns=0;function Add-R($id,$name,$ok,$detail,$warning=$false){$s=if($ok){'PASS'}elseif($warning){'WARN'}else{'FAIL'};if($s-eq'FAIL'){$script:fails++};if($s-eq'WARN'){$script:warns++};Write-Host "[$s] $id ${name}: $detail";$script:res+=@([pscustomobject]@{Id=$id;Name=$name;Status=$s})};function T($x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 Artifacts ($missing.Count-eq0) 'Required baselines, examples, evidence, and manifest exist.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$cmd=$c.Commands-match'OPTIONAL MANUAL LAB CHECK EXAMPLES ONLY'-and$c.Commands-match'OPTIONAL EXAMPLES ONLY'-and$c.Commands-match'does not require'-and$c.Commands-match'never connects';Add-R V002 Commands $cmd 'kubectl and policy engines are optional and no cluster is contacted.'
$areas=@('privileged','allowPrivilegeEscalation','runAsNonRoot','readOnlyRootFilesystem','requests','limits','livenessProbe','readinessProbe','latest','hostNetwork','hostPID','hostIPC','hostPath','NodePort','LoadBalancer','hardcoded secrets','ConfigMap','S018');$judgments=@('K8S_POLICY_PASS','K8S_POLICY_FAIL','K8S_POLICY_WARNING','K8S_POLICY_EXCEPTION_APPROVED','K8S_POLICY_EVIDENCE_INCOMPLETE','K8S_POLICY_REVIEW_REQUIRED');$exc=@('exception_id','owner','reason','expiry','approval_id','rollback_condition','evidence_reference');$rules=@($areas+$judgments+$exc|Where-Object{$c.Rules-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V003 Rules $rules 'Policy areas, judgments, and exception fields are complete.'
$base=@('runAsNonRoot: true','allowPrivilegeEscalation: false','privileged: false','readOnlyRootFilesystem: true','requests:','limits:','livenessProbe:','readinessProbe:','hostNetwork: false','hostPID: false','hostIPC: false');$compliant=@($base|Where-Object{$c.Compliant-notmatch[regex]::Escape($_)}).Count-eq0-and$c.Compliant-notmatch':latest';Add-R V004 'Compliant manifest' $compliant 'Secure baseline fields and non-latest image are required.'
$violation=$c.Violation-match'VIOLATION SAMPLE'-and$c.Violation-match'privileged: true'-and$c.Violation-match'allowPrivilegeEscalation: true'-and$c.Violation-match'runAsUser: 0'-and$c.Violation-match':latest'-and$c.Violation-match'hostPath';Add-R V005 'Violation manifest' $violation 'Known violations must be clearly labeled.'
$exception=@($exc|Where-Object{$c.ExceptionManifest-notmatch[regex]::Escape($_)}).Count-eq0-and$c.ExceptionManifest-match'K8S_POLICY_EXCEPTION_APPROVED';Add-R V006 'Exception manifest' $exception 'All exception fields and judgment are required.'
$exposure=$c.Exposure-match'VIOLATION SAMPLE'-and$c.Exposure-match'NodePort'-and$c.Exposure-match'ClusterIP';Add-R V007 'Service exposure' $exposure 'Unsafe exposure is violation-only and safe example is ClusterIP.'
$ev=$c.Load-match'External_Policy_Engine_Required:\s*false'-and$c.Pass-match'K8S_POLICY_PASS'-and$c.Fail-match'K8S_POLICY_FAIL'-and$c.Exception-match'K8S_POLICY_EXCEPTION_APPROVED'-and$c.Class-match'Severity'-and$c.Class-match'Required_Action';Add-R V008 Evidence $ev 'Load/pass/fail/exception/classification evidence is consistent.'
$final=$c.Final-match'Manifest_Policy_Rules_Validated:\s*true'-and$c.Final-match'Live_Cluster_Operation_Performed:\s*false'-and$c.Final-match'K8S_POLICY_PASS';Add-R V009 Summary $final 'Policy validated with no live operation.'
$mf=@('k8s_policy_validation_id','policy_rule_set_reference','compliant_manifest_reference','violation_manifest_reference','exception_manifest_reference','service_exposure_manifest_reference','violation_count_placeholder','critical_violation_count_placeholder','exception_count_placeholder','policy_as_code_scenario: S043','kubernetes_rbac_scenario: S018','workload_deployment_scenario: S022','service_health_scenario: S040','evidence_reference','final_judgment');$manifest=@($mf|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V010 Manifest $manifest 'Manifest fields and S043/S018/S022/S040 mappings are required.'
$kube=@(Get-ChildItem $root -Recurse -File -Force -ErrorAction SilentlyContinue|Where-Object{$_.FullName-notlike"$root\.git*"-and$_.Name-match'(?i)^(?:kubeconfig|config\.kube)$'});Add-R V011 Kubeconfig ($kube.Count-eq0) 'No kubeconfig file may exist.'
$ip=$all-match'(?<![\w<])(?:\d{1,3}\.){3}\d{1,3}(?![\w>])';$domain=$all-match'(?i)\b(?:https?://)?[a-z0-9-]+\.(?:com|net|org|io|cloud)(?:/\S*)?\b';$secret=$all-match'(?im)^\s*(?:password|token|secret|authorization|api_key)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN (?:CERTIFICATE|.*PRIVATE KEY)-----';Add-R V012 Safety (-not$ip-and-not$domain-and-not$secret) 'No real endpoints, registries, networks, credentials, certificates, keys, or secrets.'
$src=Get-Content $PSCommandPath -Raw;$exec=$src-match'(?im)^\s*(?:kubectl|opa|conftest|kyverno|aws|az|openstack)\s+';Add-R V013 Execution (-not$exec) 'No kubectl, policy engine, cloud CLI, or cluster execution.'
$boundary=$c.Runbook-match'S018'-and$c.Runbook-match'S043'-and$c.Runbook-match'OUT OF SCOPE';Add-R V014 Boundaries $boundary 'RBAC/general policy and live enforcement boundaries are documented.'
Add-R V015 Maturity $false 'Placeholder exceptions and repository-native rules require future lab evidence.' $true
$ts=(Get-Date).ToString('s');$overall=if($fails){'FAIL'}else{'PASS'};$end="[$overall] Kubernetes manifest policy (StaticEvidence): $fails critical failure(s), $warns warning(s).";Write-Host $end;@('S044 Kubernetes Manifest Policy Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+($res|ForEach-Object{"[$($_.Status)] $($_.Id) $($_.Name)"})+@('',$end,'No kubectl, cluster, policy engine, or mutation operation occurred.')|Set-Content $log -Encoding UTF8
@('# Kubernetes Manifest Policy Validation Summary','',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required file check result: **$(if($missing.Count-eq0){'PASS'}else{'FAIL'})**","- Command safety result: **$(if($cmd){'PASS'}else{'FAIL'})**","- Rule set result: **$(if($rules){'PASS'}else{'FAIL'})**","- Compliant manifest result: **$(if($compliant){'PASS'}else{'FAIL'})**","- Violation manifest result: **$(if($violation){'PASS'}else{'FAIL'})**","- Exception manifest result: **$(if($exception){'PASS'}else{'FAIL'})**","- Service exposure result: **$(if($exposure){'PASS'}else{'FAIL'})**","- Evidence result: **$(if($ev-and$final){'PASS'}else{'FAIL'})**","- Manifest/mapping result: **$(if($manifest){'PASS'}else{'FAIL'})**","- Kubeconfig safety result: **$(if($kube.Count-eq0){'PASS'}else{'FAIL'})**","- Secret-safety result: **$(if(-not$ip-and-not$domain-and-not$secret){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**")|Set-Content $summary -Encoding UTF8;if($fails){exit 1}
