$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L4-failure-recovery\S037-security-rule-misconfiguration-validation'
$p=@{Runbook=Join-Path $root 'runbooks\security-rule-misconfiguration-validation.md';Commands=Join-Path $root 'runbooks\security-rule-misconfiguration-commands.example.md';Criteria=Join-Path $root 'security-baseline\security-rule-misconfiguration-criteria.example.md';Decision=Join-Path $root 'security-baseline\security-rule-rollback-decision-matrix.example.md';Policy=Join-Path $root 'policy\security-rule-misconfiguration-policy.example.md';Pre=Join-Path $e 'logs\pre-change-security-rules.sample.txt';Event=Join-Path $e 'logs\security-rule-misconfiguration-event.sample.txt';Detection=Join-Path $e 'logs\misconfiguration-detection.sample.txt';Impact=Join-Path $e 'logs\exposure-impact-assessment.sample.txt';Rollback=Join-Path $e 'logs\rollback-action.sample.txt';Post=Join-Path $e 'logs\post-rollback-security-rules.sample.txt';Validation=Join-Path $e 'logs\security-rule-validation-summary.sample.txt'}
$log=Join-Path $e 'logs\security-rule-misconfiguration-validation.log';$summary=Join-Path $e 'configs\security-rule-misconfiguration-summary.md';New-Item -ItemType Directory -Force -Path (Split-Path $log),(Split-Path $summary)|Out-Null
$rs=[System.Collections.Generic.List[object]]::new();$ls=[System.Collections.Generic.List[string]]::new();$fail=0;$warn=0
function Add-R([string]$Id,[string]$Name,[string]$Result,[string]$Detail){if($Result-eq'FAIL'){$script:fail++};if($Result-eq'WARN'){$script:warn++};$x="[$Result] $Id ${Name}: $Detail";Write-Host $x;$script:ls.Add($x)|Out-Null;$script:rs.Add([pscustomobject]@{Id=$Id;Name=$Name;Result=$Result;Detail=$Detail})|Out-Null};function T([string]$x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 'Required artifacts' $(if($missing.Count-eq 0){'PASS'}else{'FAIL'}) 'Five baselines and seven samples are required.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$terms=@('<cloud-provider>','<security-rule-id-placeholder>','<security-group-placeholder>','<nsg-placeholder>','<openstack-security-group-placeholder>','<kubernetes-network-policy-placeholder>','<source-cidr-placeholder>','<approved-source-cidr-placeholder>','<restricted-admin-cidr-placeholder>','<bastion-cidr-placeholder>','<service-port-placeholder>','<rollback-change-id-placeholder>','<evidence-path>');$boundaries=@('Automatic blocking','SOAR','WAF','IDS/IPS','EDR','Production emergency-change automation');Add-R V002 'Runbook placeholders and exclusions' $(if(@(($terms+$boundaries)|Where-Object{$c.Runbook-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'Required placeholders and excluded response capabilities must be explicit.'
$types=@('SSH exposed to unrestricted source','Database port exposed to unrestricted source','Kubernetes API exposed to unrestricted source','Internal service exposed publicly','Azure NSG Any-to-Any allow rule','OpenStack security group broad ingress rule','Kubernetes NetworkPolicy allow-all ingress placeholder','Egress any-any exception placeholder','Missing description / change reference','Missing rollback evidence');Add-R V003 'Misconfiguration criteria matrix' $(if(@($types|Where-Object{$c.Criteria-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'All ten required misconfiguration types are required.'
$cases=@('Critical public admin exposure','Critical public DB exposure','Public internal API exposure','Temporary maintenance exception','Approved bastion-only SSH','Approved service-to-service access','Missing owner','Missing expiry','Missing rollback evidence');Add-R V004 'Rollback decision matrix' $(if(@($cases|Where-Object{$c.Decision-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'All nine decision cases are required.'
$policyFields=@('owner','reason','expiry','approval','change reference','rollback evidence');$policyReady=@($policyFields|Where-Object{$c.Policy-notmatch[regex]::Escape($_)}).Count-eq 0-and$c.Policy-match'Admin ports must not be open'-and$c.Policy-match'Database ports must not be open'-and$c.Policy-match'Internal service ports must not be publicly exposed';Add-R V005 'Policy requirements' $(if($policyReady){'PASS'}else{'FAIL'}) 'Temporary exception metadata and exposure prohibitions are required.'
$commandScope=$c.Commands-match'Cloud modification commands are \*\*OUT OF SCOPE\*\*'-and$c.Commands-match'Firewall modification commands are \*\*OUT OF SCOPE\*\*'-and$c.Commands-match'kubectl apply.*OUT OF SCOPE'-and$c.Commands-match'Rollback is represented by sanitized evidence';Add-R V006 'Command reference scope boundary' $(if($commandScope){'PASS'}else{'FAIL'}) 'Modification commands must be out of scope and rollback evidence-only.'
$pre=$c.Pre-match'<bastion-cidr-placeholder>'-and$c.Pre-match'<application-subnet-placeholder>'-and$c.Pre-match'<internal-service-cidr-placeholder>'-and$c.Pre-match'Least_Privilege:\s*confirmed-placeholder';Add-R V007 'Pre-change least privilege evidence' $(if($pre){'PASS'}else{'FAIL'}) 'Bastion, application subnet, internal-service, and least-privilege placeholders are required.'
$event=$c.Event-match'MANUAL MISCONFIGURATION SAMPLE'-and([regex]::Matches($c.Event,'<unrestricted-source-placeholder>')).Count-ge 2-and$c.Event-match'Execution_By_Validator:\s*false';Add-R V008 'Manual misconfiguration evidence' $(if($event){'PASS'}else{'FAIL'}) 'Misconfiguration must be explicit, manual, and not validator-executed.'
$detected=$c.Detection-match'unsafe-rule-detected-placeholder'-and$c.Detection-match'<unsafe-source-placeholder>'-and$c.Detection-match'<unsafe-port-placeholder>'-and$c.Detection-match'(?i)Severity:\s*(?:Critical|High)-placeholder';Add-R V009 'Misconfiguration detection evidence' $(if($detected){'PASS'}else{'FAIL'}) 'Unsafe rule/source/port and severity are required.'
$impact=$c.Impact-match'Affected_Surface:'-and$c.Impact-match'<unauthorized-access-path-placeholder>'-and$c.Impact-match'rollback-required-placeholder'-and$c.Impact-match'Production_Data_Stored:\s*false';Add-R V010 'Exposure impact assessment' $(if($impact){'PASS'}else{'FAIL'}) 'Surface, potential path, rollback need, and no-production-data marker are required.'
$rollback=$c.Rollback-match'MANUAL ROLLBACK SAMPLE'-and$c.Rollback-match'<approved-source-cidr-placeholder>'-and$c.Rollback-match'removed-placeholder'-and$c.Rollback-match'Execution_By_Validator:\s*false';Add-R V011 'Manual rollback evidence' $(if($rollback){'PASS'}else{'FAIL'}) 'Rollback must be explicit, manual, and not validator-executed.'
$post=$c.Post-match'<bastion-cidr-placeholder>'-and$c.Post-match'<application-subnet-placeholder>'-and$c.Post-match'<internal-service-cidr-placeholder>'-and$c.Post-match'Unrestricted_Admin_Exposure:\s*false'-and$c.Post-match'Unrestricted_DB_Exposure:\s*false';$unsafePost=$c.Post-match'<unrestricted-source-placeholder>|Any-to-Any|allow-all|broad ingress';Add-R V012 'Post-rollback safe state' $(if($post-and-not$unsafePost){'PASS'}else{'FAIL'}) 'Restricted sources and false unrestricted exposure are required.'
$validated=$c.Validation-match'Misconfiguration_Detected:\s*true'-and$c.Validation-match'Rollback_Evidence_Present:\s*true'-and$c.Validation-match'Post_Rollback_State:\s*safe'-and$c.Validation-match'Real_Cloud_Changes_Performed:\s*false';Add-R V013 'Final validation summary evidence' $(if($validated){'PASS'}else{'FAIL'}) 'Detected, rollback-present, safe, and no-real-change judgments are required.'
$expiryPlaceholder=$c.Event-match'Temporary_Exception_Expiry:\s*<expiry-placeholder>';Add-R V014 'Temporary exception expiry maturity' $(if($expiryPlaceholder){'WARN'}else{'PASS'}) 'Placeholder-only expiry requires a future authorized value before a real exception.'
$idPatterns='(?i)\b(?:vpc|vnet|subnet|sg|nsg|proj|tenant|subscription|account)-[0-9a-f]{6,}\b|\b\d{12}\b|\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b';$ip=[regex]::Matches($all,'(?<![A-Za-z0-9<])(?:\d{1,3}\.){3}\d{1,3}(?:/\d{1,2})?(?![A-Za-z0-9>])').Count;$domain=[regex]::Matches($all,'(?i)(?<![A-Za-z0-9<.-])(?:[a-z0-9-]+\.)+[a-z]{2,}(?![A-Za-z0-9>.-])').Count;$secret=$all-match'(?im)^\s*(?:token|password|secret|authorization|cookie|api[_-]?key)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$safe=$all-notmatch$idPatterns-and$ip-eq 0-and$domain-eq 0-and-not$secret;Add-R V015 'Identifier network and secret safety' $(if($safe){'PASS'}else{'FAIL'}) 'No concrete cloud ID, address/CIDR, domain, credential, key, or secret may exist.'
$script=Get-Content $PSCommandPath -Raw;$unsafeExecution=$script-match'(?im)^\s*(?:aws|az|openstack|kubectl|iptables|firewall-cmd|netsh|terraform)\b';Add-R V016 'Execution safety boundary' $(if(-not$unsafeExecution){'PASS'}else{'FAIL'}) 'Validator must not call cloud, Kubernetes, firewall, or Terraform commands.'
$ts=(Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK');$overall=if($fail-eq 0){'PASS'}else{'FAIL'};$final="[$overall] Security rule misconfiguration (StaticEvidence): $fail critical failure(s), $warn warning(s).";Write-Host $final;@('SNSD Multi-Cloud Ops - S037 Security Rule Misconfiguration Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+@($ls)+@('', $final,'No cloud, Kubernetes, firewall, Terraform, routing, or network command was executed; no real identifier or network value was stored.')|Set-Content $log -Encoding UTF8
$out=@('# Security Rule Misconfiguration Summary','', '- Scenario: S037-security-rule-misconfiguration-validation',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required file check result: **$(if($missing.Count-eq 0){'PASS'}else{'FAIL'})**","- Policy requirement check result: **$(if($policyReady){'PASS'}else{'FAIL'})**","- Pre-change least privilege evidence result: **$(if($pre){'PASS'}else{'FAIL'})**","- Manual misconfiguration evidence result: **$(if($event){'PASS'}else{'FAIL'})**","- Detection evidence result: **$(if($detected){'PASS'}else{'FAIL'})**","- Impact assessment evidence result: **$(if($impact){'PASS'}else{'FAIL'})**","- Rollback evidence result: **$(if($rollback){'PASS'}else{'FAIL'})**","- Post-rollback validation result: **$(if($post-and-not$unsafePost){'PASS'}else{'FAIL'})**","- Identifier / secret safety check result: **$(if($safe){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result | Detail |','|---|---|---|---|');foreach($r in $rs){$out+="| $($r.Id) | $($r.Name) | $($r.Result) | $($r.Detail) |"};$out|Set-Content $summary -Encoding UTF8;if($fail-gt 0){exit 1};exit 0
