param(
    [switch]$LiveKubectl,
    [switch]$LiveHttp,
    [string]$Namespace,
    [string]$DeploymentName,
    [string]$ServiceName,
    [string]$ApiHealthUrl
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$root = Split-Path -Parent $PSScriptRoot
$evidenceRoot = Join-Path $root "evidence\L4-failure-recovery\S032-api-service-failure-validation"
$runbook = Join-Path $root "runbooks\api-service-failure-validation.md"
$commands = Join-Path $root "runbooks\api-service-failure-commands.example.md"
$criteria = Join-Path $root "runbooks\api-service-failure-criteria.example.md"
$samples = @{
    PrePods=Join-Path $evidenceRoot "logs\pre-failure-api-pods.sample.txt"; PreEndpoints=Join-Path $evidenceRoot "logs\pre-failure-api-endpoints.sample.txt"; PreHttp=Join-Path $evidenceRoot "logs\pre-failure-api-http.sample.txt"
    Injection=Join-Path $evidenceRoot "logs\api-failure-injection-event.sample.txt"; Detection=Join-Path $evidenceRoot "logs\api-failure-detection.sample.txt"; PostPods=Join-Path $evidenceRoot "logs\post-recovery-api-pods.sample.txt"
    PostEndpoints=Join-Path $evidenceRoot "logs\post-recovery-api-endpoints.sample.txt"; PostHttp=Join-Path $evidenceRoot "logs\post-recovery-api-http.sample.txt"; Rollout=Join-Path $evidenceRoot "logs\api-rollout-status.sample.txt"
}
$logPath=Join-Path $evidenceRoot "logs\api-service-failure-validation.log"
$summaryPath=Join-Path $evidenceRoot "configs\api-service-failure-summary.md"
New-Item -ItemType Directory -Force -Path (Split-Path $logPath),(Split-Path $summaryPath)|Out-Null
$results=[System.Collections.Generic.List[object]]::new();$lines=[System.Collections.Generic.List[string]]::new();$failures=0;$warnings=0
function Add-Result([string]$Id,[string]$Name,[string]$Result,[string]$Detail){if($Result-eq'FAIL'){$script:failures++};if($Result-eq'WARN'){$script:warnings++};$line="[$Result] $Id ${Name}: $Detail";Write-Host $line;$script:lines.Add($line)|Out-Null;$script:results.Add([pscustomobject]@{Id=$Id;Name=$Name;Result=$Result;Detail=$Detail})|Out-Null}
function Read-Text([string]$Path){if(Test-Path -LiteralPath $Path -PathType Leaf){Get-Content -LiteralPath $Path -Raw}else{''}}
$required=@($runbook,$commands,$criteria)+@($samples.Values);$missing=@($required|Where-Object{-not(Test-Path -LiteralPath $_ -PathType Leaf)})
Add-Result V001 'Required artifacts' $(if($missing.Count-eq 0){'PASS'}else{'FAIL'}) $(if($missing.Count-eq 0){'Three baselines and nine samples exist.'}else{'Required artifacts are missing.'})
$content=@{};foreach($key in $samples.Keys){$content[$key]=Read-Text $samples[$key]};$runbookText=Read-Text $runbook;$commandText=Read-Text $commands;$criteriaText=Read-Text $criteria;$combined=(@($runbookText,$commandText,$criteriaText)+@($content.Values))-join"`n"
$terms=@('<namespace>','<api-deployment-name>','<api-service-name>','<api-pod-name>','<replacement-api-pod-name>','<api-health-endpoint-placeholder>','<api-url-placeholder>','<expected-status-code>','<failure-status-code>','<recovery-time-threshold-seconds>','<evidence-path>','Static','LiveKubectl','LiveHttp');$missingTerms=@($terms|Where-Object{$runbookText-notmatch[regex]::Escape($_)})
Add-Result V002 'Workflow and placeholders' $(if($missingTerms.Count-eq 0){'PASS'}else{'FAIL'}) $(if($missingTerms.Count-eq 0){'Controlled workflow, modes, and placeholders are documented.'}else{'Runbook terms are incomplete.'})
$manualBoundary=$commandText-match'MANUAL FAULT INJECTION ONLY'-and$commandText-match'kubectl delete pod <api-pod-name>'-and$commandText-match'kubectl scale deployment/<api-deployment-name> --replicas=0'-and$commandText-match'never executed by the validator'-and$commandText-match'disposable'
Add-Result V003 'Manual fault boundary' $(if($manualBoundary){'PASS'}else{'FAIL'}) $(if($manualBoundary){'Delete and scale-to-zero are manual disposable-lab references only.'}else{'Manual fault boundary is incomplete.'})
$phases=@('Pre-failure API deployment state','Pre-failure API pod readiness','Pre-failure Service endpoint availability','Pre-failure API HTTP health response','Manual failure injection event','API failure detection','Endpoint loss or degraded endpoint state','HTTP failure response','Recovery action placeholder','Post-recovery pod readiness','Post-recovery Service endpoint availability','Post-recovery API HTTP health response','Recovery time threshold');$criteriaReady=@($phases|Where-Object{$criteriaText-notmatch[regex]::Escape($_)}).Count-eq 0
Add-Result V004 'Failure criteria matrix' $(if($criteriaReady){'PASS'}else{'FAIL'}) $(if($criteriaReady){'All required phases exist.'}else{'Criteria phases are incomplete.'})
$prePods=$content.PrePods-match'\s1/1\s' -and $content.PrePods-match'\sRunning\s';Add-Result V005 'Pre-failure Pod evidence' $(if($prePods){'PASS'}else{'FAIL'}) 'Running and Ready 1/1 is required.'
$preEp=$content.PreEndpoints-match'<api-pod-ip-placeholder>:8080' -and $content.PreEndpoints-notmatch'(?i)<none>';Add-Result V006 'Pre-failure endpoint evidence' $(if($preEp){'PASS'}else{'FAIL'}) 'A symbolic non-empty endpoint is required.'
$preHttp=$content.PreHttp-match'HTTP/1\.1 200 OK';Add-Result V007 'Pre-failure HTTP evidence' $(if($preHttp){'PASS'}else{'FAIL'}) 'A healthy status is required.'
$injection=$content.Injection-match'MANUAL FAULT INJECTION SAMPLE'-and$content.Injection-match'Execution_By_Validator:\s*false';Add-Result V008 'Manual injection evidence' $(if($injection){'PASS'}else{'FAIL'}) 'The event must be explicitly manual and not validator-executed.'
$detection=$content.Detection-match'(?i)(5\d\d|timeout|connection refused|unavailable|<none>)';Add-Result V009 'Failure detection evidence' $(if($detection){'PASS'}else{'FAIL'}) 'An expected failure signal is required.'
$postPods=$content.PostPods-match'sample-api-placeholder-klmno' -and $content.PostPods-match'\s1/1\s' -and $content.PostPods-match'\sRunning\s';Add-Result V010 'Post-recovery Pod evidence' $(if($postPods){'PASS'}else{'FAIL'}) 'A replacement Running/Ready Pod is required.'
$postEp=$content.PostEndpoints-match'<api-pod-ip-placeholder>:8080' -and $content.PostEndpoints-notmatch'(?i)<none>';Add-Result V011 'Post-recovery endpoint evidence' $(if($postEp){'PASS'}else{'FAIL'}) 'A non-empty endpoint is required.'
$postHttp=$content.PostHttp-match'HTTP/1\.1 200 OK';Add-Result V012 'Post-recovery HTTP evidence' $(if($postHttp){'PASS'}else{'FAIL'}) 'A healthy recovered status is required.'
$rollout=$content.Rollout-match'successfully rolled out';Add-Result V013 'Rollout evidence' $(if($rollout){'PASS'}else{'FAIL'}) 'Successful rollout is required.'
$badPost='(?i)CrashLoopBackOff|ImagePullBackOff|ErrImagePull|\bFailed\b|\bPending\b|\bUnknown\b|\b0/1\b|HTTP/1\.1 5\d\d|timeout|connection refused|<none>';$postSafe=($content.PostPods+"`n"+$content.PostEndpoints+"`n"+$content.PostHttp)-notmatch$badPost;Add-Result V014 'Recovered-state health' $(if($postSafe){'PASS'}else{'FAIL'}) 'No unhealthy recovered-state indicator may remain.'
$elapsed=[regex]::Match($content.Injection,'(?im)^Recovery_Elapsed_Seconds:\s*(\d+(?:\.\d+)?)\s*$');Add-Result V015 'Recovery timing' $(if($elapsed.Success){'PASS'}else{'WARN'}) $(if($elapsed.Success){'Elapsed time is available.'}else{'Elapsed time is not measured; threshold compliance is unproven.'})
$forbiddenFiles=@(Get-ChildItem $root -Recurse -File -Force -ErrorAction SilentlyContinue|Where-Object{$_.FullName-notmatch'[\\/]\.git[\\/]'-and$_.Name-match'(?i)(^|\.)kubeconfig($|\.)|service[-_]?account.*token|\.(?:crt|cer|pem|key|p12|pfx)$'});$realIp=[regex]::Matches($combined,'(?<![A-Za-z0-9<])(?:\d{1,3}\.){3}\d{1,3}(?![A-Za-z0-9>])').Count;$realUrl=[regex]::Matches($combined,'(?i)https?://(?!<)[^\s"`]+').Count;$secret=$combined-match'(?im)^\s*(?:token|password|secret|authorization|cookie|api[_-]?key)\s*[:=]\s*(?!["'']?<)\S+'-or$combined-match'-----BEGIN (?:CERTIFICATE|(?:[A-Z ]+ )?PRIVATE KEY)-----';$safe=$forbiddenFiles.Count-eq 0-and$realIp-eq 0-and$realUrl-eq 0-and-not$secret
Add-Result V016 'Endpoint and secret safety' $(if($safe){'PASS'}else{'FAIL'}) 'No real endpoint/address or sensitive artifact may exist.'
$scriptText=Get-Content $PSCommandPath -Raw;$requiredArgs=@('\$deploymentArgs=@\("get","deployment",\$DeploymentName,"-n",\$Namespace\)','\$podArgs=@\("get","pods","-n",\$Namespace\)','\$serviceArgs=@\("get","service",\$ServiceName,"-n",\$Namespace\)','\$endpointArgs=@\("get","endpoints",\$ServiceName,"-n",\$Namespace\)','\$rolloutArgs=@\("rollout","status","deployment/\$DeploymentName","-n",\$Namespace\)');$argSafe=@($requiredArgs|Where-Object{$scriptText-notmatch$_}).Count-eq 0;$destructive=$scriptText-match'(?im)^\s*(?:&\s*)?kubectl\s+(?:delete|apply|patch|edit|scale|restart|cordon|drain|taint)\b';Add-Result V017 'Execution safety boundary' $(if($argSafe-and-not$destructive){'PASS'}else{'FAIL'}) 'Only five read-only kubectl argument sets may execute.'
$mode=@();if($LiveKubectl){$mode+='LiveKubectl'};if($LiveHttp){$mode+='LiveHttp'};if($mode.Count-eq 0){$mode+='Static'};$modeName=$mode-join'+'
if($LiveKubectl){$live='PASS';if([string]::IsNullOrWhiteSpace($Namespace)-or[string]::IsNullOrWhiteSpace($DeploymentName)-or[string]::IsNullOrWhiteSpace($ServiceName)){$live='FAIL'}else{$kubectl=Get-Command kubectl -CommandType Application -ErrorAction SilentlyContinue;if($null-eq$kubectl){$live='FAIL'}else{$deploymentArgs=@("get","deployment",$DeploymentName,"-n",$Namespace);$podArgs=@("get","pods","-n",$Namespace);$serviceArgs=@("get","service",$ServiceName,"-n",$Namespace);$endpointArgs=@("get","endpoints",$ServiceName,"-n",$Namespace);$rolloutArgs=@("rollout","status","deployment/$DeploymentName","-n",$Namespace);$outs=@();foreach($args in @($deploymentArgs,$podArgs,$serviceArgs,$endpointArgs,$rolloutArgs)){$o=@(&$kubectl.Source @args 2>&1);if($LASTEXITCODE-ne 0){$live='FAIL'};$outs+=,$o};if(($outs[1]-join"`n")-notmatch'\s\d+/\d+\s+Running\s'){$live='FAIL'};if(($outs[3]-join"`n")-match'(?i)<none>'){$live='FAIL'};if(($outs[4]-join"`n")-notmatch'successfully rolled out'){$live='FAIL'}}};Add-Result V018 'LiveKubectl read-only state' $live 'Raw cluster output is not stored.'}
if($LiveHttp){$http='PASS';$detail='Sanitized status recorded.';if([string]::IsNullOrWhiteSpace($ApiHealthUrl)){$http='FAIL';$detail='ApiHealthUrl is required.'}else{try{$response=Invoke-WebRequest -Uri $ApiHealthUrl -Method Head -UseBasicParsing -TimeoutSec 10;$status=[int]$response.StatusCode;if($status-in 200,204){$detail="Healthy status $status."}elseif($status-in 401,403){$http='WARN';$detail="Status $status may require authentication."}elseif($status-ge 500){$http='FAIL';$detail="Unhealthy 5xx status."}}catch{$http='FAIL';$detail='Connection or request failed; no response body was stored.'}};Add-Result V019 'LiveHttp read-only health' $http $detail}
$timestamp=(Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK');$overall=if($failures-eq 0){'PASS'}else{'FAIL'};$final="[$overall] API service failure ($modeName): $failures critical failure(s), $warnings warning(s).";Write-Host $final
@("SNSD Multi-Cloud Ops - S032 API Service Failure Validation","Generated: $timestamp","Validation mode: $modeName","")+@($lines)+@("",$final,"No credentials, response bodies, raw live output, or destructive action were stored or executed.")|Set-Content $logPath -Encoding UTF8
$summary=@('# API Service Failure Summary','',"- Scenario: S032-api-service-failure-validation","- Generated: $timestamp","- Validation mode: **$modeName**","- Required file check result: **$(if($missing.Count-eq 0){'PASS'}else{'FAIL'})**","- Pre-failure API pod evidence result: **$(if($prePods){'PASS'}else{'FAIL'})**","- Pre-failure endpoint evidence result: **$(if($preEp){'PASS'}else{'FAIL'})**","- Pre-failure HTTP evidence result: **$(if($preHttp){'PASS'}else{'FAIL'})**","- Manual fault injection evidence result: **$(if($injection){'PASS'}else{'FAIL'})**","- Failure detection evidence result: **$(if($detection){'PASS'}else{'FAIL'})**","- Post-recovery API pod evidence result: **$(if($postPods){'PASS'}else{'FAIL'})**","- Post-recovery endpoint evidence result: **$(if($postEp){'PASS'}else{'FAIL'})**","- Post-recovery HTTP evidence result: **$(if($postHttp){'PASS'}else{'FAIL'})**","- Rollout status result: **$(if($rollout){'PASS'}else{'FAIL'})**","- Recovery time threshold documentation result: **$(if($runbookText-match'<recovery-time-threshold-seconds>'){'PASS'}else{'FAIL'})**","- Secret-safety check result: **$(if($safe){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result | Detail |','|---|---|---|---|');foreach($r in $results){$summary+="| $($r.Id) | $($r.Name) | $($r.Result) | $($r.Detail.Replace('|','\|')) |"};$summary|Set-Content $summaryPath -Encoding UTF8
if($failures-gt 0){exit 1};exit 0
