$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L5-governance-intelligent-ops\S042-terraform-drift-remediation-validation'
$p=@{Runbook=Join-Path $root 'runbooks\terraform-drift-remediation-validation.md';Commands=Join-Path $root 'runbooks\terraform-drift-remediation-commands.example.md';Criteria=Join-Path $root 'terraform\terraform-drift-remediation-criteria.example.md';DecisionMatrix=Join-Path $root 'terraform\terraform-drift-remediation-decision-matrix.example.md';Policy=Join-Path $root 'policy\terraform-drift-remediation-policy.example.md';RevertJson=Join-Path $root 'terraform\drift-remediation-plan-revert.example.json';CodifyJson=Join-Path $root 'terraform\drift-remediation-plan-codify.example.json';PostJson=Join-Path $root 'terraform\drift-remediation-plan-post-remediation-no-drift.example.json';Detection=Join-Path $e 'logs\drift-detection-reference.sample.txt';Decision=Join-Path $e 'logs\remediation-decision.sample.txt';Approval=Join-Path $e 'logs\remediation-approval.sample.txt';Plan=Join-Path $e 'logs\remediation-plan.sample.txt';Rollback=Join-Path $e 'logs\remediation-rollback-plan.sample.txt';Post=Join-Path $e 'logs\post-remediation-no-drift.sample.txt';Final=Join-Path $e 'logs\terraform-remediation-final-summary.sample.txt';Manifest=Join-Path $e 'configs\terraform-drift-remediation-manifest.sample.yml'}
$log=Join-Path $e 'logs\terraform-drift-remediation-validation.log';$summary=Join-Path $e 'configs\terraform-drift-remediation-validation-summary.md';New-Item -ItemType Directory -Force -Path (Split-Path $log),(Split-Path $summary)|Out-Null
$rs=[System.Collections.Generic.List[object]]::new();$ls=[System.Collections.Generic.List[string]]::new();$fail=0;$warn=0
function Add-R([string]$Id,[string]$Name,[string]$Result,[string]$Detail){if($Result-eq'FAIL'){$script:fail++};if($Result-eq'WARN'){$script:warn++};$x="[$Result] $Id ${Name}: $Detail";Write-Host $x;$script:ls.Add($x)|Out-Null;$script:rs.Add([pscustomobject]@{Id=$Id;Name=$Name;Result=$Result;Detail=$Detail})|Out-Null};function T([string]$x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 'Required artifacts' $(if($missing.Count-eq 0){'PASS'}else{'FAIL'}) 'Five baselines, three JSON examples, seven log samples, and one manifest are required.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$terms=@('terraform apply','terraform destroy','terraform import','terraform state rm','terraform state mv','terraform force-unlock');$commandSafe=$c.Commands-match'MANUAL LAB EXECUTION ONLY'-and$c.Commands-match'MANUAL LOCAL ROLLBACK EXAMPLE ONLY'-and$c.Commands-match'OUT OF SCOPE'-and@($terms|Where-Object{$c.Commands-notmatch[regex]::Escape($_)}).Count-eq 0;Add-R V002 'Command safety boundary' $(if($commandSafe){'PASS'}else{'FAIL'}) 'Plan is manual-only and apply/destroy/import/state mutation are out of scope.'
$detect=$c.Detection-match'Source_Scenario:\s*S041'-and$c.Detection-match'Drift_Detection_ID'-and$c.Detection-match'Drift_Status'-and$c.Detection-match'Drift_Severity'-and$c.Detection-match'Affected_Resource';Add-R V003 'S041 drift reference' $(if($detect){'PASS'}else{'FAIL'}) 'S041 detection ID, status, severity, and resource are required.'
$options=@('REVERT_TO_TERRAFORM','CODIFY_APPROVED_CHANGE','INVESTIGATE_ONLY','REJECT_CHANGE','ACCEPT_DOCUMENTED_EXCEPTION');$decision=$c.Decision-match'Remediation_Option:\s*(?:REVERT_TO_TERRAFORM|CODIFY_APPROVED_CHANGE|INVESTIGATE_ONLY|REJECT_CHANGE|ACCEPT_DOCUMENTED_EXCEPTION)'-and$c.Decision-match'Operational_Reason'-and$c.Decision-match'Risk_Assessment'-and$c.Decision-match'Real_Cloud_Operation_Performed:\s*false';Add-R V004 'Remediation decision' $(if($decision){'PASS'}else{'FAIL'}) 'Approved option, reason, risk, and no-real-operation marker are required.'
$severityRequiresApproval=$c.Detection-match'(?i)Drift_Severity:\s*(?:Critical|High|Medium)';$approval=$c.Approval-match'Approval_ID:\s*<approval-id-placeholder>'-and$c.Approval-match'Approval_Status'-and$c.Approval-match'Approver_Role'-and$c.Approval-match'Approval_Scope'-and$c.Approval-match'Real_Person_Or_Organization_Data:\s*false';Add-R V005 'Approval evidence' $(if(-not$severityRequiresApproval-or$approval){'PASS'}else{'FAIL'}) 'Medium/High/Critical drift requires sanitized approval evidence.'
$plan=$c.Plan-match'Remediation_Change_ID'-and$c.Plan-match'Affected_Resource'-and$c.Plan-match'Expected_Value'-and$c.Plan-match'Remediated_Value'-and$c.Plan-match'Terraform_Plan'-and$c.Plan-match'Remediation_Executed_By_Validation_Script:\s*false';Add-R V006 'Non-executed remediation plan' $(if($plan){'PASS'}else{'FAIL'}) 'Change/resource/value/plan fields and no-execution marker are required.'
$rollback=$c.Rollback-match'Rollback_Change_ID'-and$c.Rollback-match'Rollback_Condition'-and$c.Rollback-match'Rollback_Owner_Role'-and$c.Rollback-match'Rollback_Command'-and$c.Rollback-match'MANUAL ROLLBACK ONLY';Add-R V007 'Rollback plan evidence' $(if($rollback){'PASS'}else{'FAIL'}) 'Rollback ID, condition, owner, command placeholder, and manual-only marker are required.'
$post=$c.Post-match'Exit_Code:\s*0'-and$c.Post-match'No changes\. Infrastructure matches the configuration\.'-and$c.Post-match'NO_DRIFT'-and$c.Post-match'REMEDIATION_VALIDATED';Add-R V008 'Post-remediation no-drift evidence' $(if($post){'PASS'}else{'FAIL'}) 'Exit code 0, NO_DRIFT, and REMEDIATION_VALIDATED are required.'
$final=$c.Final-match'S041_Drift_Reference_Present:\s*true'-and$c.Final-match'Remediation_Decision_Present:\s*true'-and$c.Final-match'Approval_Evidence_Present:\s*true'-and$c.Final-match'Rollback_Evidence_Present:\s*true'-and$c.Final-match'Post_Remediation_No_Drift_Evidence_Present:\s*true'-and$c.Final-match'Terraform_Execution_Performed_By_Validation_Script:\s*false'-and$c.Final-match'REMEDIATION_VALIDATED';Add-R V009 'Final remediation summary' $(if($final){'PASS'}else{'FAIL'}) 'All decision/approval/rollback/post checks, no execution, and final judgment are required.'
$mf=@('remediation_validation_id','drift_detection_scenario: S041','drift_detection_id','terraform_environment','cloud_provider','affected_resource','drift_severity','remediation_option','remediation_change_id','approval_required','approval_id','rollback_required','rollback_change_id','post_remediation_status','post_remediation_plan_exit_code','policy_validation_scenario: S043','cost_guardrail_scenario: S045','evidence_reference','final_judgment');$manifest=@($mf|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq 0;Add-R V010 'Remediation manifest and mappings' $(if($manifest){'PASS'}else{'FAIL'}) 'All fields plus S041/S043/S045 links are required.'
$jsonOk=$true;try{$j1=$c.RevertJson|ConvertFrom-Json;$j2=$c.CodifyJson|ConvertFrom-Json;$j3=$c.PostJson|ConvertFrom-Json;$jsonOk=$j1.remediation_option-eq'REVERT_TO_TERRAFORM'-and$j2.remediation_option-eq'CODIFY_APPROVED_CHANGE'-and$j3.final_judgment-eq'REMEDIATION_VALIDATED'-and$j3.drift_status-eq'NO_DRIFT'}catch{$jsonOk=$false};Add-R V011 'Sanitized remediation JSON examples' $(if($jsonOk){'PASS'}else{'FAIL'}) 'Revert, codify, and post-remediation examples must parse and match judgments.'
$policyTerms=@('S041','Critical drift requires approval','rollback evidence','must not be silently accepted','state files','plan binaries','S043','S045');$policy=@($policyTerms|Where-Object{$c.Policy-notmatch[regex]::Escape($_)}).Count-eq 0;Add-R V012 'Remediation policy requirements' $(if($policy){'PASS'}else{'FAIL'}) 'Detection, approval, rollback, artifact, policy, and cost boundaries are required.'
$riskyFiles=@(Get-ChildItem $root -Recurse -Force -ErrorAction SilentlyContinue|Where-Object{($_.FullName-notlike"$root\.git*")-and(($_.PSIsContainer-and$_.Name-eq'.terraform')-or(-not$_.PSIsContainer-and($_.Name-match'^(?:terraform\.tfstate(?:\.backup)?|terraform\.tfvars|.+\.auto\.tfvars)$'-or$_.Extension-match'^\.(?:tfplan|plan)$')))});Add-R V013 'Terraform state and artifact safety' $(if($riskyFiles.Count-eq 0){'PASS'}else{'FAIL'}) 'No tfstate, tfvars, plan binary, or .terraform directory may exist.'
$ip=$all-match'(?<![\w<])(?:\d{1,3}\.){3}\d{1,3}(?:/\d{1,2})?(?![\w>])';$id=$all-match'(?i)\b(?:vpc|sg|subnet|vnet)-[0-9a-f]{6,}\b'-or$all-match'\b\d{12}\b'-or$all-match'\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b';$secret=$all-match'(?im)^\s*(?:password|token|secret|access_key|secret_key|client_secret|authorization)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$safe=-not$ip-and-not$id-and-not$secret;Add-R V014 'Identifier network and secret safety' $(if($safe){'PASS'}else{'FAIL'}) 'No real IDs, IP/CIDR, credential, token, key, backend value, or secret may exist.'
$script=Get-Content $PSCommandPath -Raw;$exec=$script-match'(?im)^\s*(?:terraform|aws|az|openstack)\s+';$claim=$c.Plan-match'Remediation_Executed_By_Validation_Script:\s*true'-or$c.Final-match'Terraform_Execution_Performed_By_Validation_Script:\s*true';Add-R V015 'No execution or automatic remediation' $(if(-not$exec-and-not$claim){'PASS'}else{'FAIL'}) 'Validator must not run Terraform/cloud CLIs or claim remediation execution.'
$placeholder=$c.Decision-match'<operational-reason-placeholder>'-or$c.Approval-match'<approval-id-placeholder>'-or$c.Rollback-match'<rollback-condition-placeholder>';Add-R V016 'Evidence maturity' $(if($placeholder){'WARN'}else{'PASS'}) 'Placeholder-only decision, approval, or rollback data requires future disposable-lab proof.'
$ts=(Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK');$overall=if($fail-eq 0){'PASS'}else{'FAIL'};$finalLine="[$overall] Terraform drift remediation (StaticEvidence): $fail critical failure(s), $warn warning(s).";Write-Host $finalLine;@('SNSD Multi-Cloud Ops - S042 Terraform Drift Remediation Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+@($ls)+@('',$finalLine,'No Terraform, cloud API, remote state, provider credential, or remediation operation occurred.')|Set-Content $log -Encoding UTF8
$out=@('# Terraform Drift Remediation Validation Summary','', '- Scenario: S042-terraform-drift-remediation-validation',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required file check result: **$(if($missing.Count-eq 0){'PASS'}else{'FAIL'})**","- S041 drift reference result: **$(if($detect){'PASS'}else{'FAIL'})**","- Remediation decision result: **$(if($decision){'PASS'}else{'FAIL'})**","- Approval evidence result: **$(if($approval){'PASS'}else{'FAIL'})**","- Remediation plan result: **$(if($plan){'PASS'}else{'FAIL'})**","- Rollback plan result: **$(if($rollback){'PASS'}else{'FAIL'})**","- Post-remediation no-drift result: **$(if($post){'PASS'}else{'FAIL'})**","- Manifest result: **$(if($manifest){'PASS'}else{'FAIL'})**","- S043 policy mapping result: **$(if($manifest){'PASS'}else{'FAIL'})**","- S045 cost mapping result: **$(if($manifest){'PASS'}else{'FAIL'})**","- Terraform state safety result: **$(if($riskyFiles.Count-eq 0){'PASS'}else{'FAIL'})**","- Secret-safety check result: **$(if($safe){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result | Detail |','|---|---|---|---|');foreach($r in $rs){$out+="| $($r.Id) | $($r.Name) | $($r.Result) | $($r.Detail) |"};$out|Set-Content $summary -Encoding UTF8;if($fail-gt 0){exit 1};exit 0
