$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e="$root\evidence\L5-governance-intelligent-ops\S045-cost-guardrail-validation"
$p=@{Runbook="$root\runbooks\cost-guardrail-validation.md";Commands="$root\runbooks\cost-guardrail-commands.example.md";Rules="$root\cost-governance\cost-guardrail-rules.example.yml";Criteria="$root\cost-governance\cost-guardrail-criteria.example.md";Decision="$root\cost-governance\cost-guardrail-decision-matrix.example.md";ImpactMatrix="$root\cost-governance\cost-impact-classification-matrix.example.md";Policy="$root\policy\cost-guardrail-policy.example.md";InputPass="$root\cost-governance\cost-evaluation-input-pass.example.json";InputFail="$root\cost-governance\cost-evaluation-input-fail.example.json";InputException="$root\cost-governance\cost-evaluation-input-exception.example.json";Load="$e\logs\cost-rule-load.sample.txt";Pass="$e\logs\cost-evaluation-pass.sample.txt";Fail="$e\logs\cost-evaluation-fail.sample.txt";Exception="$e\logs\cost-exception-approval.sample.txt";Impact="$e\logs\cost-impact-classification.sample.txt";Cleanup="$e\logs\cost-cleanup-mapping.sample.txt";Final="$e\logs\cost-guardrail-final-summary.sample.txt";Manifest="$e\configs\cost-guardrail-validation-manifest.sample.yml"}
$log="$e\logs\cost-guardrail-validation.log";$summary="$e\configs\cost-guardrail-validation-summary.md";$res=@();$fails=0;$warns=0;function Add-R($id,$name,$ok,$detail,$warning=$false){$s=if($ok){'PASS'}elseif($warning){'WARN'}else{'FAIL'};if($s-eq'FAIL'){$script:fails++};if($s-eq'WARN'){$script:warns++};Write-Host "[$s] $id ${name}: $detail";$script:res+=@([pscustomobject]@{Id=$id;Name=$name;Status=$s})};function T($x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 Artifacts ($missing.Count-eq0) 'Required cost-governance artifacts exist.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$cmd=$c.Commands-match'MANUAL LAB EVIDENCE CONVERSION ONLY'-and$c.Commands-match'PLACEHOLDER ONLY'-and$c.Commands-match'does not run Terraform'-and$c.Commands-match'does not.*query billing'-and$c.Commands-match'does not.*require an external cost tool';Add-R V002 Commands $cmd 'Terraform/billing commands are manual/placeholders and no external tool is required.'
$judgments=@('COST_GUARDRAIL_PASS','COST_GUARDRAIL_FAIL','COST_GUARDRAIL_WARNING','COST_EXCEPTION_APPROVED','COST_EVIDENCE_INCOMPLETE','COST_REVIEW_REQUIRED');$exc=@('exception_id','owner','reason','expiry','approval_id','rollback_condition','evidence_reference');$domains=@('monthly-budget','daily-budget','incremental-delta','terraform-change','resource-cost','cleanup');$rules=@($judgments+$exc+$domains|Where-Object{$c.Rules-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V003 Rules $rules 'Judgments, exceptions, and guardrail domains are complete.'
$json=$true;try{$a=$c.InputPass|ConvertFrom-Json;$b=$c.InputFail|ConvertFrom-Json;$d=$c.InputException|ConvertFrom-Json;$json=$a.final_expected_judgment-eq'COST_GUARDRAIL_PASS'-and$b.final_expected_judgment-eq'COST_GUARDRAIL_FAIL'-and$d.final_expected_judgment-eq'COST_EXCEPTION_APPROVED'}catch{$json=$false};Add-R V004 Inputs $json 'Pass/fail/exception inputs are parseable and consistent.'
$load=$c.Load-match'Cost_Guardrail_Rules_Loaded'-and$c.Load-match'Real_Billing_API_Queried:\s*false'-and$c.Load-match'External_Cost_Tool_Required:\s*false';Add-R V005 Load $load 'Rules loaded with no billing API or external tool.'
$pass=$c.Pass-match'Within_Threshold:\s*true-placeholder'-and$c.Pass-match'COST_GUARDRAIL_PASS'-and$c.Pass-notmatch'Threshold_Exceeded';Add-R V006 Pass $pass 'Within-threshold pass evidence is required.'
$failEv=$c.Fail-match'Monthly_Threshold_Exceeded'-and$c.Fail-match'Incremental_Cost_Delta_Exceeded'-and$c.Fail-match'Missing_Cleanup_Mapping'-and$c.Fail-match'COST_GUARDRAIL_FAIL';Add-R V007 Fail $failEv 'Threshold and cleanup violations must fail.'
$exception=@($exc|Where-Object{$c.Exception-notmatch[regex]::Escape($_)}).Count-eq0-and$c.Exception-match'COST_EXCEPTION_APPROVED';Add-R V008 Exception $exception 'Complete approved exception required.'
$impact=$c.Impact-match'Resource_Category'-and$c.Impact-match'Cost_Signal'-and$c.Impact-match'Risk_Level'-and$c.Impact-match'Required_Action';Add-R V009 Impact $impact 'Cost impact classification fields required.'
$cleanup=$c.Cleanup-match'Cleanup_Candidate'-and$c.Cleanup-match'Cleanup_Scenario:\s*S046'-and$c.Cleanup-match'Real_Resource_Deletion_Performed:\s*false';Add-R V010 Cleanup $cleanup 'S046 mapping and no deletion required.'
$final=$c.Final-match'Cost_Guardrail_Rules_Validated:\s*true'-and$c.Final-match'Real_Billing_API_Queried:\s*false'-and$c.Final-match'Real_Cloud_Operation_Performed:\s*false'-and$c.Final-match'COST_GUARDRAIL_PASS';Add-R V011 Summary $final 'Rules validated with no billing/cloud operation.'
$mf=@('cost_guardrail_validation_id','guardrail_rule_set_reference','pass_input_reference','fail_input_reference','exception_input_reference','monthly_threshold_placeholder','daily_threshold_placeholder','incremental_delta_threshold_placeholder','cost_impact_classification_reference','drift_detection_scenario: S041','drift_remediation_scenario: S042','policy_as_code_scenario: S043','resource_cleanup_scenario: S046','final_evidence_report_scenario: S050','evidence_reference','final_judgment');$manifest=@($mf|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V012 Manifest $manifest 'All fields and S041/S042/S043/S046/S050 mappings required.'
$policy=@('monthly cost evidence','Incremental cost delta','Critical cost increases','owner, reason, expiry, approval, rollback condition, and evidence reference','S046','real billing data','invoices','billing exports','cloud bills','S050');$policyOk=@($policy|Where-Object{$c.Policy-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V013 Policy $policyOk 'Cost, exception, cleanup, artifact, and reporting rules required.'
$risky=@(Get-ChildItem $root -Recurse -Force -ErrorAction SilentlyContinue|Where-Object{($_.FullName-notlike"$root\.git*")-and(($_.PSIsContainer-and$_.Name-eq'.terraform')-or(-not$_.PSIsContainer-and($_.Name-match'^(?:terraform\.tfstate(?:\.backup)?|terraform\.tfvars|.+\.auto\.tfvars)$'-or$_.Name-match'(?i)(?:invoice|billing-export|cloud-bill|cost-and-usage-report)' -or$_.Extension-match'^\.(?:tfplan|plan)$')))});Add-R V014 ArtifactSafety ($risky.Count-eq0) 'No Terraform state/plan or real billing artifact.'
$ip=$all-match'(?<![\w<])(?:\d{1,3}\.){3}\d{1,3}(?![\w>])';$id=$all-match'\b\d{12}\b';$secret=$all-match'(?im)^\s*(?:password|token|secret|access_key|billing_api_key|authorization)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$src=Get-Content $PSCommandPath -Raw;$exec=$src-match'(?im)^\s*(?:terraform|aws|az|openstack)\s+';Add-R V015 Safety (-not$ip-and-not$id-and-not$secret-and-not$exec) 'No identifiers, networks, credentials, keys, or external execution.'
Add-R V016 Maturity $false 'Cost, threshold, and exception values are placeholder-only.' $true
$ts=(Get-Date).ToString('s');$overall=if($fails){'FAIL'}else{'PASS'};$end="[$overall] Cost guardrail (StaticEvidence): $fails critical failure(s), $warns warning(s).";Write-Host $end;@('S045 Cost Guardrail Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+($res|ForEach-Object{"[$($_.Status)] $($_.Id) $($_.Name)"})+@('',$end,'No Terraform, billing/cloud API, external cost tool, budget, optimization, or cleanup operation occurred.')|Set-Content $log -Encoding UTF8
@('# Cost Guardrail Validation Summary','',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required file result: **$(if($missing.Count-eq0){'PASS'}else{'FAIL'})**","- Command safety: **$(if($cmd){'PASS'}else{'FAIL'})**","- Rule set: **$(if($rules){'PASS'}else{'FAIL'})**","- Pass/fail/exception: **$(if($pass-and$failEv-and$exception){'PASS'}else{'FAIL'})**","- Impact classification: **$(if($impact){'PASS'}else{'FAIL'})**","- Cleanup mapping: **$(if($cleanup){'PASS'}else{'FAIL'})**","- Manifest/mappings: **$(if($manifest){'PASS'}else{'FAIL'})**","- Artifact/secret safety: **$(if($risky.Count-eq0-and-not$ip-and-not$id-and-not$secret){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**")|Set-Content $summary -Encoding UTF8;if($fails){exit 1}
