$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e="$root/evidence/L5-governance-intelligent-ops/S050-final-evidence-report-generation-validation"
$p=@{Runbook="$root/runbooks/final-evidence-report-generation-validation.md";Commands="$root/runbooks/final-evidence-report-generation-commands.example.md";Template="$root/docs/final-evidence-report-template.example.md";Model="$root/docs/final-evidence-report-generation-model.md";Criteria="$root/docs/final-evidence-report-criteria.example.md";Decision="$root/docs/final-evidence-report-decision-matrix.example.md";Policy="$root/policy/final-evidence-report-generation-policy.example.md";SampleReport="$e/configs/final-evidence-report.sample.md";SampleJson="$e/configs/final-evidence-report-summary.sample.json";Manifest="$e/configs/final-evidence-report-generation-manifest.sample.yml";GeneratedReport="$e/configs/final-evidence-report.generated.md";GeneratedJson="$e/configs/final-evidence-report-summary.generated.json";TemplateLog="$e/logs/final-report-template-load.sample.txt";Discovery="$e/logs/final-report-input-discovery.sample.txt";Generation="$e/logs/final-report-generation.sample.txt";Sections="$e/logs/final-report-section-validation.sample.txt";Coverage="$e/logs/final-report-scenario-coverage.sample.txt";Evidence="$e/logs/final-report-evidence-coverage.sample.txt";Risk="$e/logs/final-report-risk-summary.sample.txt";Safety="$e/logs/final-report-safety-scan.sample.txt";Final="$e/logs/final-report-final-summary.sample.txt";Generator="$root/tools/generate-final-evidence-report.ps1"}
$log="$e/logs/final-evidence-report-validation.log";$summary="$e/configs/final-evidence-report-validation-summary.md";$res=@();$fails=0;$warns=0
function Add-R($id,$name,$ok,$detail,$warning=$false){$s=if($ok){'PASS'}elseif($warning){'WARN'}else{'FAIL'};if($s-eq'FAIL'){$script:fails++};if($s-eq'WARN'){$script:warns++};Write-Host "[$s] $id ${name}: $detail";$script:res+=[pscustomobject]@{Id=$id;Name=$name;Status=$s}};function T($x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 Artifacts ($missing.Count-eq0) 'Required S050 inputs, samples, generator, and generated outputs exist.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$generation=$c.Generation-match'Final_Evidence_Report_Generated:\s*true'-and$c.Generation-match'Summary_JSON_Generated:\s*true'-and$c.Generation-match'Live_Infrastructure_Query_Performed:\s*false'-and(Test-Path $p.GeneratedReport)-and(Test-Path $p.GeneratedJson);Add-R V002 Generation $generation 'Markdown/JSON generated locally with no live query.'
$sections=@('Report Metadata','Executive Summary','Platform Scope','Architecture Summary','Scenario Coverage Summary','L1 Foundation Validation Summary','L2 Security Baseline Validation Summary','L3 Service Operations Validation Summary','L4 Failure Recovery Validation Summary','L5 Governance Intelligent Ops Summary','Evidence Status Summary','Validation Script Summary','Risk Register Summary','Excluded Scope Confirmation','Safety Boundary Confirmation','Intelligent Ops Summary','Final Operational Judgment','Appendix A: Scenario Status Matrix','Appendix B: Evidence Status Matrix','Appendix C: Validation Commands','Appendix D: Generated Evidence References');$sectionOk=@($sections|Where-Object{$c.GeneratedReport-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V003 Sections $sectionOk 'All required report sections exist.'
$ids=@(1..50|ForEach-Object{'S{0:D3}'-f$_});$coverage=@($ids|Where-Object{$c.GeneratedReport-notmatch[regex]::Escape($_)}).Count-eq0-and$c.GeneratedReport-match'total_scenarios: 50';Add-R V004 Coverage $coverage 'S001-S050 and total count 50 are present.'
$jsonOk=$false;$judgment='';try{$j=$c.GeneratedJson|ConvertFrom-Json;$fields=@('final_report_id','report_generated_at','repository_name','platform_name','total_scenarios','scenario_range','l1_scenario_count','l2_scenario_count','l3_scenario_count','l4_scenario_count','l5_scenario_count','implemented_scenarios','validated_scenarios','ready_evidence_count','partial_evidence_count','blocked_scenario_count','risk_count','excluded_scope_confirmed','safety_boundary_confirmed','intelligent_ops_scenarios','final_judgment','evidence_reference');$judgment=$j.final_judgment;$jsonOk=@($fields|Where-Object{$_-notin$j.PSObject.Properties.Name}).Count-eq0-and$j.total_scenarios-eq50-and$judgment-in@('FINAL_REPORT_READY','FINAL_REPORT_WARNING','FINAL_REPORT_INCOMPLETE','FINAL_REPORT_BLOCKED','FINAL_REPORT_INVALID')}catch{$jsonOk=$false};Add-R V005 SummaryJson $jsonOk 'Generated summary JSON is complete and has a valid judgment.'
$mf=@('final_evidence_report_generation_validation_id','final_report_id','report_template_reference','report_output_reference','report_summary_reference','scenario_status_matrix_reference','evidence_status_matrix_reference','progress_tracker_reference','implementation_log_reference','risk_register_reference','scope_lock_reference','excluded_scope_reference','scenario_coverage_count: 50','expected_scenario_count: 50','l1_range','l2_range','l3_range','l4_range','l5_range','intelligent_ops_range','validation_mode','evidence_reference','final_judgment');$manifest=@($mf|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V006 Manifest $manifest 'Manifest fields and coverage ranges exist.'
$samples=$c.TemplateLog-match'Required_Report_Sections_Validated:\s*true'-and$c.Discovery-match'Scenario_Status_Matrix_Discovered:\s*true'-and$c.Sections-match'Required_Sections_Present:\s*true'-and$c.Coverage-match'Expected_Scenario_Count:\s*50'-and$c.Coverage-match'S001_S050_Accounted_For:\s*true'-and$c.Evidence-match'Evidence_Matrix_Discovered:\s*true'-and$c.Final-match'FINAL_REPORT_READY';Add-R V007 SampleEvidence $samples 'Template, discovery, sections, coverage, evidence, and final samples are consistent.'
$refs=@('docs/scenario-status-matrix.md','docs/evidence-status-matrix.md','docs/risk-register.md','docs/excluded-scope.md');$refsOk=@($refs|Where-Object{$c.GeneratedReport-notmatch[regex]::Escape($_)}).Count-eq0-and$c.GeneratedReport-match'Risk Register Summary'-and$c.GeneratedReport-match'Excluded Scope Confirmation';Add-R V008 GovernanceRefs $refsOk 'Status matrices, risk register, and excluded scope are referenced.'
$safetyTerms=@('No_Secrets_Detected: true','No_Real_Identifiers_Detected: true','No_Production_Logs_Detected: true','No_Production_Metrics_Detected: true','No_Billing_Data_Detected: true','No_SIEM_Wazuh_EDR_Data_Detected: true','No_Packet_Payloads_Detected: true');$safetyOk=@($safetyTerms|Where-Object{$c.Safety-notmatch[regex]::Escape($_)}).Count-eq0-and$c.GeneratedReport-match'No live infrastructure validation was performed by S050'-and$c.GeneratedReport-match'No secrets or real identifiers are included';Add-R V009 SafetyBoundary $safetyOk 'Safety sample and no-live/no-secret statements are present.'
$intelligent=@('S047','S048','S049','Intelligent Ops Summary');$intelligentOk=@($intelligent|Where-Object{$c.GeneratedReport-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V010 IntelligentOps $intelligentOk 'S047-S049 are summarized.'
$unsafeClaim=$c.GeneratedReport-match'(?i)(?<!not )production audit certification|(?<!not )compliance certification|external audit approved|production compliance approved';$policy=$c.Policy-match'prohibited'-and$c.Policy-match'External audit certification'-and$c.Policy-match'production compliance approval';Add-R V011 CertificationSafety (-not$unsafeClaim-and$policy) 'No affirmative certification or audit-approval claim exists.'
$risky=@(Get-ChildItem $root -Recurse -Force -ErrorAction SilentlyContinue|Where-Object{$_.FullName-notlike"$root/.git*"-and(($_.PSIsContainer-and$_.Name-eq'.terraform')-or(-not$_.PSIsContainer-and($_.Name-match'^(?:terraform\.tfstate(?:\.backup)?|terraform\.tfvars|.+\.auto\.tfvars|kubeconfig|clouds\.yaml|openrc)$'-or$_.Extension-match'(?i)^\.(pem|key|p12|pfx|pcap|pcapng)$')))});Add-R V012 ArtifactSafety ($risky.Count-eq0) 'No state, tfvars, kube/cloud config, key, or packet artifact exists.'
$ip=$all-match'(?<![\w<])(?:\d{1,3}\.){3}\d{1,3}(?![\w>])';$url=$all-match'(?i)https?://(?!<)[a-z0-9]';$id=$all-match'\b\d{12}\b'-or$all-match'(?i)\b(?:i|vol|vpc|sg|subnet)-[0-9a-f]{6,}\b';$secret=$all-match'(?im)^\s*(?:password|token|secret|access_key|api_key|authorization)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';Add-R V013 SensitiveSafety (-not$ip-and-not$url-and-not$id-and-not$secret) 'No real network, identifier, credential, key, or secret detected.'
$src=Get-Content $PSCommandPath -Raw;$exec=$src-match'(?im)^\s*(?:terraform|kubectl|aws|az|openstack|curl|Invoke-RestMethod|Invoke-WebRequest)\s+';Add-R V014 ExecutionSafety (-not$exec-and$c.Commands-match'LOCAL REPOSITORY CHECK ONLY') 'Validator executes no external or infrastructure command.'
$final=$c.Final-match'Report_Generated:\s*true'-and$c.Final-match'Scenario_Coverage_Validated:\s*true'-and$c.Final-match'Safety_Scan_Passed:\s*true'-and$c.Final-match'FINAL_REPORT_READY';Add-R V015 FinalSummary $final 'Sample final summary is ready.'
Add-R V016 Maturity ($judgment-eq'FINAL_REPORT_READY') "Generated judgment is $judgment; Markdown/JSON and sample evidence remain portfolio-grade." ($judgment-ne'FINAL_REPORT_READY')
$ts=(Get-Date).ToString('s');$overall=if($fails){'FAIL'}else{'PASS'};$end="[$overall] Final evidence report (StaticEvidence): $fails critical failure(s), $warns warning(s).";Write-Host $end;@('S050 Final Evidence Report Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+($res|ForEach-Object{"[$($_.Status)] $($_.Id) $($_.Name)"})+@('',$end,'No live infrastructure, external reporting, PDF/PPTX, certification, or remediation operation occurred.')|Set-Content $log -Encoding UTF8
@('# Final Evidence Report Validation Summary','',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required files: **$(if($missing.Count-eq0){'PASS'}else{'FAIL'})**","- Generation/output/JSON: **$(if($generation-and$jsonOk){'PASS'}else{'FAIL'})**","- Manifest/coverage/L1-L5: **$(if($manifest-and$coverage-and$sectionOk){'PASS'}else{'FAIL'})**","- Risk/excluded scope: **$(if($refsOk){'PASS'}else{'FAIL'})**","- Safety/Intelligent Ops/certification: **$(if($safetyOk-and$intelligentOk-and-not$unsafeClaim){'PASS'}else{'FAIL'})**","- Artifact/secret safety: **$(if($risky.Count-eq0-and-not$ip-and-not$url-and-not$id-and-not$secret){'PASS'}else{'FAIL'})**","- Final judgment: **$overall** (report: **$judgment**)")|Set-Content $summary -Encoding UTF8;if($fails){exit 1}
