param([switch]$LiveHttp,[string]$LoadBalancerUrl,[string]$BackendAUrl,[string]$BackendBUrl)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L4-failure-recovery\S035-load-balancer-failure-validation'
$p=@{Runbook=Join-Path $root 'runbooks\load-balancer-failure-validation.md';Commands=Join-Path $root 'runbooks\load-balancer-failure-commands.example.md';Criteria=Join-Path $root 'runbooks\load-balancer-failure-criteria.example.md';Metrics=Join-Path $root 'observability\prometheus\load-balancer-failure-metrics.example.md';Matrix=Join-Path $root 'traffic-management\load-balancer-failure-response-matrix.example.md';PreLb=Join-Path $e 'logs\pre-failure-lb-health.sample.txt';PreBackends=Join-Path $e 'logs\pre-failure-backend-health.sample.txt';Injection=Join-Path $e 'logs\lb-failure-injection-event.sample.txt';Down=Join-Path $e 'logs\lb-down-detection.sample.txt';Impact=Join-Path $e 'logs\client-facing-impact.sample.txt';During=Join-Path $e 'logs\backend-direct-health-during-lb-failure.sample.txt';Recovery=Join-Path $e 'logs\lb-recovery-event.sample.txt';PostLb=Join-Path $e 'logs\post-recovery-lb-health.sample.txt';PostClient=Join-Path $e 'logs\post-recovery-client-health.sample.txt';Bypass=Join-Path $e 'logs\manual-bypass-rollback-validation.sample.txt'}
$log=Join-Path $e 'logs\load-balancer-failure-validation.log';$summary=Join-Path $e 'configs\load-balancer-failure-summary.md';New-Item -ItemType Directory -Force -Path (Split-Path $log),(Split-Path $summary)|Out-Null
$rs=[System.Collections.Generic.List[object]]::new();$ls=[System.Collections.Generic.List[string]]::new();$fail=0;$warn=0
function Add-R([string]$Id,[string]$Name,[string]$Result,[string]$Detail){if($Result-eq'FAIL'){$script:fail++};if($Result-eq'WARN'){$script:warn++};$x="[$Result] $Id ${Name}: $Detail";Write-Host $x;$script:ls.Add($x)|Out-Null;$script:rs.Add([pscustomobject]@{Id=$Id;Name=$Name;Result=$Result;Detail=$Detail})|Out-Null};function T([string]$x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 'Required artifacts' $(if($missing.Count-eq 0){'PASS'}else{'FAIL'}) 'Five baselines and ten samples are required.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$terms=@('<load-balancer-url-placeholder>','<backend-a-url-placeholder>','<backend-b-url-placeholder>','<load-balancer-service-placeholder>','<manual-bypass-placeholder>','<rollback-to-normal-path-placeholder>','<recovery-time-threshold-seconds>','<evidence-path>','MANUAL FAULT INJECTION ONLY','MANUAL RECOVERY ACTION ONLY','Static','LiveHttp');Add-R V002 'Runbook workflow and modes' $(if(@($terms|Where-Object{$c.Runbook-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'Placeholders, manual boundaries, and modes are required.'
$phases=@('Pre-failure load balancer health','Pre-failure backend health','Manual load balancer failure injection','Load balancer down detection','Client-facing service impact','Backend direct availability during LB failure','Manual recovery action','Post-recovery load balancer health','Post-recovery client-facing service health','Manual bypass / rollback validation','Recovery time threshold');Add-R V003 'Criteria matrix' $(if(@($phases|Where-Object{$c.Criteria-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'All eleven phases are required.';$refs=$c.Commands-match'MANUAL FAULT INJECTION ONLY'-and$c.Commands-match'MANUAL RECOVERY ACTION ONLY'-and$c.Commands-match'systemctl stop <load-balancer-service-placeholder>'-and$c.Commands-match'systemctl start <load-balancer-service-placeholder>'-and$c.Commands-match'never executes';Add-R V004 'Manual command boundary' $(if($refs){'PASS'}else{'FAIL'}) 'Stop/start must be manual-only.'
$metric=$c.Metrics-match'<load-balancer-target-placeholder>'-and$c.Metrics-match'<backend-target-placeholder>';$matrix=$c.Matrix-match'LB 503'-and$c.Matrix-match'backends 200 while LB down';Add-R V005 'Metrics and response matrix' $(if($metric-and$matrix){'PASS'}else{'FAIL'}) 'Symbolic metrics and failure isolation response are required.'
$preLb=$c.PreLb-match'HTTP/1\.1 200 OK'-and$c.PreLb-match'healthy-placeholder';$preBackends=([regex]::Matches($c.PreBackends,'HTTP/1\.1 200 OK')).Count-eq 2;Add-R V006 'Pre-failure LB and backend health' $(if($preLb-and$preBackends){'PASS'}else{'FAIL'}) 'LB and two backends must be healthy.';$injection=$c.Injection-match'MANUAL FAULT INJECTION SAMPLE'-and$c.Injection-match'Execution_By_Validator:\s*false';Add-R V007 'Manual failure injection' $(if($injection){'PASS'}else{'FAIL'}) 'Failure event must be manual-only.'
$down=$c.Down-match'(?i)(HTTP/1\.1 5\d\d|connection refused|timeout|inactive-placeholder)';$impact=$c.Impact-match'failed-placeholder'-and$c.Impact-match'503-placeholder'-and$c.Impact-match'Response_Body_Stored:\s*false';Add-R V008 'LB down and client impact' $(if($down-and$impact){'PASS'}else{'FAIL'}) 'Entrypoint and client failure evidence are required.';$during=([regex]::Matches($c.During,'HTTP/1\.1 200 OK')).Count-eq 2-and$c.During-match'remains-available-placeholder';Add-R V009 'Backend isolation during LB failure' $(if($during){'PASS'}else{'FAIL'}) 'Both direct backends must remain healthy.'
$recovery=$c.Recovery-match'MANUAL RECOVERY ACTION SAMPLE'-and$c.Recovery-match'Execution_By_Validator:\s*false';Add-R V010 'Manual recovery event' $(if($recovery){'PASS'}else{'FAIL'}) 'Recovery must be manual-only.';$post=$c.PostLb-match'HTTP/1\.1 200 OK'-and$c.PostLb-match'restored-placeholder'-and$c.PostClient-match'HTTP/1\.1 200 OK'-and$c.PostClient-match'restored-placeholder';Add-R V011 'Post-recovery LB and client health' $(if($post){'PASS'}else{'FAIL'}) 'LB and client path must be restored.';$bypass=$c.Bypass-match'Manual_Bypass:\s*documented-placeholder'-and$c.Bypass-match'Rollback_To_Normal_LB_Path:\s*documented-placeholder'-and$c.Bypass-match'DNS_Or_Routing_Value_Stored:\s*false';Add-R V012 'Manual bypass and rollback' $(if($bypass){'PASS'}else{'FAIL'}) 'Both steps must be documented without real routing data.'
$elapsed=[regex]::Match($c.Injection,'(?im)^Recovery_Elapsed_Seconds:\s*(\d+(?:\.\d+)?)\s*$');Add-R V013 'Recovery timing' $(if($elapsed.Success){'PASS'}else{'WARN'}) 'Unmeasured time leaves threshold compliance unproven.';$badPost=($c.PostLb+"`n"+$c.PostClient)-match'(?i)(5\d\d|timeout|connection refused|failed|inactive)';Add-R V014 'Recovered-state failure indicators' $(if(-not$badPost){'PASS'}else{'FAIL'}) 'No failure signal may remain after recovery.'
$ip=[regex]::Matches($all,'(?<![A-Za-z0-9<])(?:\d{1,3}\.){3}\d{1,3}(?![A-Za-z0-9>])').Count;$url=[regex]::Matches($all,'(?i)https?://(?!<)[^\s"`]+').Count;$domain=[regex]::Matches($all,'(?i)(?<![A-Za-z0-9<.-])(?:[a-z0-9-]+\.)+[a-z]{2,}(?![A-Za-z0-9>.-])').Count;$secret=$all-match'(?im)^\s*(?:token|password|secret|authorization|cookie|api[_-]?key)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$safe=$ip-eq 0-and$url-eq 0-and$domain-eq 0-and-not$secret;Add-R V015 'Endpoint and secret safety' $(if($safe){'PASS'}else{'FAIL'}) 'No real URL/domain/address, credential, cookie, key, or secret may exist.'
$script=Get-Content $PSCommandPath -Raw;$unsafe=$script-match'(?im)^\s*(?:systemctl|service|nginx|kubectl|terraform|ansible-playbook)\b';Add-R V016 'Execution safety boundary' $(if(-not$unsafe){'PASS'}else{'FAIL'}) 'Validator must not change services, traffic, DNS, routing, or infrastructure.'
$mode=if($LiveHttp){'LiveHttp'}else{'Static'};if($LiveHttp){$live='PASS';$detail='Status-only HEAD checks completed.';if([string]::IsNullOrWhiteSpace($LoadBalancerUrl)-or[string]::IsNullOrWhiteSpace($BackendAUrl)-or[string]::IsNullOrWhiteSpace($BackendBUrl)){$live='FAIL';$detail='All three URLs are required.'}else{foreach($u in @($LoadBalancerUrl,$BackendAUrl,$BackendBUrl)){try{$res=Invoke-WebRequest -Uri $u -Method Head -UseBasicParsing -TimeoutSec 10;if([int]$res.StatusCode-notin 200,204){$live='FAIL'}}catch{$live='FAIL'}}};Add-R V017 'LiveHttp read-only state' $live $detail}
$ts=(Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK');$overall=if($fail-eq 0){'PASS'}else{'FAIL'};$final="[$overall] Load balancer failure ($mode): $fail critical failure(s), $warn warning(s).";Write-Host $final;@('SNSD Multi-Cloud Ops - S035 Load Balancer Failure Validation',"Generated: $ts","Validation mode: $mode",'')+@($ls)+@('', $final,'No service/configuration/DNS/routing change, credential, raw response, or response body was stored or executed.')|Set-Content $log -Encoding UTF8
$out=@('# Load Balancer Failure Summary','', '- Scenario: S035-load-balancer-failure-validation',"- Generated: $ts","- Validation mode: **$mode**","- Required file check result: **$(if($missing.Count-eq 0){'PASS'}else{'FAIL'})**","- Pre-failure health result: **$(if($preLb-and$preBackends){'PASS'}else{'FAIL'})**","- Manual fault result: **$(if($injection){'PASS'}else{'FAIL'})**","- Failure/impact result: **$(if($down-and$impact){'PASS'}else{'FAIL'})**","- Backend isolation result: **$(if($during){'PASS'}else{'FAIL'})**","- Recovery result: **$(if($recovery-and$post){'PASS'}else{'FAIL'})**","- Bypass/rollback result: **$(if($bypass){'PASS'}else{'FAIL'})**","- Secret-safety result: **$(if($safe){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result | Detail |','|---|---|---|---|');foreach($r in $rs){$out+="| $($r.Id) | $($r.Name) | $($r.Result) | $($r.Detail) |"};$out|Set-Content $summary -Encoding UTF8;if($fail-gt 0){exit 1};exit 0
