$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L5-governance-intelligent-ops\S043-policy-as-code-validation'
$p=@{Runbook=Join-Path $root 'runbooks\policy-as-code-validation.md';Commands=Join-Path $root 'runbooks\policy-as-code-commands.example.md';Schema=Join-Path $root 'policy\policy-as-code-rule-schema.example.yml';Rules=Join-Path $root 'policy\policy-as-code-rules.example.yml';Criteria=Join-Path $root 'policy\policy-as-code-criteria.example.md';Decision=Join-Path $root 'policy\policy-as-code-decision-matrix.example.md';InputPass=Join-Path $root 'policy\policy-evaluation-input-pass.example.json';InputFail=Join-Path $root 'policy\policy-evaluation-input-fail.example.json';InputException=Join-Path $root 'policy\policy-evaluation-input-exception.example.json';Load=Join-Path $e 'logs\policy-rule-load.sample.txt';Pass=Join-Path $e 'logs\policy-evaluation-pass.sample.txt';Fail=Join-Path $e 'logs\policy-evaluation-fail.sample.txt';Exception=Join-Path $e 'logs\policy-exception-approval.sample.txt';Class=Join-Path $e 'logs\policy-violation-classification.sample.txt';Final=Join-Path $e 'logs\policy-final-summary.sample.txt';Manifest=Join-Path $e 'configs\policy-as-code-validation-manifest.sample.yml'}
$log=Join-Path $e 'logs\policy-as-code-validation.log';$summary=Join-Path $e 'configs\policy-as-code-validation-summary.md';New-Item -ItemType Directory -Force -Path (Split-Path $log),(Split-Path $summary)|Out-Null
$results=@();$fail=0;$warn=0;function Add-R($id,$name,$ok,$detail,$warning=$false){$status=if($ok){'PASS'}elseif($warning){'WARN'}else{'FAIL'};if($status-eq'FAIL'){$script:fail++};if($status-eq'WARN'){$script:warn++};$line="[$status] $id ${name}: $detail";Write-Host $line;$script:results+=@([pscustomobject]@{Id=$id;Name=$name;Status=$status;Detail=$detail})};function T($x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 'Required artifacts' ($missing.Count-eq0) 'Six baselines, three inputs, six logs, and one manifest are required.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$cmd=$c.Commands-match'OPTIONAL EXAMPLES ONLY'-and$c.Commands-match'not required'-and$c.Commands-match'MANUAL LAB EVIDENCE CONVERSION ONLY'-and$c.Commands-match'OUT OF SCOPE';Add-R V002 'Command safety' $cmd 'OPA/Conftest optional, Terraform conversion manual, live checks out of scope.'
$judgments=@('POLICY_PASS','POLICY_FAIL','POLICY_WARNING','POLICY_EXCEPTION_APPROVED','POLICY_EVIDENCE_INCOMPLETE','POLICY_REVIEW_REQUIRED');$exc=@('exception_id','owner','reason','expiry','approval_id','rollback_condition','evidence_reference');$schema=@($judgments+$exc|Where-Object{$c.Schema-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V003 'Rule schema' $schema 'All judgments and exception fields are required.'
$domains=@('terraform','security','backup','restore','cost','kubernetes-placeholder');$maps=@('S041','S042','S044','S045','S046');$rules=@($domains+$maps|Where-Object{$c.Rules-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V004 'Rule set and mappings' $rules 'Required domains and scenario mappings are required.'
$json=$true;try{$jp=$c.InputPass|ConvertFrom-Json;$jf=$c.InputFail|ConvertFrom-Json;$je=$c.InputException|ConvertFrom-Json;$json=$jp.final_expected_judgment-eq'POLICY_PASS'-and$jf.final_expected_judgment-eq'POLICY_FAIL'-and$je.final_expected_judgment-eq'POLICY_EXCEPTION_APPROVED'}catch{$json=$false};Add-R V005 'Evaluation input JSON' $json 'Pass/fail/exception inputs must parse and have consistent expected judgments.'
$load=$c.Load-match'Policy_Rules_Loaded:\s*true-placeholder'-and$c.Load-match'External_Policy_Engine_Required:\s*false';Add-R V006 'Rule load evidence' $load 'Repository-native load and no external engine requirement are required.'
$pass=$c.Pass-match'Policy_Evaluation_Completed:\s*true'-and$c.Pass-match'Critical_Violation:\s*false'-and$c.Pass-match'High_Violation:\s*false'-and$c.Pass-match'POLICY_PASS';Add-R V007 'Pass evidence' $pass 'Pass sample must contain no critical/high violation.'
$failEv=$c.Fail-match'Critical_Violation_Detected'-and$c.Fail-match'Unsafe_Admin_Exposure'-and$c.Fail-match'Missing_Rollback_Evidence'-and$c.Fail-match'POLICY_FAIL';Add-R V008 'Fail evidence' $failEv 'Critical violation and POLICY_FAIL are required.'
$exception=@($exc|Where-Object{$c.Exception-notmatch[regex]::Escape($_)}).Count-eq0-and$c.Exception-match'POLICY_EXCEPTION_APPROVED';Add-R V009 'Exception evidence' $exception 'All exception fields and approved judgment are required.'
$class=$c.Class-match'Violation_ID'-and$c.Class-match'Severity'-and$c.Class-match'Affected_Policy'-and$c.Class-match'Affected_Resource'-and$c.Class-match'Required_Action'-and$c.Class-match'Related_Scenario';Add-R V010 'Violation classification' $class 'Violation, severity, policy/resource, action, and scenario are required.'
$final=$c.Final-match'Policy_Rules_Validated:\s*true'-and$c.Final-match'Pass_Sample_Validated:\s*true'-and$c.Final-match'Fail_Sample_Validated:\s*true'-and$c.Final-match'Exception_Sample_Validated:\s*true'-and$c.Final-match'Real_Cloud_Operation_Performed:\s*false'-and$c.Final-match'POLICY_PASS';Add-R V011 'Final summary' $final 'All samples validated, no cloud operation, and POLICY_PASS required.'
$mf=@('policy_validation_id','policy_domains','rule_set_reference','pass_input_reference','fail_input_reference','exception_input_reference','violation_count_placeholder','critical_violation_count_placeholder','exception_count_placeholder','drift_detection_scenario: S041','drift_remediation_scenario: S042','kubernetes_manifest_policy_scenario: S044','cost_guardrail_scenario: S045','resource_cleanup_scenario: S046','evidence_reference','final_judgment');$manifest=@($mf|Where-Object{$c.Manifest-notmatch[regex]::Escape($_)}).Count-eq0;Add-R V012 'Manifest and mappings' $manifest 'All fields and S041/S042/S044/S045/S046 mappings required.'
$risky=@(Get-ChildItem $root -Recurse -Force -ErrorAction SilentlyContinue|Where-Object{($_.FullName-notlike"$root\.git*")-and(($_.PSIsContainer-and$_.Name-eq'.terraform')-or(-not$_.PSIsContainer-and($_.Name-match'^(?:terraform\.tfstate(?:\.backup)?|terraform\.tfvars|.+\.auto\.tfvars)$'-or$_.Extension-match'^\.(?:tfplan|plan)$')))});Add-R V013 'Terraform artifact safety' ($risky.Count-eq0) 'No state, tfvars, plan binary, or .terraform directory.'
$ip=$all-match'(?<![\w<])(?:\d{1,3}\.){3}\d{1,3}(?:/\d{1,2})?(?![\w>])';$id=$all-match'\b\d{12}\b'-or$all-match'(?i)\b(?:vpc|sg|subnet|vnet)-[0-9a-f]{6,}\b';$secret=$all-match'(?im)^\s*(?:password|token|secret|access_key|authorization)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';Add-R V014 'Identifier and secret safety' (-not$ip-and-not$id-and-not$secret) 'No real IDs, networks, backend values, credentials, keys, or secrets.'
$src=Get-Content $PSCommandPath -Raw;$exec=$src-match'(?im)^\s*(?:terraform|opa|conftest|aws|az|openstack)\s+';Add-R V015 'Execution safety' (-not$exec) 'No Terraform, policy engine, or cloud CLI execution.'
$placeholder=$c.Exception-match'<expiry-placeholder>';$native=$c.Schema-match'SAMPLE / NON-PRODUCTION';Add-R V016 'Evidence maturity' (-not($placeholder-or$native)) 'Placeholder exceptions and repository-native syntax require future lab review.' $true
$ts=(Get-Date).ToString('s');$overall=if($fail-eq0){'PASS'}else{'FAIL'};$lines=$results|ForEach-Object{"[$($_.Status)] $($_.Id) $($_.Name): $($_.Detail)"};$end="[$overall] Policy as Code (StaticEvidence): $fail critical failure(s), $warn warning(s).";Write-Host $end;@('S043 Policy as Code Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+$lines+@('',$end,'No Terraform, OPA, Conftest, cloud CLI/API, or enforcement operation occurred.')|Set-Content $log -Encoding UTF8
$out=@('# Policy as Code Validation Summary','',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required file check result: **$(if($missing.Count-eq0){'PASS'}else{'FAIL'})**","- Command safety result: **$(if($cmd){'PASS'}else{'FAIL'})**","- Rule schema result: **$(if($schema){'PASS'}else{'FAIL'})**","- Rule set result: **$(if($rules){'PASS'}else{'FAIL'})**","- Pass sample result: **$(if($pass){'PASS'}else{'FAIL'})**","- Fail sample result: **$(if($failEv){'PASS'}else{'FAIL'})**","- Exception sample result: **$(if($exception){'PASS'}else{'FAIL'})**","- Violation classification result: **$(if($class){'PASS'}else{'FAIL'})**","- Manifest result: **$(if($manifest){'PASS'}else{'FAIL'})**","- Scenario mapping result: **$(if($manifest-and$rules){'PASS'}else{'FAIL'})**","- Terraform state safety result: **$(if($risky.Count-eq0){'PASS'}else{'FAIL'})**","- Secret-safety check result: **$(if(-not$ip-and-not$id-and-not$secret){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result |','|---|---|---|');foreach($r in $results){$out+="| $($r.Id) | $($r.Name) | $($r.Status) |"};$out|Set-Content $summary -Encoding UTF8;if($fail){exit 1}
