$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path -Parent $PSScriptRoot;$e=Join-Path $root 'evidence\L4-failure-recovery\S034-db-primary-stop-runbook-validation'
$p=@{Runbook=Join-Path $root 'runbooks\db-primary-stop-runbook-validation.md';Commands=Join-Path $root 'runbooks\db-primary-stop-commands.example.md';Criteria=Join-Path $root 'runbooks\db-primary-stop-criteria.example.md';Ansible=Join-Path $root 'ansible\playbooks\db-primary-status-check.example.yml';Metrics=Join-Path $root 'observability\prometheus\db-primary-stop-metrics.example.md';PrePrimary=Join-Path $e 'logs\pre-stop-primary-status.sample.txt';PreReplica=Join-Path $e 'logs\pre-stop-replication-status.sample.txt';Stop=Join-Path $e 'logs\primary-stop-event.sample.txt';Down=Join-Path $e 'logs\primary-down-detection.sample.txt';Impact=Join-Path $e 'logs\application-write-impact.sample.txt';OutageReplica=Join-Path $e 'logs\replica-state-during-primary-stop.sample.txt';Recovery=Join-Path $e 'logs\primary-recovery-event.sample.txt';PostPrimary=Join-Path $e 'logs\post-recovery-primary-status.sample.txt';PostReplica=Join-Path $e 'logs\post-recovery-replication-status.sample.txt';Catchup=Join-Path $e 'logs\replication-catchup-after-primary-recovery.sample.txt'}
$log=Join-Path $e 'logs\db-primary-stop-runbook-validation.log';$summary=Join-Path $e 'configs\db-primary-stop-runbook-summary.md';New-Item -ItemType Directory -Force -Path (Split-Path $log),(Split-Path $summary)|Out-Null
$rs=[System.Collections.Generic.List[object]]::new();$ls=[System.Collections.Generic.List[string]]::new();$fail=0;$warn=0
function Add-R([string]$Id,[string]$Name,[string]$Result,[string]$Detail){if($Result-eq'FAIL'){$script:fail++};if($Result-eq'WARN'){$script:warn++};$x="[$Result] $Id ${Name}: $Detail";Write-Host $x;$script:ls.Add($x)|Out-Null;$script:rs.Add([pscustomobject]@{Id=$Id;Name=$Name;Result=$Result;Detail=$Detail})|Out-Null}
function T([string]$x){if(Test-Path $x -PathType Leaf){Get-Content $x -Raw}else{''}}
$missing=@($p.Values|Where-Object{-not(Test-Path $_ -PathType Leaf)});Add-R V001 'Required artifacts' $(if($missing.Count-eq 0){'PASS'}else{'FAIL'}) 'Five baselines and ten samples are required.';$c=@{};foreach($k in $p.Keys){$c[$k]=T $p[$k]};$all=($c.Values)-join"`n"
$terms=@('<primary-service-name-placeholder>','<db-replica-host-placeholder>','<binlog-file-placeholder>','<binlog-position-placeholder>','<replication-lag-threshold-seconds>','<evidence-path>','MANUAL FAULT INJECTION ONLY','MANUAL RECOVERY ACTION ONLY','not promoted');Add-R V002 'Runbook boundary' $(if(@($terms|Where-Object{$c.Runbook-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'Manual-only and no-promotion contract is required.'
$phases=@('Pre-stop primary service state','Pre-stop primary role confirmation','Pre-stop replica replication health','Manual primary stop event','Primary service down detection','Application write impact detection','Replica state during primary outage','No automatic replica promotion confirmation','Manual primary recovery action','Post-recovery primary service state','Post-recovery primary role confirmation','Post-recovery replication health','Replication catch-up validation');Add-R V003 'Criteria matrix' $(if(@($phases|Where-Object{$c.Criteria-notmatch[regex]::Escape($_)}).Count-eq 0){'PASS'}else{'FAIL'}) 'All thirteen phases are required.'
$debug=$c.Ansible-match'hosts:\s*db_primary_placeholder'-and$c.Ansible-match'ansible\.builtin\.debug'-and$c.Ansible-notmatch'(?im)^\s*(?:shell|command|service|systemd):';Add-R V004 'Ansible placeholder safety' $(if($debug){'PASS'}else{'FAIL'}) 'Debug-only example is required.';$metric=$c.Metrics-match'<db-primary-instance-placeholder>'-and$c.Metrics-match'<db-replica-instance-placeholder>';Add-R V005 'Metric placeholders' $(if($metric){'PASS'}else{'FAIL'}) 'Symbolic Primary and replica metrics are required.'
$prePrimary=$c.PrePrimary-match'Primary_Service:\s*active-placeholder'-and$c.PrePrimary-match'Primary_Role:\s*available-placeholder'-and$c.PrePrimary-match'<binlog-file-placeholder>'-and$c.PrePrimary-match'<binlog-position-placeholder>';Add-R V006 'Pre-stop Primary state' $(if($prePrimary){'PASS'}else{'FAIL'}) 'Active role and symbolic master status are required.';$preReplica=$c.PreReplica-match'Replica_IO_Running:\s*Yes'-and$c.PreReplica-match'Replica_SQL_Running:\s*Yes'-and$c.PreReplica-match'Seconds_Behind_Master:\s*0';Add-R V007 'Pre-stop replication state' $(if($preReplica){'PASS'}else{'FAIL'}) 'Healthy threads and zero lag are required.'
$stop=$c.Stop-match'MANUAL FAULT INJECTION SAMPLE'-and$c.Stop-match'Execution_By_Validator:\s*false';Add-R V008 'Manual Primary stop event' $(if($stop){'PASS'}else{'FAIL'}) 'Stop event must be manual-only.';$down=$c.Down-match'inactive-placeholder'-and$c.Down-match'connection-refused-placeholder'-and$c.Down-match'down-placeholder';Add-R V009 'Primary down detection' $(if($down){'PASS'}else{'FAIL'}) 'Service, connection, and exporter failure signals are required.';$impact=$c.Impact-match'unavailable-placeholder'-and$c.Impact-match'503-placeholder'-and$c.Impact-match'failed-placeholder'-and$c.Impact-match'Payload_Stored:\s*false';Add-R V010 'Application write impact' $(if($impact){'PASS'}else{'FAIL'}) 'Sanitized write-path failure evidence is required.'
$notPromoted=$c.OutageReplica-match'not-promoted-placeholder'-and$c.OutageReplica-match'Read_Only:\s*enabled-placeholder'-and$c.OutageReplica-match'Replica_IO_Running:\s*No'-and$c.OutageReplica-match'Seconds_Behind_Master:\s*NULL';Add-R V011 'Replica no-promotion state' $(if($notPromoted){'PASS'}else{'FAIL'}) 'Replica must remain read-only and unpromoted.';$recovery=$c.Recovery-match'MANUAL RECOVERY ACTION SAMPLE'-and$c.Recovery-match'Execution_By_Validator:\s*false';Add-R V012 'Manual Primary recovery event' $(if($recovery){'PASS'}else{'FAIL'}) 'Recovery must be manual-only.'
$postPrimary=$c.PostPrimary-match'Primary_Service:\s*active-placeholder'-and$c.PostPrimary-match'Primary_Role:\s*restored-placeholder'-and$c.PostPrimary-match'<binlog-file-placeholder>'-and$c.PostPrimary-match'<binlog-position-placeholder>';$postReplica=$c.PostReplica-match'Replica_IO_Running:\s*Yes'-and$c.PostReplica-match'Replica_SQL_Running:\s*Yes'-and$c.PostReplica-match'Seconds_Behind_Master:\s*0';Add-R V013 'Post-recovery Primary and replication' $(if($postPrimary-and$postReplica){'PASS'}else{'FAIL'}) 'Restored Primary role and healthy replication are required.';$catchup=$c.Catchup-match'within-threshold-placeholder'-and$c.Catchup-match'IO_Thread:\s*healthy'-and$c.Catchup-match'SQL_Thread:\s*healthy'-and$c.Catchup-match'Replication_Error:\s*none-placeholder';Add-R V014 'Replication catch-up' $(if($catchup){'PASS'}else{'FAIL'}) 'Healthy catch-up/no-error judgment is required.'
$elapsed=[regex]::Match($c.Stop,'(?im)^Recovery_Elapsed_Seconds:\s*(\d+(?:\.\d+)?)\s*$');Add-R V015 'Recovery timing' $(if($elapsed.Success){'PASS'}else{'WARN'}) 'Unmeasured time leaves threshold compliance unproven.'
$bad=$c.PostPrimary-match'(?i)(inactive|unavailable|failed)'-or$c.PostReplica-match'(?i)(Running:\s*No|Seconds_Behind_Master:\s*(?:NULL|[1-9]\d*))'-or$c.Catchup-match'(?i)Replication_Error:\s*(?!none-placeholder)\S+';Add-R V016 'Recovered-state failure indicators' $(if(-not$bad){'PASS'}else{'FAIL'}) 'No unhealthy recovered state may remain.'
$forbidden=@(Get-ChildItem $root -Recurse -File -Force -ErrorAction SilentlyContinue|Where-Object{$_.FullName-notmatch'[\\/]\.git[\\/]'-and$_.Name-match'(?i)(?:^|[-_])dump(?:[-_.]|$)|\.dump$|\.sql\.gz$|\.pem$|\.key$|^my\.cnf$|^\.my\.cnf$'});$ip=[regex]::Matches($all,'(?<![A-Za-z0-9<])(?:\d{1,3}\.){3}\d{1,3}(?![A-Za-z0-9>])').Count;$secret=$all-match'(?im)^\s*(?:password|user|token|secret|dsn|connection_string)\s*[:=]\s*(?!["'']?<)\S+'-or$all-match'-----BEGIN .*PRIVATE KEY-----';$safe=$forbidden.Count-eq 0-and$ip-eq 0-and-not$secret;Add-R V017 'Database and payload safety' $(if($safe){'PASS'}else{'FAIL'}) 'No dump, credential, payload, address, key, or secret may exist.'
$script=Get-Content $PSCommandPath -Raw;$unsafe=$script-match'(?im)^\s*(?:mysql|mariadb|systemctl|service|ansible-playbook|curl|Invoke-WebRequest|Invoke-RestMethod)\b';Add-R V018 'Execution safety boundary' $(if(-not$unsafe){'PASS'}else{'FAIL'}) 'No DB, service, Ansible, monitoring, or network execution is allowed.'
$ts=(Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK');$overall=if($fail-eq 0){'PASS'}else{'FAIL'};$final="[$overall] DB Primary stop runbook (StaticEvidence): $fail critical failure(s), $warn warning(s).";Write-Host $final;@('SNSD Multi-Cloud Ops - S034 DB Primary Stop Runbook Validation',"Generated: $ts",'Validation mode: StaticEvidence','')+@($ls)+@('', $final,'No database, service, SQL, promotion, failover, monitoring, or network action was executed.')|Set-Content $log -Encoding UTF8
$out=@('# DB Primary Stop Runbook Summary','', '- Scenario: S034-db-primary-stop-runbook-validation',"- Generated: $ts",'- Validation mode: **StaticEvidence**',"- Required file check result: **$(if($missing.Count-eq 0){'PASS'}else{'FAIL'})**","- Pre-stop state result: **$(if($prePrimary-and$preReplica){'PASS'}else{'FAIL'})**","- Manual stop result: **$(if($stop){'PASS'}else{'FAIL'})**","- Down and write-impact result: **$(if($down-and$impact){'PASS'}else{'FAIL'})**","- No-promotion result: **$(if($notPromoted){'PASS'}else{'FAIL'})**","- Manual recovery result: **$(if($recovery){'PASS'}else{'FAIL'})**","- Post-recovery result: **$(if($postPrimary-and$postReplica-and$catchup){'PASS'}else{'FAIL'})**","- Secret-safety result: **$(if($safe){'PASS'}else{'FAIL'})**","- Final judgment: **$overall**",'','| Check ID | Check | Result | Detail |','|---|---|---|---|');foreach($r in $rs){$out+="| $($r.Id) | $($r.Name) | $($r.Result) | $($r.Detail) |"};$out|Set-Content $summary -Encoding UTF8;if($fail-gt 0){exit 1};exit 0


