apiVersion: v1
kind: Service
metadata:
  name: grant-api
  namespace: control-service
  labels:
    app.kubernetes.io/name: grant-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grant-api
  ports:
    - {name: http, port: 8002, targetPort: http, protocol: TCP}
