apiVersion: v1
kind: ServiceAccount
metadata:
  name: grant-api
  namespace: control-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grant-expiry
  namespace: control-service
automountServiceAccountToken: false
